import test from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync,randomBytes} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,stat,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {request as httpRequest} from 'node:http';
process.env.WIS_DB_PATH=':memory:';
const {openDatabase}=await import('./db.mjs');
const {makeServer}=await import('./server.mjs');
test('local HTTP authorization, consent, queue transaction, replay and private QR',async()=>{
 const database=openDatabase(':memory:');const salt='test-salt',password=randomBytes(20).toString('hex');database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 const temp=await mkdtemp(resolve(tmpdir(),'wis-backend-test-'));await mkdir(resolve(temp,'baileys-auth'));await writeFile(resolve(temp,'baileys-auth','creds.json'),'private-auth-fixture');const authStateUpdatedAt=(await stat(resolve(temp,'baileys-auth','creds.json'))).mtime.toISOString();const server=makeServer(database,{stateDir:temp,adminUsername:'ortu'});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 const call=async(path,method='GET',body,token,headers={})=>{const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),Origin:base,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 const original=process.env.WIS_OUTBOUND_ENABLED;
 try{
  const originalDeploymentKind=process.env.WIS_DEPLOYMENT_KIND;
  try{
   process.env.WIS_DEPLOYMENT_KIND='production';assert.deepEqual((await call('/api/runtime-info')).json.data,{environment:'production',storage:'sqlite'});
   delete process.env.WIS_DEPLOYMENT_KIND;assert.deepEqual((await call('/api/runtime-info')).json.data,{environment:'local',storage:'sqlite'});
  }finally{if(originalDeploymentKind===undefined)delete process.env.WIS_DEPLOYMENT_KIND;else process.env.WIS_DEPLOYMENT_KIND=originalDeploymentKind;}
  const publicLocalStatus=await call('/api/local-status');assert.equal(publicLocalStatus.status,200);assert.deepEqual(publicLocalStatus.json.data,{status:'disconnected',error:null,last_disconnect:null});assert.equal(JSON.stringify(publicLocalStatus.json.data).includes('auth_state_updated_at'),false);
  assert.equal((await call('/api/whatsapp/recover','POST',{})).status,401);
  assert.deepEqual((await call('/api/login-config')).json.data,{username:'ortu',password_recovery_available:false});assert.equal((await call('/api/v1/contacts')).status,401);
  assert.equal((await call('/api/whatsapp/qr')).status,401);
  assert.equal((await call('/api/login','POST',{password},null,{Origin:'https://other.example'})).status,403);
  assert.equal((await call('/api/login','POST',{username:'localadmin',password})).status,401);const login=await call('/api/login','POST',{username:'ortu',password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
  database.prepare("UPDATE connections SET status='qr_pending',qr_payload='private-qr',qr_expires_at=?").run(new Date(Date.now()+30000).toISOString());database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('connection_diagnostics','wis-5679',?,?)").run(JSON.stringify({last_disconnect_at:new Date().toISOString(),status_code:440,reason:'connection_replaced',phone:'private-phone',qr_payload:'private-qr'}),new Date().toISOString());const publicQrPending=await call('/api/local-status');assert.deepEqual(publicQrPending.json.data,{status:'qr_pending',error:null,last_disconnect:{at:publicQrPending.json.data.last_disconnect.at,status_code:440,reason:'connection_replaced'}});assert.equal(JSON.stringify(publicQrPending.json.data).includes('private'),false);const connection=await call('/api/whatsapp/connection');assert.equal(connection.json.data.qr_payload,undefined);assert.equal(connection.json.data.last_disconnect.reason,'connection_replaced');assert.ok(Math.abs(Date.parse(connection.json.data.auth_state_updated_at)-Date.parse(authStateUpdatedAt))<5);assert.equal(JSON.stringify(connection.json.data).includes('private-auth-fixture'),false);
  const qr=await fetch(base+'/api/whatsapp/qr',{headers:{Cookie:cookie,Origin:base}});assert.equal(qr.status,200);assert.equal(qr.headers.get('content-type'),'image/svg+xml');assert.equal(qr.headers.get('cache-control'),'no-store');const svg=await qr.text();assert.match(svg,/<svg\b/);assert.equal(svg.includes('private-qr'),false);
  const readToken=(await call('/api/v1/tokens','POST',{name:'read only',scopes:['read']})).json.data.token;const readerQr=await fetch(base+'/api/whatsapp/qr',{headers:{Authorization:'Bearer '+readToken,Origin:base}});assert.equal(readerQr.status,403);
  database.prepare("UPDATE connections SET qr_expires_at=?").run(new Date(Date.now()-1000).toISOString());const expiredQr=await fetch(base+'/api/whatsapp/qr',{headers:{Cookie:cookie,Origin:base}});assert.equal(expiredQr.status,404);assert.equal((await expiredQr.json()).error,'qr_unavailable');
  database.prepare("UPDATE connections SET status='disconnected',last_error='session_revoked',command=NULL,qr_payload=NULL,qr_expires_at=NULL WHERE id='wis-5679'").run();
  assert.equal((await call('/api/whatsapp/recover','POST',{})).status,202);
  assert.equal(database.prepare("SELECT command FROM connections WHERE id='wis-5679'").get().command,'recover');
  assert.equal((await call('/api/whatsapp/recover','POST',{})).json.error,'connection_command_pending');
  database.prepare("UPDATE connections SET status='connected',last_error=NULL,command=NULL WHERE id='wis-5679'").run();
  assert.equal((await call('/api/whatsapp/recover','POST',{})).json.error,'session_recovery_not_available');
  const created=await call('/api/v1/tokens','POST',{name:'send only',scopes:['send']});assert.equal(created.status,201);const token=created.json.data.token;
  assert.equal((await call('/api/v1/contacts','GET',null,token)).status,403);
  const contact=(await call('/api/v1/contacts','POST',{phone_e164:'+12025555679',display_name:'Local test',consent_at:new Date().toISOString(),consent_source:'test',consent_scope:'test'})).json.data;
  const payload={to:contact.phone_e164,type:'text',body:'local simulation'};process.env.WIS_OUTBOUND_ENABLED='false';assert.equal((await call('/api/v1/messages','POST',payload,token,{'Idempotency-Key':'one'})).json.error,'outbound_disabled');assert.equal(database.prepare('SELECT count(*) AS n FROM operations').get().n,0);
  process.env.WIS_OUTBOUND_ENABLED='true';const first=await call('/api/v1/messages','POST',payload,token,{'Idempotency-Key':'one'});assert.equal(first.status,202);assert.ok(first.json.data.message_id);
  assert.equal((await call('/api/v1/messages','POST',payload,token,{'Idempotency-Key':'one'})).json.data.id,first.json.data.id);assert.equal(database.prepare('SELECT count(*) AS n FROM messages').get().n,1);
  assert.equal((await call('/api/v1/messages','POST',{...payload,body:'changed'},token,{'Idempotency-Key':'one'})).status,409);
  await call('/api/v1/contacts','PATCH',{id:contact.id,opted_out_at:new Date().toISOString()});assert.equal((await call('/api/v1/messages','POST',payload,token,{'Idempotency-Key':'two'})).status,403);
  assert.equal((await call('/api/v1/contacts','PATCH',{id:contact.id,opted_out_at:null})).status,409);
  await call('/api/v1/tokens?id='+created.json.data.id,'DELETE');assert.equal((await call('/api/v1/messages','POST',payload,token,{'Idempotency-Key':'three'})).status,401);
  database.prepare("INSERT INTO contacts(id,wa_jid,created_at) VALUES('lid','123@lid',?)").run(new Date().toISOString());
  database.prepare("UPDATE operations SET status='delivered' WHERE id=?").run(first.json.data.id);database.prepare("UPDATE operations SET status='read' WHERE id=?").run(first.json.data.id);
  database.prepare("INSERT INTO webhooks(id,url,secret,enabled,created_at) VALUES('test','https://example.com','test',1,?)").run(new Date().toISOString());database.prepare("UPDATE messages SET delivery_status='read' WHERE id=?").run(first.json.data.message_id);assert.equal(database.prepare('SELECT count(*) AS n FROM webhook_deliveries').get().n,1);
  for(let i=0;i<70;i++)database.prepare('INSERT INTO contacts(id,display_name,created_at) VALUES(?,?,?)').run('page-'+String(i).padStart(3,'0'),'Pagination contact '+i,new Date().toISOString());
  const paged=await call('/api/v1/contacts?q=Pagination&limit=10&offset=20');assert.equal(paged.json.meta.total,70);assert.equal(paged.json.data.length,10);assert.equal(paged.json.meta.has_more,true);
  assert.equal((await call('/api/v1/contacts?limit=0')).status,400);assert.equal((await call('/api/v1/contacts?q=%25')).json.meta.total,0);
  assert.equal((await call('/api/v1/overview')).json.data.counts.contacts,72);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('profile','wis-5679',?,?)").run(JSON.stringify({name:'Local account'}),new Date().toISOString());
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('account_username','wis-5679',?,?)").run(JSON.stringify({available:true,response_verified:true,username:'wis_owner',source:'usync_username_protocol'}),new Date().toISOString());
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('group','1@g.us',?,?)").run(JSON.stringify({subject:'Actual group',participants:[]}),new Date().toISOString());
  const account=(await call('/api/v1/account')).json.data;assert.equal(account.profile.data.name,'Local account');assert.equal(account.username.data.username,'wis_owner');assert.equal(account.profile.data.username,'wis_owner');assert.equal(account.profile.data.username_available,true);assert.equal((await call('/api/v1/groups?q=Actual')).json.meta.total,1);
  assert.equal((await call('/api/v1/groups?id=1%40g.us')).json.data.subject,'Actual group');assert.equal((await call('/api/v1/groups?id=404%40g.us')).status,404);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('contact','12025555679@s.whatsapp.net',?,?)").run(JSON.stringify({name:'Observed contact',status:'Available'}),new Date().toISOString());
  const detail=await call('/api/v1/contacts?id='+contact.id);assert.equal(detail.json.data.contact.id,contact.id);assert.equal(detail.json.data.profile.data.name,'Observed contact');assert.equal(detail.json.data.conversations.length,1);assert.equal((await call('/api/v1/contacts?id=missing')).status,404);
  assert.equal((await call('/api/v1/products')).json.meta.observed,false);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('catalog','self',?,?)").run(JSON.stringify({available:true,product_count:0}),new Date().toISOString());
  assert.equal((await call('/api/v1/products')).json.meta.collection_status,'observed_partial');
  database.prepare("UPDATE snapshots SET payload=? WHERE kind='catalog'").run(JSON.stringify({available:true,product_count:0,response_verified:true}));
  assert.equal((await call('/api/v1/products')).json.meta.collection_status,'complete');
  const emptyCatalog=await call('/api/v1/products');assert.equal(emptyCatalog.json.meta.observed,true);assert.equal(emptyCatalog.json.meta.total,0);assert.equal(emptyCatalog.json.meta.summaries[0].data.available,true);
  const catalogNow=new Date().toISOString();for(const [owner,scope] of [['own@s.whatsapp.net','own_account'],['12025555679@s.whatsapp.net','contact_catalog']])database.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run('catalog',owner,JSON.stringify({available:true,scope}),catalogNow);
  for(const [id,owner,scope] of [['own-current','own@s.whatsapp.net','own_account'],['own-stale','own@s.whatsapp.net','public_catalog'],['contact-current','12025555679@s.whatsapp.net','contact_catalog']])database.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run('product',owner+':'+id,JSON.stringify({id,owner_jid:owner,scope,name:id}),catalogNow);
  const scopedProducts=await call('/api/v1/products');assert.equal(scopedProducts.json.meta.total,2);assert.deepEqual(scopedProducts.json.data.map(x=>x.id.split(':').at(-1)).sort(),['contact-current','own-current']);
  database.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run('catalog','diagnostic-owner',JSON.stringify({scope:'own_account',last_attempt_scope:'own_account',last_attempt_source:'checked_baileys_iq_fallback',last_attempt_at:'2026-09-28T12:00:00.000Z',private_token:'never-return'}),catalogNow);
  database.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run('product','diagnostic-owner:diagnostic-product',JSON.stringify({id:'diagnostic-product',owner_jid:'diagnostic-owner',scope:'own_account',name:'Diagnostic product'}),catalogNow);
  const catalogDetail=await call('/api/v1/products?id=diagnostic-owner%3Adiagnostic-product');const catalogSummary=catalogDetail.json.meta.summaries[0].data;assert.equal(catalogSummary.last_attempt_scope,'own_account');assert.equal(catalogSummary.last_attempt_source,'checked_baileys_iq_fallback');assert.equal(catalogSummary.last_attempt_at,'2026-09-28T12:00:00.000Z');assert.equal(JSON.stringify(catalogDetail.json).includes('never-return'),false);
  for(const [kind,id,name]of [['product','self:1','Observed product'],['collection','self:2','Observed collection'],['label','label-1','Observed label'],['label','label-deleted','Deleted label'],['community','2@g.us','Observed community'],['newsletter','3@newsletter','Observed channel']])database.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run(kind,id,JSON.stringify({name,...(id==='label-deleted'?{deleted:true}:{})}),new Date().toISOString());
  for(const endpoint of ['products','collections','labels','communities','channels']){const listed=await call('/api/v1/'+endpoint+'?q=Observed&limit=1');assert.equal(listed.json.meta.total,1);assert.equal(listed.json.data.length,1);}
  database.prepare("DELETE FROM snapshots WHERE kind='newsletter'").run();database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('newsletters','self',?,?)").run(JSON.stringify({available:true,response_verified:false,known_only:true,count:0,attempted_count:0,failure_count:0,unattempted_count:0,complete:false,partial:true,source:'known_local_channels'}),new Date().toISOString());
  const knownOnlyChannels=await call('/api/v1/channels');assert.deepEqual(knownOnlyChannels.json.data,[]);assert.equal(knownOnlyChannels.json.meta.total,0);assert.equal(knownOnlyChannels.json.meta.observed,true);assert.equal(knownOnlyChannels.json.meta.collection_status,'observed_partial');assert.equal(knownOnlyChannels.json.meta.summaries[0].data.response_verified,false);assert.equal(knownOnlyChannels.json.meta.summaries[0].data.known_only,true);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('newsletter','3@newsletter',?,?)").run(JSON.stringify({name:'Observed channel'}),new Date().toISOString());
  const activeLabels=await call('/api/v1/labels');assert.equal(activeLabels.json.meta.total,1);assert.equal(activeLabels.json.meta.deleted_count,1);assert.deepEqual(activeLabels.json.data.map(x=>x.name),['Observed label']);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('blocklist','wis-5679',?,?)").run(JSON.stringify({ids:['123@s.whatsapp.net'],available:true}),new Date().toISOString());
  const reader=(await call('/api/v1/tokens','POST',{name:'reader',scopes:['read']})).json.data.token;assert.equal((await call('/api/v1/blocklist','GET',null,reader)).status,403);assert.equal((await call('/api/v1/snapshots?kind=blocklist','GET',null,reader)).status,400);assert.equal((await call('/api/v1/blocklist')).json.data[0].id,'123@s.whatsapp.net');
  assert.equal((await fetch(base+'/api/v1/newsletter-counts?target=3%40newsletter')).status,401);assert.equal((await call('/api/v1/newsletter-counts?target=3%40newsletter','GET',null,reader)).status,403);assert.equal((await call('/api/v1/newsletter-counts?target=invalid')).status,400);assert.equal((await call('/api/v1/newsletter-counts?target=9%40newsletter')).status,404);
  assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter',target:'999@newsletter'})).status,404);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter',target:'https://example.com'})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter',target:'3@newsletter'})).status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'https://example.com'})).status,400);const countCommand=await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'3@newsletter'});assert.equal(countCommand.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'3@newsletter'})).json.data.id,countCommand.json.data.id);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'9@newsletter'})).status,404);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'3@newsletter',action:'follow'})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'newsletter_counts',target:'3@newsletter'},reader)).status,403);
  const countsNow=new Date().toISOString();database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('newsletter_counts','3@newsletter',?,?)").run(JSON.stringify({available:true,response_verified:false,partial:true,source:'baileys_read_only_aggregate',fields:{subscribers:{available:true,response_verified:true,stale:false,value:42,observed_at:countsNow},admin_count:{available:false,response_verified:false,stale:true,value:2,error:'access_denied',observed_at:'2026-01-01T00:00:00.000Z',provider_secret:'must_not_return'},secret:'must_not_return'}}),countsNow);const channelCounts=await call('/api/v1/newsletter-counts?target=3%40newsletter');assert.equal(channelCounts.json.data.subscribers.value,42);assert.equal(channelCounts.json.data.subscribers.available,true);assert.equal(channelCounts.json.data.admin_count.value,2);assert.equal(channelCounts.json.data.admin_count.stale,true);assert.equal(channelCounts.json.data.admin_count.error,'access_denied');assert.equal(JSON.stringify(channelCounts.json).includes('must_not_return'),false);
  assert.equal((await call('/api/v1/sync','POST',{kind:'community',target:'2@g.us'})).status,202);
  for(const kind of ['catalog','collections','blocklist','communities','newsletters'])assert.equal((await call('/api/v1/sync','POST',{kind})).status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'catalog',target:'unknown'})).status,400);
  assert.equal((await call('/api/v1/account-limits','GET',null,reader)).status,403);assert.equal((await fetch(base+'/api/v1/account-limits')).status,401);assert.equal((await call('/api/v1/snapshots?kind=account_limits','GET',null,reader)).status,400);
  const unknownLimits=(await call('/api/v1/account-limits')).json.data;assert.equal(unknownLimits.observed,false);assert.equal(unknownLimits.quota.total_quota,null);assert.equal(unknownLimits.timelock.is_active,null);
  const limitsCommand=await call('/api/v1/sync','POST',{kind:'account_limits'});assert.equal(limitsCommand.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'account_limits'})).json.data.id,limitsCommand.json.data.id);assert.equal((await call('/api/v1/sync','POST',{kind:'account_limits',target:null})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'account_limits'},reader)).status,403);
  const usernameCommand=await call('/api/v1/sync','POST',{kind:'account_username'});assert.equal(usernameCommand.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'account_username',target:null})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'account_username'},reader)).status,403);
   const contactProfiles=await call('/api/v1/sync','POST',{kind:'contact_profiles'});assert.equal(contactProfiles.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'contact_profiles'})).json.data.id,contactProfiles.json.data.id);database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('contact_profiles','wis-5679',?,?)").run(JSON.stringify({available:true,scope:'known_contacts',batch_size:3,checked_count:2,verified_read_count:4,failure_count:0,partial:true,complete:false}),new Date().toISOString());assert.equal((await call('/api/v1/snapshots?kind=contact_profiles','GET',null,reader)).json.data[0].kind,'contact_profiles');
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('account_limits','wis-5679',?,?)").run(JSON.stringify({quota:{available:true,response_verified:true,total_quota:0,used_quota:-1,cycle_start_timestamp:'1234567890',cycle_end_timestamp:'secret-private',capping_status:'CAPPED',ote_status:'secret-private',secret:'secret-private'},timelock:{available:false,error:'secret-private',status_code:500,is_active:'false',enforcement_type:'secret-private'},partial:true,observed_at:new Date().toISOString()}),new Date().toISOString());
  const limits=(await call('/api/v1/account-limits')).json.data;assert.equal(limits.quota.total_quota,0);assert.equal(limits.quota.used_quota,null);assert.equal(limits.quota.capping_status,'CAPPED');assert.equal(limits.quota.cycle_start_timestamp,'1234567890');assert.equal(limits.timelock.is_active,null);assert.equal(limits.timelock.status_code,500);assert.equal(limits.timelock.error,'read_unavailable');assert.equal(limits.whapi_projection.getnewchatlimit.fields.cap_type,'individual_new_chat_thread');assert.equal(limits.whapi_projection.getnewchatlimit.fields.quota_remaining,null);assert.equal(limits.whapi_projection.getnewchatlimit.fields.is_capped,null);assert.equal(limits.whapi_projection.getnewchatlimit.fields.cycle_start_at,1234567890);assert.equal(limits.whapi_projection.getnewchatlimit.fields.updated_at,null);assert.equal(limits.whapi_projection.getreachouttimelock.fields.is_restricted,null);assert.equal(JSON.stringify(limits).includes('secret-private'),false);assert.equal((await call('/api/v1/account-limits','POST',{})).status,404);
  database.prepare("UPDATE snapshots SET payload=json_set(payload,'$.timelock.enforcement_type','BIZ_QUALITY') WHERE kind='account_limits'").run();assert.equal((await call('/api/v1/account-limits')).json.data.timelock.enforcement_type,'BIZ_QUALITY');
  const conversationId=database.prepare('SELECT conversation_id FROM messages WHERE id=?').get(first.json.data.message_id).conversation_id;const conversationJid=database.prepare('SELECT wa_chat_id FROM conversations WHERE id=?').get(conversationId).wa_chat_id;
   database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('chat',?,?,?)").run(conversationJid,JSON.stringify({unreadCount:3,archived:false,secret:'private-chat-secret',nested:{url:'private-chat-secret'}}),new Date().toISOString());database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('presence',?,?,?)").run(conversationJid,JSON.stringify({presences:{'123@s.whatsapp.net':{lastKnownPresence:'available',observed_at:'2026-09-28T06:00:00.000Z',secret:'private-presence-secret'}}}),new Date().toISOString());
   const chatDetail=(await call('/api/v1/conversations?id='+conversationId,'GET',null,reader)).json.data;assert.equal(chatDetail.conversation.id,conversationId);assert.equal(chatDetail.message_counts.total,1);assert.equal(chatDetail.message_counts.out,1);assert.equal(chatDetail.history_complete,false);assert.equal(chatDetail.snapshots[0].data.unreadCount,3);const presenceDetail=chatDetail.snapshots.find(snapshot=>snapshot.kind==='presence');assert.equal(presenceDetail.data.presences['123@s.whatsapp.net'].lastKnownPresence,'available');assert.equal(presenceDetail.data.presences['123@s.whatsapp.net'].observed_at,'2026-09-28T06:00:00.000Z');assert.equal(presenceDetail.data.presences['123@s.whatsapp.net'].observed_seq,undefined);assert.equal(presenceDetail.data.presences_truncated,false);assert.equal(JSON.stringify(chatDetail).includes('private-presence-secret'),false);assert.equal(JSON.stringify(chatDetail).includes('private-chat-secret'),false);const manyPresences=Object.fromEntries(Array.from({length:257},(_,index)=>[`${10000000+index}@s.whatsapp.net`,{lastKnownPresence:'available'}]));database.prepare("UPDATE snapshots SET payload=? WHERE kind='presence' AND resource_id=?").run(JSON.stringify({presences:manyPresences}),conversationJid);const truncatedPresence=(await call('/api/v1/conversations?id='+conversationId,'GET',null,reader)).json.data.snapshots.find(snapshot=>snapshot.kind==='presence');assert.equal(truncatedPresence.data.presences_truncated,true);assert.equal(Object.keys(truncatedPresence.data.presences).length,256);assert.equal((await call('/api/v1/conversations?id=missing','GET',null,reader)).status,404);assert.equal((await call('/api/v1/conversations?id=','GET',null,reader)).status,400);
  database.prepare('UPDATE conversations SET contact_id=NULL WHERE id=?').run(conversationId);const contactChats=(await call('/api/v1/contacts?id='+contact.id,'GET',null,reader)).json.data.conversations;assert.ok(contactChats.some(c=>c.id===conversationId&&c.relation_origins.includes('exact_phone_jid')));assert.equal((await call('/api/v1/conversations?id='+conversationId,'GET',null,reader)).json.data.contact,null);assert.equal(database.prepare('SELECT contact_id FROM conversations WHERE id=?').get(conversationId).contact_id,null);database.prepare('UPDATE conversations SET contact_id=? WHERE id=?').run(contact.id,conversationId);
  const unknownGroupRead=await call('/api/v1/group-requests?target=1%40g.us','GET',null,reader);assert.equal(unknownGroupRead.json.data.collection_status,'not_collected');
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('group_requests','1@g.us',?,?)").run(JSON.stringify({available:true,response_verified:true,requests:[{jid:'123@lid',request_method:'invite_link',request_time:'12345',invite_code:'private-secret',url:'https://secret.invalid'}]}),new Date().toISOString());
  const requests=await call('/api/v1/group-requests?target=1%40g.us','GET',null,reader);assert.equal(requests.json.data.collection_status,'complete');assert.equal(requests.json.data.requests[0].jid,'123@lid');assert.equal(JSON.stringify(requests.json).includes('private-secret'),false);
  database.prepare("INSERT OR REPLACE INTO snapshots(kind,resource_id,payload,updated_at) VALUES('community','2@g.us',?,?)").run(JSON.stringify({subject:'Community',community_jid:'2@g.us',is_community:true,linked_groups_truncated:true,linked_groups:[{id:'3@g.us',subject:'Linked',size:4,secret:'must_not_return'}]}),new Date().toISOString());const communityDetail=await call('/api/v1/communities?id=2%40g.us','GET',null,reader);assert.equal(communityDetail.json.data.community_jid,'2@g.us');assert.equal(communityDetail.json.data.is_community,true);assert.equal(communityDetail.json.data.linked_groups_truncated,true);assert.equal(communityDetail.json.data.linked_groups[0].id,'3@g.us');assert.equal(JSON.stringify(communityDetail.json).includes('must_not_return'),false);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('community_subgroups','2@g.us',?,?)").run(JSON.stringify({available:false,stale:true,error:'private-secret',groups:[{id:'1@g.us',subject:'Linked observed',inviteCode:'private-secret'}]}),new Date().toISOString());
  const subgroup=await call('/api/v1/community-subgroups?target=2%40g.us','GET',null,reader);assert.equal(subgroup.json.data.collection_status,'unavailable');assert.equal(subgroup.json.data.groups[0].subject,'Linked observed');assert.equal(JSON.stringify(subgroup.json).includes('private-secret'),false);assert.equal((await call('/api/v1/communities?id=2%40g.us','GET',null,reader)).json.data.subgroups.stale,true);
  database.prepare("UPDATE snapshots SET payload=json_set(payload,'$.error','access_denied') WHERE kind='community_subgroups' AND resource_id='2@g.us'").run();assert.equal((await call('/api/v1/community-subgroups?target=2%40g.us','GET',null,reader)).json.data.error,'access_denied');
  database.prepare("UPDATE snapshots SET payload=json_set(payload,'$.available',json('false'),'$.error','provider_error','$.status_code',500) WHERE kind='group_requests' AND resource_id='1@g.us'").run();
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('group_join_event','1@g.us:123@lid',?,?)").run(JSON.stringify({group_id:'1@g.us',participant:'123@lid',action:'created',method:'invite_link',observed_at:new Date().toISOString(),secret:'private-evidence',history:[{action:'created',secret:'private-evidence'}]}),new Date().toISOString());
  const partialRequests=await call('/api/v1/group-requests?target=1%40g.us','GET',null,reader);assert.equal(partialRequests.json.data.status_code,500);assert.equal(partialRequests.json.data.available,false);assert.equal(partialRequests.json.data.observed_events[0].participant,'123@lid');assert.equal(partialRequests.json.data.observed_events_meta.current_pending_inferred,false);assert.equal(JSON.stringify(partialRequests.json).includes('private-evidence'),false);
  assert.equal((await call('/api/v1/sync','POST',{kind:'group_requests',target:'1@g.us'})).status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'community_subgroups',target:'2@g.us'})).status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'group_requests',target:'999@g.us'})).status,404);assert.equal((await call('/api/v1/sync','POST',{kind:'group_requests',target:'1@g.us',action:'approve'})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'community_subgroups',target:'1@g.us'})).status,404);
  const sync=await call('/api/v1/sync','POST',{kind:'groups'});assert.equal(sync.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'groups'})).json.data.id,sync.json.data.id);assert.equal(database.prepare("SELECT command FROM connections WHERE id='wis-5679'").get().command,null);
  assert.equal((await call('/api/v1/sync','POST',{kind:'send'})).status,400);assert.equal((await call('/api/v1/settings','PATCH',{outbound_enabled:true})).status,400);assert.equal((await call('/api/v1/settings','PATCH',{poll_seconds:20})).json.data.poll_seconds,20);
  for(let i=0;i<1002;i++)database.prepare('INSERT INTO events(id,kind,payload,created_at) VALUES(?,?,?,?)').run('event-'+i,'test','{}',new Date().toISOString());assert.equal((await call('/api/v1/events?limit=5')).json.meta.total,1000);
  const originalMessage=database.prepare('SELECT * FROM messages WHERE id=?').get(first.json.data.message_id);database.prepare("UPDATE messages SET wa_message_id='wa-detail',media_path='local-test.pdf' WHERE id=?").run(originalMessage.id);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('message','wa-detail',?,?)").run(JSON.stringify({type:'text',details:{quote:{stanzaId:'prior',text:'Observed quote'}}}),new Date().toISOString());
  database.prepare("INSERT INTO events(id,kind,resource_id,payload,created_at) VALUES('reaction','messages.reaction','wa-detail',?,?)").run(JSON.stringify({reaction:{text:'👍'}}),new Date().toISOString());
  const messageDetail=await call('/api/v1/messages?id='+originalMessage.id);assert.equal(messageDetail.json.data.contact.id,contact.id);assert.equal(messageDetail.json.data.details.quote.text,'Observed quote');assert.equal(messageDetail.json.data.reactions.events.length,1);assert.equal(messageDetail.json.data.history.complete,false);assert.equal((await call('/api/v1/messages?id=missing')).status,404);
  const chat=database.prepare('SELECT * FROM conversations WHERE id=?').get(originalMessage.conversation_id);const historyRequest=await call('/api/v1/sync','POST',{kind:'history',target:chat.wa_chat_id});assert.equal(historyRequest.status,202);assert.equal(historyRequest.json.data.requested_count,50);assert.equal((await call('/api/v1/sync','POST',{kind:'history',target:chat.wa_chat_id,count:100})).status,400);assert.equal((await call('/api/v1/sync','POST',{kind:'history',target:'999@s.whatsapp.net'})).status,404);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('history_request',?,?,?)").run(historyRequest.json.data.id,JSON.stringify({target:chat.wa_chat_id,status:'requested',request_id:'request-test',requested_count:50}),new Date().toISOString());assert.equal((await call('/api/v1/history?conversation_id='+chat.id)).json.data.latest_request.data.status,'requested');assert.equal((await call('/api/v1/history?conversation_id='+chat.id)).json.data.complete,false);
  database.prepare("INSERT INTO conversations(id,wa_chat_id) VALUES('other-chat','321@s.whatsapp.net')").run();database.prepare("INSERT INTO messages(id,conversation_id,direction,body,created_at) VALUES('other-message','other-chat','in','local simulation across chats',?)").run(new Date().toISOString());assert.equal((await call('/api/v1/messages?q=local%20simulation')).json.meta.total,2);assert.equal((await call('/api/v1/messages?q=local%20simulation&conversation_id='+chat.id)).json.meta.total,1);assert.equal((await call('/api/v1/sync','POST',{kind:'history',target:'321@s.whatsapp.net'})).json.error,'history_anchor_unavailable');
  await mkdir(resolve(temp,'media'),{recursive:true});await writeFile(resolve(temp,'media','local-test.pdf'),'%PDF-1.7\n');await writeFile(resolve(temp,'media','unregistered.pdf'),'%PDF-1.7\n');
  assert.equal((await fetch(base+'/api/v1/media?path=local-test.pdf')).status,401);const download=await fetch(base+'/api/v1/media?path=local-test.pdf',{headers:{Cookie:cookie}});assert.equal(download.status,200);assert.equal(download.headers.get('content-type'),'application/pdf');assert.equal((await call('/api/v1/media?path=..%2Fadmin-access.txt')).status,400);
  assert.equal((await call('/api/v1/media?path=unregistered.pdf')).status,404);const mediaList=await call('/api/v1/media');assert.equal(mediaList.json.meta.total,1);assert.equal(mediaList.json.data[0].available,true);assert.equal(mediaList.json.data[0].path,'local-test.pdf');
  const uploaded=await call('/api/v1/media','POST',{mime_type:'application/pdf',base64:Buffer.from('%PDF-1.7\n').toString('base64')});assert.equal(uploaded.status,201);assert.equal((await call('/api/v1/media')).json.meta.total,2);
  assert.equal(database.prepare("SELECT count(*) AS n FROM audit WHERE action='api.read.contacts' AND actor='admin'").get().n,1);
  const hookToken=(await call('/api/v1/tokens','POST',{name:'webhook observer',scopes:['webhooks:write']})).json.data.token;
  const newHook=await call('/api/v1/webhooks','POST',{url:'https://example.com/receiver'},hookToken);assert.equal(newHook.status,201);assert.equal(newHook.json.data.enabled,false);assert.ok(newHook.json.data.secret);
  database.prepare('INSERT INTO webhook_deliveries(id,webhook_id,event_id,event_type,payload,status,attempts,available_at,last_error,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('safe-detail',newHook.json.data.id,'evt-safe','message.created',JSON.stringify({id:'evt-safe',secret:'must-not-return',data:{body:'visible content',authorization:'must-not-return'}}),'failed',5,new Date().toISOString(),'token=must-not-return',new Date().toISOString());
  const hooks=await call('/api/v1/webhooks','GET',null,hookToken);const observedHook=hooks.json.data.find(x=>x.id===newHook.json.data.id);assert.equal(observedHook.secret,undefined);assert.equal(observedHook.delivery_counts.failed,1);assert.equal(observedHook.activation_requires_approval,true);
  const deliveries=await call('/api/v1/webhook-deliveries?webhook_id='+newHook.json.data.id+'&status=failed&limit=1','GET',null,hookToken);assert.equal(deliveries.status,200);assert.equal(deliveries.json.meta.total,1);assert.equal(deliveries.json.data[0].payload,undefined);assert.equal(deliveries.json.data[0].last_error,'delivery_failed');
  assert.equal((await call('/api/v1/webhook-deliveries?status=arbitrary','GET',null,hookToken)).status,400);assert.equal((await call('/api/v1/webhook-deliveries?id=safe-detail','GET',null,hookToken)).status,403);
  const detailDelivery=await call('/api/v1/webhook-deliveries?id=safe-detail');assert.equal(detailDelivery.json.data.payload.data.body,'visible content');assert.equal(JSON.stringify(detailDelivery.json).includes('must-not-return'),false);
  for(const legacyError of ['unknownlowercasesecret','a'.repeat(64)]){database.prepare("UPDATE webhook_deliveries SET last_error=? WHERE id='safe-detail'").run(legacyError);const detail=await call('/api/v1/webhook-deliveries?id=safe-detail');assert.equal(detail.json.data.last_error,'delivery_failed');const list=await call('/api/v1/webhook-deliveries?webhook_id='+newHook.json.data.id,'GET',null,hookToken);assert.equal(list.json.data[0].last_error,'delivery_failed');assert.equal(JSON.stringify(detail.json).includes(legacyError),false);}
  database.prepare("UPDATE webhook_deliveries SET last_error='interrupted_delivery' WHERE id='safe-detail'").run();assert.equal((await call('/api/v1/webhook-deliveries?id=safe-detail')).json.data.last_error,'interrupted_delivery');
  const inventory=await call('/api/v1/webhook-events','GET',null,hookToken);assert.deepEqual(inventory.json.data.supported.map(x=>x.name),['message.created','message.updated','operation.updated']);assert.equal(inventory.json.data.reference.wire_compatible,false);
  assert.equal((await call('/api/v1/webhooks','PATCH',{id:newHook.json.data.id,enabled:true},hookToken)).status,409);const beforeDelete=database.prepare('SELECT count(*) AS n FROM webhook_deliveries WHERE webhook_id=?').get(newHook.json.data.id).n;
  const disabled=await call('/api/v1/webhooks?id='+newHook.json.data.id,'DELETE',null,hookToken);assert.equal(disabled.json.data.history_preserved,true);assert.equal(database.prepare('SELECT count(*) AS n FROM webhook_deliveries WHERE webhook_id=?').get(newHook.json.data.id).n,beforeDelete);assert.equal(database.prepare('SELECT enabled FROM webhooks WHERE id=?').get(newHook.json.data.id).enabled,0);
  const avatarTarget='123@lid',avatarFilename='11111111-1111-4111-8111-111111111111.png',png=Buffer.from([137,80,78,71,13,10,26,10]);
  assert.equal((await call('/api/v1/avatars?target='+avatarTarget)).json.data.status,'not_collected');assert.equal((await call('/api/v1/avatars?target=999%40lid')).status,404);assert.equal((await call('/api/v1/avatars?target=..%2Fadmin-access.txt')).status,400);
  await mkdir(resolve(temp,'avatars'),{recursive:true});await writeFile(resolve(temp,'avatars',avatarFilename),png);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('avatar',?,?,?)").run(avatarTarget,JSON.stringify({filename:avatarFilename,mime:'image/png',size:png.length,available:true,stale:false,url:'https://secret.invalid/token'}),new Date().toISOString());
  const avatarMeta=await call('/api/v1/avatars?target='+avatarTarget,'GET',null,reader);assert.equal(avatarMeta.status,200);assert.equal(avatarMeta.json.data.available,true);assert.equal(avatarMeta.json.data.filename,undefined);assert.equal(JSON.stringify(avatarMeta.json).includes('secret.invalid'),false);
  const avatarBytes=await fetch(base+'/api/v1/avatars?target='+avatarTarget+'&content=1',{headers:{Authorization:'Bearer '+reader}});assert.equal(avatarBytes.status,200);assert.equal(avatarBytes.headers.get('content-type'),'image/png');assert.ok(avatarBytes.headers.get('cache-control').includes('no-store'));assert.deepEqual(Buffer.from(await avatarBytes.arrayBuffer()),png);
  assert.equal((await fetch(base+'/api/v1/avatars?target='+avatarTarget+'&content=1')).status,401);assert.equal((await call('/api/v1/avatars?target='+avatarTarget,'GET',null,hookToken)).status,403);
  const avatarCommand=await call('/api/v1/sync','POST',{kind:'avatar',target:avatarTarget});assert.equal(avatarCommand.status,202);assert.equal((await call('/api/v1/sync','POST',{kind:'avatar',target:avatarTarget,url:'https://example.com'})).status,400);
  database.prepare("UPDATE snapshots SET payload=? WHERE kind='avatar' AND resource_id=?").run(JSON.stringify({filename:'../admin-access.txt',mime:'image/png',available:true}),avatarTarget);assert.equal((await call('/api/v1/avatars?target='+avatarTarget+'&content=1')).status,404);
  database.prepare("UPDATE connections SET phone='+12025555679',expected_phone_e164='+12025555679' WHERE id='wis-5679'").run();assert.equal((await call('/api/v1/avatars?target=12025555679%40s.whatsapp.net','GET',null,reader)).status,403);assert.equal((await call('/api/v1/account')).json.data.avatar.target,'12025555679@s.whatsapp.net');
  database.prepare("UPDATE connections SET expected_phone_e164=NULL WHERE id='wis-5679'").run();assert.equal((await call('/api/v1/sync','POST',{kind:'avatar',target:'12025555679@s.whatsapp.net'})).status,409);
  const emptyCalls=await call('/api/v1/calls','GET',null,reader);assert.equal(emptyCalls.json.meta.total,0);assert.equal(emptyCalls.json.meta.history_complete,false);assert.equal(emptyCalls.json.meta.legacy_events_included,false);
  const future=new Date(Date.now()+3600000).toISOString(),past=new Date(Date.now()-1000).toISOString(),storyDate=new Date(Date.now()-60000).toISOString();for(const [id,extra]of [['story-active',{}],['story-expired',{expires_at:past}],['story-revoked',{revoked:true}],['story-bad-date',{expires_at:'not-a-date'}],['story-future',{date:future}],['story-huge-expiry',{expires_at:'2099-01-01T00:00:00Z'}],['story-invalid-date',{date:'invalid'}]])database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('story',?,?,?)").run(id,JSON.stringify({author:'123@lid',type:'image',body:id==='story-active'?'Observed caption':'hidden-expired-content',date:storyDate,expires_at:future,source:'live',url:'https://secret.invalid',mediaKey:'secret',...extra}),new Date().toISOString());
  const stories=await call('/api/v1/stories?author=123%40lid&limit=1','GET',null,reader);assert.equal(stories.json.meta.total,1,JSON.stringify(stories.json));assert.equal(stories.json.data[0].body,'Observed caption');assert.equal(stories.json.data[0].media_available,false);assert.equal(JSON.stringify(stories.json).includes('secret.invalid'),false);assert.equal((await call('/api/v1/stories?q=hidden-expired-content','GET',null,reader)).json.meta.total,0);
  assert.equal((await call('/api/v1/stories?id=story-expired','GET',null,reader)).status,404);assert.equal((await call('/api/v1/stories?id=story-revoked','GET',null,reader)).status,404);assert.equal((await call('/api/v1/snapshots?kind=story','GET',null,reader)).status,400);assert.equal((await call('/api/v1/stories','GET',null,hookToken)).status,403);assert.equal((await fetch(base+'/api/v1/stories')).status,401);assert.equal((await call('/api/v1/stories','POST',{body:'not published'})).status,404);
  const unknownIdentity=await call('/api/v1/identities?id=123%40lid','GET',null,reader);assert.equal(unknownIdentity.json.data.status,'unknown');assert.equal(unknownIdentity.json.data.phone_e164,null);assert.equal(unknownIdentity.json.data.pn,null);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('identity','123@lid',?,?)").run(JSON.stringify({lid:'123@lid',pn:'12025555679@s.whatsapp.net',source:'lid-mapping.update',observed_at:new Date().toISOString(),status:'observed',secret:'privatevalue'}),new Date().toISOString());
  const mapping=await call('/api/v1/identities?lid=123%40lid&pn=%2B12025555679&limit=1','GET',null,reader);assert.equal(mapping.json.meta.total,1);assert.equal(mapping.json.data[0].phone_e164,'+12025555679');assert.equal(mapping.json.data[0].source,'lid-mapping.update');assert.equal(mapping.json.data[0].secret,undefined);assert.equal(mapping.json.meta.history_complete,false);
  database.prepare("UPDATE snapshots SET payload=? WHERE kind='identity' AND resource_id='123@lid'").run(JSON.stringify({lid:'123@lid',pn:'12025555679@s.whatsapp.net',source:'contacts',status:'conflict',conflict:true,conflicting_pn:'12025550000@s.whatsapp.net'}));assert.equal((await call('/api/v1/identities?id=123%40lid','GET',null,reader)).json.data.status,'conflict');assert.equal(database.prepare("SELECT phone_e164 FROM contacts WHERE id='lid'").get().phone_e164,null);
  database.prepare("UPDATE snapshots SET payload=? WHERE kind='identity' AND resource_id='123@lid'").run(JSON.stringify({lid:'123@lid',pn:'12025555679@s.whatsapp.net',source:'contacts',candidate_pns:['12025550000@s.whatsapp.net','12025559999@s.whatsapp.net','https://private.invalid','123@lid'],conflict:true}));database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('identity','456@lid',?,?)").run(JSON.stringify({lid:'456@lid',pn:'12025559999@s.whatsapp.net',source:'contacts',status:'observed'}),new Date().toISOString());
  const ambiguous=await call('/api/v1/identities?pn=%2B12025559999','GET',null,reader);assert.equal(ambiguous.json.meta.total,2);assert.ok(ambiguous.json.data.every(row=>row.status==='conflict'));assert.equal(ambiguous.json.data.find(row=>row.id==='123@lid').candidate_pns.length,3);assert.equal(JSON.stringify(ambiguous.json).includes('private.invalid'),false);
  assert.equal((await call('/api/v1/identities?pn=123%40lid','GET',null,reader)).status,400);assert.equal((await call('/api/v1/identities?id=unknown','GET',null,reader)).status,404);assert.equal((await call('/api/v1/identities','GET',null,hookToken)).status,403);assert.equal((await fetch(base+'/api/v1/identities')).status,401);assert.equal((await call('/api/v1/identities','POST',{lid:'123@lid',pn:'fake'})).status,404);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('call',?,?,?)").run('call-observed',JSON.stringify({id:'ignore-payload-id',from:'123@s.whatsapp.net',chatId:'456@g.us',status:'ringing',isVideo:true,date:'2026-01-01T00:00:00Z',secret:'privatevalue',url:'https://private.invalid',history:[{status:'offer',date:'2026-01-01T00:00:00Z',secret:'privatevalue'}]}),new Date().toISOString());
  const callList=await call('/api/v1/calls?q=123&status=ringing&limit=1','GET',null,reader);assert.equal(callList.status,200);assert.equal(callList.json.meta.total,1);assert.equal(callList.json.data[0].id,'call-observed');assert.equal(callList.json.data[0].isVideo,true);assert.equal(JSON.stringify(callList.json).includes('privatevalue'),false);
  const callDetail=await call('/api/v1/calls?id=call-observed','GET',null,reader);assert.equal(callDetail.json.data.from,'123@s.whatsapp.net');assert.equal(callDetail.json.data.chatId,'456@g.us');assert.equal(callDetail.json.data.history[0].status,'offer');assert.equal(callDetail.json.data.history[0].secret,undefined);assert.equal((await call('/api/v1/calls?status=unknown','GET',null,reader)).status,400);assert.equal((await call('/api/v1/calls?id=missing','GET',null,reader)).status,404);assert.equal((await call('/api/v1/calls','GET',null,hookToken)).status,403);assert.equal((await fetch(base+'/api/v1/calls')).status,401);assert.equal((await call('/api/v1/calls','POST',{target:'123@s.whatsapp.net'})).status,404);
 }finally{if(original===undefined)delete process.env.WIS_OUTBOUND_ENABLED;else process.env.WIS_OUTBOUND_ENABLED=original;await new Promise(r=>server.close(r));database.close();await rm(temp,{recursive:true,force:true});}
});
test('known-chat disappearing mode read is scoped, deduplicated and visible as a local-only snapshot',async()=>{
 const database=openDatabase(':memory:'),salt='mode-api-test',password=randomBytes(20).toString('hex');database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 const temp=await mkdtemp(resolve(tmpdir(),'wis-disappearing-mode-api-')),server=makeServer(database,{stateDir:temp});await new Promise(resolveServer=>server.listen(0,'127.0.0.1',resolveServer));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 const call=async(path,method='GET',body,token)=>{const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),Origin:base,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 try{
  database.prepare("INSERT INTO conversations(id,wa_chat_id) VALUES('known-chat','123@s.whatsapp.net')").run();
  const login=await call('/api/login','POST',{password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
  assert.equal((await call('/api/v1/sync','POST',{kind:'disappearing_mode',target:'999@s.whatsapp.net'})).status,404);
  assert.equal((await call('/api/v1/sync','POST',{kind:'disappearing_mode',target:'123@newsletter'})).status,400);
  const queued=await call('/api/v1/sync','POST',{kind:'disappearing_mode',target:'123@s.whatsapp.net'});assert.equal(queued.status,202);
  assert.equal((await call('/api/v1/sync','POST',{kind:'disappearing_mode',target:'123@s.whatsapp.net'})).json.data.id,queued.json.data.id);
  const readToken=(await call('/api/v1/tokens','POST',{name:'mode read only',scopes:['read']})).json.data.token;
  assert.equal((await call('/api/v1/sync','POST',{kind:'disappearing_mode',target:'123@s.whatsapp.net'},readToken)).status,403);
  database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('disappearing_mode',?,?,?)").run('123@s.whatsapp.net',JSON.stringify({available:true,response_verified:true,stale:false,scope:'known_chat',duration_seconds:86400,set_at:'2026-09-27T00:00:00.000Z',observed_at:'2026-09-28T00:00:00.000Z',private:'must_not_escape'}),new Date().toISOString());
  const detail=await call('/api/v1/conversations?id=known-chat');const mode=detail.json.data.snapshots.find(row=>row.kind==='disappearing_mode').data;assert.equal(mode.duration_seconds,86400);assert.equal(mode.set_at,'2026-09-27T00:00:00.000Z');assert.equal(mode.private,undefined);
  const state=await call('/api/v1/disappearing-mode?target=123%40s.whatsapp.net');assert.equal(state.json.data.snapshot.duration_seconds,86400);assert.equal(state.json.data.command.status,'pending');
  assert.equal((await call('/api/v1/disappearing-mode?target=123%40newsletter')).status,400);
 }finally{await new Promise(resolveServer=>server.close(resolveServer));database.close();await rm(temp,{recursive:true,force:true});}
});
test('Easypanel HTTPS proxy requires exact host, origin and forwarded protocol',async()=>{
 const database=openDatabase(':memory:'),salt='easypanel-proxy-test',password=randomBytes(20).toString('hex');database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 const temp=await mkdtemp(resolve(tmpdir(),'wis-easypanel-proxy-')),server=makeServer(database,{stateDir:temp,allowedHosts:['dashboard.example.test'],trustProxy:true});await new Promise(resolveServer=>server.listen(0,'127.0.0.1',resolveServer));const port=server.address().port;
 const request=({host='dashboard.example.test',origin='https://dashboard.example.test',proto='https'}={})=>new Promise((resolveRequest,reject)=>{const req=httpRequest({hostname:'127.0.0.1',port,path:'/api/login',method:'POST',headers:{Host:host,Origin:origin,'X-Forwarded-Proto':proto,'Content-Type':'application/json'}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolveRequest({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks).toString()}));});req.on('error',reject);req.end(JSON.stringify({password}));});
 try{
  const internalHealth=await fetch('http://127.0.0.1:'+port+'/api/local-status');assert.equal(internalHealth.status,200);
  const login=await request();assert.equal(login.status,200,login.body);assert.match(login.headers['set-cookie'][0],/; Secure(?:;|$)/);
  assert.equal((await request({host:'other.example.test'})).status,403);assert.equal((await request({origin:'https://attacker.example.test'})).status,403);assert.equal((await request({proto:'https,http'})).status,403);assert.equal((await request({proto:'http'})).status,403);
 }finally{await new Promise(r=>server.close(r));database.close();await rm(temp,{recursive:true,force:true});}
});

test('reopening additive schema preserves existing contact and session state',async()=>{const temp=await mkdtemp(resolve(tmpdir(),'wis-migration-test-'));try{const file=resolve(temp,'test.sqlite');let database=openDatabase(file);database.prepare("INSERT INTO contacts(id,phone_e164,display_name,created_at) VALUES('keep','+12025550111','Existing data',?)").run(new Date().toISOString());database.prepare("INSERT INTO sessions(token_hash,expires_at) VALUES('session','2099-01-01T00:00:00Z')").run();database.close();database=openDatabase(file);assert.equal(database.prepare("SELECT display_name FROM contacts WHERE id='keep'").get().display_name,'Existing data');assert.equal(database.prepare('SELECT count(*) AS n FROM sessions').get().n,1);assert.equal(database.prepare('SELECT count(*) AS n FROM snapshots').get().n,0);database.close();}finally{await rm(temp,{recursive:true,force:true});}});

test('group invite metadata lookup is administrator-only, transient and rate-limited',async()=>{
 const database=openDatabase(':memory:'),salt='invite-test-salt',password=randomBytes(20).toString('hex'),code='OpaqueInviteCode';
 database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 const temp=await mkdtemp(resolve(tmpdir(),'wis-group-invite-api-'));let calls=0;
 const server=makeServer(database,{stateDir:temp,lookupGroupInviteInfo:{lookup:async value=>{calls++;assert.equal(value,code);return {data:{id:'12345@g.us',name:'Equipo'},meta:{response_verified:true}};},close(){}}});
 await new Promise(resolveServer=>server.listen(0,'127.0.0.1',resolveServer));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 const call=async(path,method='GET',body,token)=>{const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),Origin:base,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 try{
  assert.equal((await call('/api/v1/group-invite-info','POST',{invite_code:code})).status,401);
  const login=await call('/api/login','POST',{password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
  const reader=(await call('/api/v1/tokens','POST',{name:'invite reader',scopes:['read']})).json.data.token;
  assert.equal((await call('/api/v1/group-invite-info','POST',{invite_code:code},reader)).status,403);
  assert.equal((await call('/api/v1/group-invite-info','POST',{invite_code:'https://chat.whatsapp.com/'+code})).status,400);
  const lookup=await call('/api/v1/group-invite-info','POST',{invite_code:code});assert.equal(lookup.status,200);assert.equal(lookup.json.data.name,'Equipo');assert.equal(calls,1);
  assert.equal((await call('/api/v1/group-invite-info','POST',{invite_code:code})).status,429);assert.equal(calls,1);
  assert.equal(database.prepare('SELECT count(*) AS n FROM read_commands WHERE target=?').get(code).n,0);
  assert.equal(database.prepare('SELECT count(*) AS n FROM snapshots WHERE payload LIKE ?').get('%'+code+'%').n,0);
  assert.equal(database.prepare('SELECT count(*) AS n FROM audit WHERE resource_id=? OR action LIKE ?').get(code,'%'+code+'%').n,0);
 }finally{await new Promise(resolveServer=>server.close(resolveServer));database.close();await rm(temp,{recursive:true,force:true});}
});

test('community invite read is administrator-only and limited to known communities',async()=>{
 const database=openDatabase(':memory:'),salt='community-invite-test-salt',password=randomBytes(20).toString('hex'),target='12345-67890@g.us';
 database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 database.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('community',target,JSON.stringify({id:target,isCommunity:true}),'2026-01-01T00:00:00.000Z');
 const temp=await mkdtemp(resolve(tmpdir(),'wis-community-invite-api-')),server=makeServer(database,{stateDir:temp});
 await new Promise(resolveServer=>server.listen(0,'127.0.0.1',resolveServer));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 const call=async(path,method='GET',body,token)=>{const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),Origin:base,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 try{
  assert.equal((await call('/api/v1/sync','POST',{kind:'community_invite',target})).status,401);
  assert.equal((await call('/api/v1/community-invite?target='+encodeURIComponent(target))).status,401);
  const login=await call('/api/login','POST',{password});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
  const tokenResponse=await call('/api/v1/tokens','POST',{name:'read-only',scopes:['read']});assert.equal(tokenResponse.status,201);const readToken=tokenResponse.json.data.token;
  assert.equal((await call('/api/v1/sync','POST',{kind:'community_invite',target},readToken)).status,403);assert.equal((await call('/api/v1/community-invite?target='+encodeURIComponent(target),'GET',undefined,readToken)).status,403);
  assert.equal((await call('/api/v1/sync','POST',{kind:'community_invite',target:'99999@g.us'})).status,404);
  const queued=await call('/api/v1/sync','POST',{kind:'community_invite',target});assert.equal(queued.status,202);assert.equal(database.prepare("SELECT kind FROM read_commands WHERE target=? AND kind='community_invite'").get(target).kind,'community_invite');
  const invite=await call('/api/v1/community-invite?target='+encodeURIComponent(target));assert.equal(invite.status,200);assert.equal(invite.json.data.observed,false);assert.equal(invite.json.data.code,null);
  assert.equal((await call('/api/v1/community-invite?target='+encodeURIComponent('99999@g.us'))).status,404);
  const now=new Date().toISOString(),code='CommunityInviteTemporaryCode';database.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('community_invite',target,JSON.stringify({code,available:true,response_verified:true,last_success_at:now,expires_at:new Date(Date.now()+30000).toISOString()}),now);
  const available=await call('/api/v1/community-invite?target='+encodeURIComponent(target));assert.equal(available.json.data.code,code);assert.equal(available.headers.get('cache-control'),'no-store');
  database.prepare("UPDATE snapshots SET payload=json_set(payload,'$.expires_at',?) WHERE kind='community_invite' AND resource_id=?").run(new Date(Date.now()-1000).toISOString(),target);
  const expired=await call('/api/v1/community-invite?target='+encodeURIComponent(target));assert.equal(expired.status,200,JSON.stringify(expired.json));assert.equal(expired.json.data.code,null);assert.equal(expired.json.data.available,false);assert.equal(expired.json.data.expired,true);
 }finally{await new Promise(resolveClose=>server.close(resolveClose));database.close();await rm(temp,{recursive:true,force:true});}
});
test('newsletter invite metadata lookup is administrator-only, partial and never persisted',async()=>{
 const database=openDatabase(':memory:'),salt='newsletter-invite-salt',password=randomBytes(20).toString('hex'),code='ChannelInvite_123';database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
 const temp=await mkdtemp(resolve(tmpdir(),'wis-newsletter-invite-api-'));let calls=0;
 const server=makeServer(database,{stateDir:temp,lookupNewsletterInviteInfo:{lookup:async value=>{calls++;assert.equal(value,code);return {data:{id:'12345@newsletter',type:'newsletter',name:'Canal',subscribers_count:42},meta:{response_verified:true,partial:true}};},close(){}}});await new Promise(resolveServer=>server.listen(0,'127.0.0.1',resolveServer));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 const call=async(path,method='GET',body,token)=>{const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),Origin:base,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 try{assert.equal((await call('/api/v1/newsletter-invite-info','POST',{invite_code:code})).status,401);const login=await call('/api/login','POST',{password});cookie=login.headers.get('set-cookie').split(';')[0];const reader=(await call('/api/v1/tokens','POST',{name:'newsletter reader',scopes:['read']})).json.data.token;assert.equal((await call('/api/v1/newsletter-invite-info','POST',{invite_code:code},reader)).status,403);assert.equal((await call('/api/v1/newsletter-invite-info','POST',{invite_code:'https://whatsapp.com/channel/'+code})).status,400);const result=await call('/api/v1/newsletter-invite-info','POST',{invite_code:code});assert.equal(result.status,200);assert.equal(result.json.data.name,'Canal');assert.equal(result.json.meta.partial,true);assert.equal(calls,1);assert.equal((await call('/api/v1/newsletter-invite-info','POST',{invite_code:code})).status,429);assert.equal(database.prepare('SELECT count(*) AS n FROM read_commands WHERE target=?').get(code).n,0);assert.equal(database.prepare('SELECT count(*) AS n FROM snapshots WHERE payload LIKE ?').get('%'+code+'%').n,0);assert.equal(database.prepare('SELECT count(*) AS n FROM audit WHERE resource_id=? OR action LIKE ?').get(code,'%'+code+'%').n,0);}
 finally{await new Promise(resolveServer=>server.close(resolveServer));database.close();await rm(temp,{recursive:true,force:true});}
});
