import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, scryptSync } from 'node:crypto';
process.env.WIS_DB_PATH = ':memory:';
const { openDatabase } = await import('./db.mjs');
const { makeServer } = await import('./server.mjs');

test('capability field search requires authentication and returns bounded metadata', async () => {
  const database = openDatabase(':memory:');
  const salt = randomBytes(16).toString('hex');
  const password = randomBytes(24).toString('hex');
  database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(`${salt}:${scryptSync(password, salt, 64).toString('hex')}`);
  const server = makeServer(database);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  try {
    assert.equal((await fetch(`${base}/api/v1/capability-fields?q=participants`)).status, 401);
    assert.equal((await fetch(`${base}/api/v1/capability-field-coverage`)).status, 401);
    const login = await fetch(`${base}/api/login`, { method: 'POST', headers: { Origin: base, 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) });
    assert.equal(login.status, 200);
    const cookie = login.headers.get('set-cookie').split(';')[0];
    assert.equal((await fetch(`${base}/api/v1/capability-fields?q=x`, { headers: { Cookie: cookie } })).status, 400);
    const response = await fetch(`${base}/api/v1/capability-fields?q=participants&limit=3`, { headers: { Cookie: cookie } });
    assert.equal(response.status, 200);
    const body = await response.json();
    assert.ok(body.data.total >= body.data.results.length);
    assert.ok(body.data.results.length <= 3);
    assert.ok(body.data.results.every(row => row.field_path && ['parameter', 'request', 'response'].includes(row.direction)));
    assert.equal(JSON.stringify(body).includes('example'), false);
    const firstPage = await fetch(`${base}/api/v1/capability-fields?limit=2`, { headers: { Cookie: cookie } });
    assert.equal(firstPage.status, 200);
    const firstPageBody = await firstPage.json();
    assert.equal(firstPageBody.data.offset, 0);
    assert.equal(firstPageBody.data.results.length, 2);
    assert.ok(firstPageBody.data.total > 2);
    const secondPage = await fetch(`${base}/api/v1/capability-fields?limit=2&offset=2`, { headers: { Cookie: cookie } });
    const secondPageBody = await secondPage.json();
    assert.equal(secondPageBody.data.offset, 2);
    assert.notEqual(secondPageBody.data.results[0].field_path, firstPageBody.data.results[0].field_path);
    assert.equal((await fetch(`${base}/api/v1/capability-fields?offset=-1`, { headers: { Cookie: cookie } })).status, 400);
    const fractional = await fetch(`${base}/api/v1/capability-fields?q=participants&limit=2.5`, { headers: { Cookie: cookie } });
    assert.ok((await fractional.json()).data.results.length <= 2);
    const filtered = await fetch(`${base}/api/v1/capability-fields?capability_id=getmessages&direction=response&limit=5`, { headers: { Cookie: cookie } });
    assert.equal(filtered.status, 200);
    const filteredBody = await filtered.json();
    assert.equal(filteredBody.data.capability_id, 'getmessages');
    assert.equal(filteredBody.data.direction, 'response');
    assert.ok(filteredBody.data.results.length > 0);
    assert.ok(filteredBody.data.results.every(row => row.capability_id === 'getmessages' && row.direction === 'response'));
    assert.equal((await fetch(`${base}/api/v1/capability-fields?direction=send`, { headers: { Cookie: cookie } })).status, 400);
    assert.equal((await fetch(`${base}/api/v1/capability-fields?capability_id=../private`, { headers: { Cookie: cookie } })).status, 400);
    database.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('audit_probe','aggregate','{}','2026-10-01T12:00:00.000Z')").run();
    const coverage = await fetch(`${base}/api/v1/capability-field-coverage`, { headers: { Cookie: cookie } });
    assert.equal(coverage.status, 200);
    const coverageBody = await coverage.json();
    assert.equal(coverageBody.data.method_count, 182);
    assert.equal(coverageBody.data.source_database, 'service_sqlite');
    assert.equal(coverageBody.data.latest_snapshot_updated_at, '2026-10-01T12:00:00.000Z');
    assert.ok(coverageBody.data.totals.response_fields > 0);
    assert.ok(Number.isInteger(coverageBody.data.totals.fresh_response_fields_observed));
    assert.ok(Number.isInteger(coverageBody.data.totals.stale_only_response_fields));
    assert.ok(coverageBody.data.methods.every(row => Number.isInteger(row.response_fields_without_observation)));
    assert.equal(JSON.stringify(coverageBody).includes('should-not-leak'), false);
  } finally {
    await new Promise(resolve => server.close(resolve));
    database.close();
  }
});
