import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {buildDataCoverage} from './data-coverage.mjs';

test('coverage reports counts and observed field names without field values or secrets',()=>{
 const db=new DatabaseSync(':memory:');
 db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO contacts VALUES(?,?)').run('c1','549111@s.whatsapp.net');db.prepare('INSERT INTO conversations VALUES(?,?)').run('v1','549111@s.whatsapp.net');db.prepare('INSERT INTO messages VALUES(?,?,?)').run('m1','wamid-1','text');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('chat','549111@s.whatsapp.net',JSON.stringify({id:'private-jid',pinned:false,secret:'hidden',accessToken:'hidden',profile:{about:'private-about',details:{verified:false,token:'private-token'}},participants:[{jid:'private-participant',role:'admin'},{jid:'private-participant-2',role:'user'}],'item[0]':{value:'zero'},'item[1]':{value:'one'}}),'2026-01-01T00:00:00.000Z');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('chat','549112@s.whatsapp.net',JSON.stringify({id:'other-private-jid',unreadCount:0,[`${'x'.repeat(100)}a`]:1,[`${'x'.repeat(100)}b`]:1}),'2026-01-02T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db);assert.deepEqual(coverage.entities.contacts,{known:1,with_whatsapp_id:1,metadata_records:0});assert.deepEqual(coverage.entities.conversations,{known:1,chat_metadata_records:2});assert.deepEqual(coverage.entities.messages,{stored:1,with_whatsapp_id:1,metadata_records:0});assert.deepEqual(coverage.message_types,[{type:'text',count:1}]);assert.ok(coverage.snapshot_kinds[0].fields.includes('$.id'));assert.deepEqual(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.id'),{field:'$.id',records:2,snapshot_updated_at:'2026-01-02T00:00:00.000Z'});assert.equal(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.profile.details.verified').records,1);assert.equal(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.participants[].jid').records,1);assert.ok(coverage.snapshot_kinds[0].fields.includes('$."item[0]".value'));assert.ok(coverage.snapshot_kinds[0].fields.includes('$."item[1]".value'));assert.equal(coverage.snapshot_kinds[0].fields.some(x=>/\[\d+\]/.test(x)&&!x.includes('"')),false);assert.equal(coverage.snapshot_kinds[0].omitted_fields,2);assert.equal(coverage.snapshot_kinds[0].field_inventory_truncated,false);assert.equal(JSON.stringify(coverage).includes('private-jid'),false);assert.equal(JSON.stringify(coverage).includes('private-about'),false);assert.equal(JSON.stringify(coverage).includes('private-participant'),false);assert.equal(JSON.stringify(coverage).includes('hidden'),false);assert.equal(JSON.stringify(coverage).includes('private-token'),false);assert.equal(JSON.stringify(coverage).includes('x'.repeat(100)),false);assert.equal(coverage.history_complete,false);}finally{db.close();}
});

test('coverage bounds pathological field inventories and reports truncation',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);');
 const payload=JSON.stringify(Object.fromEntries(Array.from({length:10001},(_,i)=>[`field_${String(i).padStart(5,'0')}`,i])));
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('large','row-1',payload,'2026-01-01T00:00:00.000Z');
 try{const row=buildDataCoverage(db).snapshot_kinds[0];assert.equal(row.records,1);assert.equal(row.fields.length,100);assert.equal(row.field_counts.length,100);assert.equal(row.omitted_fields,9900);assert.equal(row.field_inventory_truncated,true);}finally{db.close();}
});
