import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {buildDataCoverage} from './data-coverage.mjs';

test('coverage keeps explicit successful observation time separate from snapshot write time',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('account','self',JSON.stringify({status:'connected',last_success_at:'2026-01-01T00:00:00.000Z'}),'2026-01-02T00:00:00.000Z');db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('profile','unmarked',JSON.stringify({status:'unknown'}),'2026-01-02T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),fields=coverage.snapshot_kinds.find(row=>row.kind==='account').field_counts,status=fields.find(row=>row.field==='$.status'),unmarked=coverage.snapshot_kinds.find(row=>row.kind==='profile').field_counts.find(row=>row.field==='$.status');assert.equal(status.snapshot_updated_at,'2026-01-02T00:00:00.000Z');assert.equal(status.snapshot_last_success_at,'2026-01-01T00:00:00.000Z');assert.equal(unmarked.snapshot_last_success_at??null,null);}finally{db.close();}
});

test('expired group and community invite codes do not count as current field evidence',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)');insert.run('group_invite','old-group',JSON.stringify({code:'expired-placeholder',expires_at:'2026-01-01T00:00:00.000Z'}),'2025-12-31T23:59:00.000Z');insert.run('group_invite','current-group',JSON.stringify({code:'current-placeholder',expires_at:'2026-01-01T00:00:30.000Z'}),'2026-01-01T00:00:00.000Z');insert.run('community_invite','old-community',JSON.stringify({code:'expired-community-placeholder',expires_at:'2026-01-01T00:00:00.000Z'}),'2025-12-31T23:59:00.000Z');insert.run('community_invite','current-community',JSON.stringify({code:'current-community-placeholder',expires_at:'2026-01-01T00:00:30.000Z'}),'2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db,Date.parse('2026-01-01T00:00:10.000Z')),group=coverage.snapshot_kinds.find(item=>item.kind==='group_invite'),community=coverage.snapshot_kinds.find(item=>item.kind==='community_invite');for(const row of [group,community]){const code=row.field_counts.find(item=>item.field==='$.code');assert.equal(code.records,1);assert.equal(code.non_empty_text_records,1);assert.equal(JSON.stringify(row).includes('placeholder'),false);}}finally{db.close();}
});

test('coverage reports counts and observed field names without field values or secrets',()=>{
 const db=new DatabaseSync(':memory:');
 db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO contacts VALUES(?,?)').run('c1','549111@s.whatsapp.net');db.prepare('INSERT INTO conversations VALUES(?,?)').run('v1','549111@s.whatsapp.net');db.prepare('INSERT INTO messages(id,wa_message_id,type) VALUES(?,?,?)').run('m1','wamid-1','text');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('chat','549111@s.whatsapp.net',JSON.stringify({id:'private-jid',pinned:false,secret:'hidden',accessToken:'hidden',profile:{about:'private-about',details:{verified:false,token:'private-token'}},participants:[{jid:'private-participant',role:'admin'},{jid:'private-participant-2',role:'user'}],'item[0]':{value:'zero'},'item[1]':{value:'one'}}),'2026-01-01T00:00:00.000Z');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('chat','549112@s.whatsapp.net',JSON.stringify({id:'other-private-jid',unreadCount:0,[`${'x'.repeat(100)}a`]:1,[`${'x'.repeat(100)}b`]:1}),'2026-01-02T00:00:00.000Z');
 db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('cmd-private-1','account','done','sensitive-target-1','sensitive-error', '2026-01-03T00:00:00.000Z');db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('cmd-private-2','account','failed','sensitive-target-2','sensitive-error', '2026-01-04T00:00:00.000Z');db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('cmd-private-3','blocklist','running','sensitive-target-3',null,'2026-01-05T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db);assert.deepEqual(coverage.entities.contacts,{known:1,with_whatsapp_id:1,metadata_records:0});assert.deepEqual(coverage.entities.conversations,{known:1,chat_metadata_records:2});assert.deepEqual(coverage.entities.messages,{stored:1,with_whatsapp_id:1,metadata_records:0});assert.deepEqual(coverage.message_types,[{type:'text',count:1}]);assert.deepEqual(coverage.read_commands,[{kind:'account',status:'done',count:1,last_updated_at:'2026-01-03T00:00:00.000Z'},{kind:'account',status:'failed',count:1,last_updated_at:'2026-01-04T00:00:00.000Z'},{kind:'blocklist',status:'running',count:1,last_updated_at:'2026-01-05T00:00:00.000Z'}]);assert.ok(coverage.snapshot_kinds[0].fields.includes('$.id'));assert.deepEqual(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.id'),{field:'$.id',records:2,non_empty_text_records:2,snapshot_updated_at:'2026-01-02T00:00:00.000Z'});assert.equal(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.profile.details.verified').records,1);assert.equal(coverage.snapshot_kinds[0].field_counts.find(x=>x.field==='$.participants[].jid').records,1);assert.ok(coverage.snapshot_kinds[0].fields.includes('$."item[0]".value'));assert.ok(coverage.snapshot_kinds[0].fields.includes('$."item[1]".value'));assert.equal(coverage.snapshot_kinds[0].fields.some(x=>/\[\d+\]/.test(x)&&!x.includes('"')),false);assert.equal(coverage.snapshot_kinds[0].omitted_fields,2);assert.equal(coverage.snapshot_kinds[0].field_inventory_truncated,false);assert.equal(JSON.stringify(coverage).includes('sensitive-target'),false);assert.equal(JSON.stringify(coverage).includes('sensitive-error'),false);assert.equal(JSON.stringify(coverage).includes('private-jid'),false);assert.equal(JSON.stringify(coverage).includes('private-about'),false);assert.equal(JSON.stringify(coverage).includes('private-participant'),false);assert.equal(JSON.stringify(coverage).includes('hidden'),false);assert.equal(JSON.stringify(coverage).includes('private-token'),false);assert.equal(JSON.stringify(coverage).includes('x'.repeat(100)),false);assert.equal(coverage.history_complete,false);}finally{db.close();}
});

test('coverage counts non-empty text per field without revealing the text',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('contact','private-1',JSON.stringify({status:{status:'private about text'}}),'2026-01-01T00:00:00.000Z');db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('contact','private-2',JSON.stringify({status:{status:''}}),'2026-01-02T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),field=coverage.snapshot_kinds.find(row=>row.kind==='contact').field_counts.find(row=>row.field==='$.status.status');assert.deepEqual(field,{field:'$.status.status',records:2,non_empty_text_records:1,snapshot_updated_at:'2026-01-02T00:00:00.000Z'});assert.equal(JSON.stringify(coverage).includes('private about text'),false);}finally{db.close();}
});

test('coverage derives chat type from recognized JID namespaces without exposing identities or claiming snapshot freshness',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)');
 for(const jid of ['private-group@g.us','private-person@s.whatsapp.net','private-lid@lid','private-channel@newsletter','unknown@unrecognized'])insert.run('chat',jid,'{}','2026-01-02T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),kind=coverage.snapshot_kinds.find(row=>row.kind==='chat'),field=kind.field_counts.find(row=>row.field==='$.whapi_derived.chat_type_from_jid');assert.deepEqual(field,{field:'$.whapi_derived.chat_type_from_jid',records:4,non_empty_text_records:4,snapshot_updated_at:null});for(const secret of ['private-group','private-person','private-lid','private-channel','unrecognized'])assert.equal(JSON.stringify(coverage).includes(secret),false);}finally{db.close();}
});

test('coverage counts only active chat label associations and never exposes identifiers',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)');insert.run('label_association','private-chat:private-label:',JSON.stringify({type:'label_jid',chatId:'private-chat',labelId:'private-label',associated:true}),'2026-01-01T00:00:00.000Z');insert.run('label_association','private-chat:private-message:private-label',JSON.stringify({type:'label_message',chatId:'private-chat',messageId:'private-message',labelId:'private-label',associated:true}),'2026-01-02T00:00:00.000Z');insert.run('label_association','private-chat-removed:private-label:',JSON.stringify({type:'label_jid',chatId:'private-chat-removed',labelId:'private-label',associated:false}),'2026-01-03T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),kind=coverage.contextual_kinds.find(row=>row.kind==='label_chat_association');assert.deepEqual(kind,{kind:'label_chat_association',records:1,field_counts:[{field:'chatId',records:1,snapshot_updated_at:'2026-01-01T00:00:00.000Z'},{field:'labelId',records:1,snapshot_updated_at:'2026-01-01T00:00:00.000Z'}]});for(const value of ['private-chat','private-label','private-message'])assert.equal(JSON.stringify(coverage).includes(value),false);}finally{db.close();}
});

test('coverage normalizes WhatsApp identities used as dynamic presence map keys',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('presence','private-resource',JSON.stringify({presences:{'5491112345679@s.whatsapp.net':{lastKnownPresence:'available'},'private-lid@lid':{lastKnownPresence:'composing'}}}),'2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),fields=coverage.snapshot_kinds.find(row=>row.kind==='presence').fields;assert.ok(fields.includes('$.presences.*.lastKnownPresence'));assert.equal(fields.some(field=>field.includes('5491112345679')||field.includes('private-lid')),false);assert.equal(JSON.stringify(coverage).includes('5491112345679'),false);assert.equal(JSON.stringify(coverage).includes('private-lid'),false);}finally{db.close();}
});

test('coverage includes only verified WHAPI quota projection fields without revealing values',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('account_limits','private-account',JSON.stringify({quota:{available:true,response_verified:true,total_quota:120,used_quota:35,capping_status:'FIRST_WARNING',ote_status:'ELIGIBLE',mv_status:'ACTIVE',cycle_start_timestamp:'1700000000',cycle_end_timestamp:'1700600000'},timelock:{available:false}}),'2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),kind=coverage.snapshot_kinds.find(row=>row.kind==='account_limits');for(const field of ['cap_type','quota_limit','quota_used','cycle_start_at','cycle_end_at'])assert.ok(kind.fields.includes(`$.whapi_projection.getnewchatlimit.fields.${field}`));for(const field of ['is_capped','cap_status','quota_remaining'])assert.equal(kind.fields.includes(`$.whapi_projection.getnewchatlimit.fields.${field}`),false);assert.equal(kind.fields.includes('$.whapi_projection.getreachouttimelock.fields.is_restricted'),false);for(const value of ['private-account','individual_new_chat_thread'])assert.equal(JSON.stringify(coverage).includes(value),false,`coverage leaked ${value}`);}finally{db.close();}
});

test('coverage counts scalar array items by normalized path without revealing values',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('business','private-resource',JSON.stringify({website:['https://private.example.test','']}),'2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),field=coverage.snapshot_kinds.find(row=>row.kind==='business').field_counts.find(x=>x.field==='$.website[]');assert.deepEqual(field,{field:'$.website[]',records:1,non_empty_text_records:1,snapshot_updated_at:'2026-01-01T00:00:00.000Z'});assert.equal(JSON.stringify(coverage).includes('private.example.test'),false);}finally{db.close();}
});

test('coverage bounds pathological field inventories and reports truncation',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const payload=JSON.stringify(Object.fromEntries(Array.from({length:10001},(_,i)=>[`field_${String(i).padStart(5,'0')}`,i])));
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('large','row-1',payload,'2026-01-01T00:00:00.000Z');
 try{const row=buildDataCoverage(db).snapshot_kinds[0];assert.equal(row.records,1);assert.equal(row.fields.length,100);assert.equal(row.field_counts.length,100);assert.equal(row.omitted_fields,9900);assert.equal(row.field_inventory_truncated,true);}finally{db.close();}
});

test('coverage counts identity observations without exposing identifiers',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('identity','private-lid',JSON.stringify({lid:'private-lid',pn:'private-pn@s.whatsapp.net',status:'observed'}),'2026-01-01T00:00:00.000Z');
 db.prepare('INSERT INTO snapshots VALUES(?,?,?,?)').run('identity','malformed','not-json','2026-01-02T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db);assert.deepEqual(coverage.entities.identity_observations,{known:2,with_whatsapp_id:1,metadata_records:2});assert.equal(JSON.stringify(coverage.entities).includes('private'),false);}finally{db.close();}
});

test('coverage reports only allowlisted read error codes and hides command targets',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('private-id-1','catalog','failed','private-target-1','provider_error','2026-01-01T00:00:00.000Z');
 db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('private-id-2','contact_profile','failed','private-target-2','raw-secret-detail','2026-01-02T00:00:00.000Z');
 db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)').run('private-id-3','contact_profile','failed','private-target-3','another-secret-detail','2026-01-03T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db);assert.deepEqual(coverage.read_errors,[{kind:'catalog',code:'provider_error',count:1,last_updated_at:'2026-01-01T00:00:00.000Z',latest_status:'failed',latest_status_at:'2026-01-01T00:00:00.000Z'},{kind:'contact_profile',code:'read_failed',count:2,last_updated_at:'2026-01-03T00:00:00.000Z',latest_status:'failed',latest_status_at:'2026-01-03T00:00:00.000Z'}]);assert.equal(coverage.read_errors_truncated,false);assert.equal(JSON.stringify(coverage.read_errors).includes('private-target'),false);assert.equal(JSON.stringify(coverage.read_errors).includes('secret-detail'),false);assert.equal(JSON.stringify(coverage.read_errors).includes('private-id'),false);}finally{db.close();}
});

test('coverage reports latest command by read kind without claiming resource recovery',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,created_at TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?,?)');insert.run('private-fail','catalog','failed','private-target','provider_error','2026-01-01T00:00:00.000Z','2026-01-01T00:00:00.000Z');insert.run('private-success','catalog','done','private-target','provider_error','2026-01-02T00:00:00.000Z','2026-01-02T00:00:00.000Z');insert.run('private-current-fail','group_requests','failed','private-target-2','provider_error','2026-01-03T00:00:00.000Z','2026-01-03T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),catalog=coverage.read_errors.find(row=>row.kind==='catalog'),group=coverage.read_errors.find(row=>row.kind==='group_requests');assert.equal(catalog.latest_status,'done');assert.equal(catalog.latest_status_at,'2026-01-02T00:00:00.000Z');assert.equal(group.latest_status,'failed');assert.equal(Object.hasOwn(catalog,'recovered_after_error'),false);assert.equal(JSON.stringify(coverage.read_errors).includes('private-target'),false);assert.equal(JSON.stringify(coverage.read_errors).includes('private-fail'),false);}finally{db.close();}
});

test('coverage flags read error groups beyond the display limit',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO read_commands VALUES(?,?,?,?,?,?)');for(let i=0;i<101;i++)insert.run(`id-${i}`,`kind-${i}`,'failed',`private-target-${i}`,'provider_error','2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db);assert.equal(coverage.read_errors.length,100);assert.equal(coverage.read_errors_truncated,true);assert.ok(coverage.read_errors.every(row=>row.code==='provider_error'));}finally{db.close();}
});

test('coverage separates live and imported message freshness without exposing arbitrary source labels',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,source TEXT DEFAULT \'import\',direction TEXT DEFAULT \'in\',created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 const insert=db.prepare('INSERT INTO messages(id,wa_message_id,type,source,direction,created_at) VALUES(?,?,?,?,?,?)');insert.run('m1','wa-1','text','import','in','2026-01-01T00:00:00.000Z');insert.run('m2','wa-2','image','live','in','2026-01-06T00:00:00.000Z');insert.run('m3','wa-3','text','live','out','2026-01-07T00:00:00.000Z');insert.run('m4','wa-4','text','private-source','out','invalid-date');
 try{const coverage=buildDataCoverage(db);assert.deepEqual(coverage.message_sources,[{source:'live_inbound',count:1,latest_at:'2026-01-06T00:00:00.000Z'},{source:'live_outbound',count:1,latest_at:'2026-01-07T00:00:00.000Z'},{source:'import_inbound',count:1,latest_at:'2026-01-01T00:00:00.000Z'},{source:'other',count:1,latest_at:null}]);assert.equal(coverage.live_inbound_count,1);assert.equal(coverage.last_live_message_at,'2026-01-06T00:00:00.000Z');assert.equal(JSON.stringify(coverage).includes('private-source'),false);}finally{db.close();}
});

test('coverage includes normalized storage field counts without returning row values',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT,title TEXT);CREATE TABLE messages(id TEXT,wa_message_id TEXT,type TEXT,body TEXT,media_path TEXT,source TEXT,direction TEXT,delivery_status TEXT,created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO contacts VALUES(?,?)').run('private-contact-id','private-jid');db.prepare('INSERT INTO conversations VALUES(?,?,?)').run('private-conversation-id','private-chat-id','private-title');db.prepare('INSERT INTO messages(id,wa_message_id,type,body,source,direction,delivery_status,created_at) VALUES(?,?,?,?,?,?,?,?)').run('private-message-id','private-wa-id','text','private-body','live','in','delivered','2026-01-01T00:00:00.000Z');
 try{const coverage=buildDataCoverage(db),messages=coverage.storage_kinds.find(row=>row.kind==='messages');assert.equal(messages.records,1);assert.deepEqual(messages.field_counts.find(row=>row.field==='body'),{field:'body',records:1});assert.deepEqual(messages.field_counts.find(row=>row.field==='delivery_status'),{field:'delivery_status',records:1});assert.deepEqual(messages.field_counts.find(row=>row.field==='media_path'),{field:'media_path',records:0});for(const secret of ['private-contact-id','private-jid','private-conversation-id','private-chat-id','private-title','private-message-id','private-wa-id','private-body'])assert.equal(JSON.stringify(coverage).includes(secret),false);}finally{db.close();}
});

test('last-message evidence is correlated to each conversation and excludes individual messages from groups',()=>{
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE contacts(id TEXT,wa_jid TEXT);CREATE TABLE conversations(id TEXT,wa_chat_id TEXT,title TEXT);CREATE TABLE messages(id TEXT,conversation_id TEXT,wa_message_id TEXT,type TEXT,body TEXT,source TEXT,direction TEXT,delivery_status TEXT,created_at TEXT);CREATE TABLE snapshots(kind TEXT,resource_id TEXT,payload TEXT,updated_at TEXT);CREATE TABLE read_commands(id TEXT,kind TEXT,status TEXT,target TEXT,error TEXT,updated_at TEXT);');
 db.prepare('INSERT INTO conversations VALUES(?,?,?)').run('group-conv','group@g.us','Group');db.prepare('INSERT INTO conversations VALUES(?,?,?)').run('person-conv','person@s.whatsapp.net','Person');
 const insert=db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?)');insert.run('person-message','person-conv','wa-person-message','text','private-individual-body','live','in','delivered','2026-01-02T00:00:00.000Z');
 try{let coverage=buildDataCoverage(db),chat=coverage.contextual_kinds.find(row=>row.kind==='chat_last_message'),group=coverage.contextual_kinds.find(row=>row.kind==='group_last_message');assert.equal(chat.records,2);assert.equal(chat.field_counts.find(row=>row.field==='body').records,1);assert.equal(group.records,1);assert.equal(group.field_counts.find(row=>row.field==='body').records,0);assert.equal(group.field_counts.find(row=>row.field==='wa_message_id').records,0);assert.equal(JSON.stringify(coverage).includes('private-individual-body'),false);insert.run('group-message-old','group-conv','wa-group-message-old','text','private-group-body-old','live','in','delivered','2026-01-03T00:00:00.000Z');insert.run('group-message-new','group-conv','wa-group-message-new','image',null,'live','in','delivered','2026-01-04T00:00:00.000Z');coverage=buildDataCoverage(db);group=coverage.contextual_kinds.find(row=>row.kind==='group_last_message');assert.equal(group.field_counts.find(row=>row.field==='body').records,0);assert.equal(group.field_counts.find(row=>row.field==='wa_message_id').records,1);assert.equal(JSON.stringify(coverage).includes('private-group-body-old'),false);}finally{db.close();}
});
