import {LOCAL_LIMITS} from './limits.mjs';
import {buildDataCoverage} from './data-coverage.mjs';
import {listCapabilityFields,searchCapabilityFields} from './capability-fields.mjs';
import {getScheduledReadSettings,getScheduledReadStatus,queueScheduledReadIfDue,updateScheduledReadSettings} from './scheduled-reads.mjs';
import {createGroupInviteInfoRpc,validGroupInviteCode} from './group-invite-info.mjs';
import {createServer} from 'node:http';
import {randomBytes,randomUUID,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {readFile,writeFile,mkdir,realpath,stat} from 'node:fs/promises';
import {realpathSync,statSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {db,root,stateDir,transaction} from './db.mjs';
const now=()=>new Date().toISOString();
function accountLimits(row){
 let raw={};try{raw=JSON.parse(row?.payload??'{}')??{};}catch{}
 const timestamp=x=>typeof x==='string'&&/^\d{1,16}$/.test(x)?x:null;
 const integer=x=>Number.isSafeInteger(x)&&x>=0?x:null;
 const choice=(x,values)=>values.includes(x)?x:null;
 const section=x=>({available:x?.available===true,response_verified:x?.response_verified===true,error:choice(x?.error,['read_timeout','read_pending','invalid_response','provider_error','access_denied','disconnected','method_missing'])??(x?.error?'read_unavailable':null),status_code:Number.isInteger(x?.status_code)&&x.status_code>=100&&x.status_code<=599?x.status_code:null});
 const q=raw.quota??{},t=raw.timelock??{};
 const quota={...section(q),total_quota:integer(q.total_quota),used_quota:integer(q.used_quota),cycle_start_timestamp:timestamp(q.cycle_start_timestamp),cycle_end_timestamp:timestamp(q.cycle_end_timestamp),server_sent_timestamp:timestamp(q.server_sent_timestamp),ote_status:choice(q.ote_status,['NOT_ELIGIBLE','ELIGIBLE','ACTIVE_IN_CURRENT_CYCLE','EXHAUSTED']),mv_status:choice(q.mv_status,['NOT_ELIGIBLE','NOT_ACTIVE','ACTIVE','ACTIVE_UPGRADE_AVAILABLE']),capping_status:choice(q.capping_status,['NONE','FIRST_WARNING','SECOND_WARNING','CAPPED'])};
 const timelock={...section(t),is_active:typeof t.is_active==='boolean'?t.is_active:null,time_enforcement_ends:timestamp(t.time_enforcement_ends),enforcement_type:choice(t.enforcement_type,["BIZ_COMMERCE_VIOLATION_ALCOHOL","BIZ_COMMERCE_VIOLATION_ADULT","BIZ_COMMERCE_VIOLATION_ANIMALS","BIZ_COMMERCE_VIOLATION_BODY_PARTS_FLUIDS","BIZ_COMMERCE_VIOLATION_DATING","BIZ_COMMERCE_VIOLATION_DIGITAL_SERVICES_PRODUCTS","BIZ_COMMERCE_VIOLATION_DRUGS","BIZ_COMMERCE_VIOLATION_DRUGS_ONLY_OTC","BIZ_COMMERCE_VIOLATION_GAMBLING","BIZ_COMMERCE_VIOLATION_HEALTHCARE","BIZ_COMMERCE_VIOLATION_REAL_FAKE_CURRENCY","BIZ_COMMERCE_VIOLATION_SUPPLEMENTS","BIZ_COMMERCE_VIOLATION_TOBACCO","BIZ_COMMERCE_VIOLATION_VIOLENT_CONTENT","BIZ_COMMERCE_VIOLATION_WEAPONS","BIZ_QUALITY","DEFAULT","WEB_COMPANION_ONLY"])};
 return {observed:Boolean(row),updated_at:row?.updated_at??null,observed_at:typeof raw.observed_at==='string'&&Number.isFinite(Date.parse(raw.observed_at))?new Date(raw.observed_at).toISOString():null,partial:raw.partial!==false||!quota.available||!timelock.available,quota,timelock};
}
const hash=x=>createHash('sha256').update(x).digest('hex');
const fail=(status,message)=>{throw Object.assign(Error(message),{status});};
const scopes=['read','send','contacts:write','webhooks:write'];
const eligible=c=>Boolean(c?.consent_at&&c.consent_source?.trim()&&c.consent_scope?.trim()&&!c.opted_out_at);
const phone=x=>typeof x==='string'&&/^\+[1-9]\d{6,14}$/.test(x);
function conversationSnapshot(row){
 const raw=JSON.parse(row.payload)||{},scalar=(value,keys)=>Object.fromEntries(keys.filter(key=>typeof value?.[key]==='boolean'||typeof value?.[key]==='string'&&value[key].length<=8192||typeof value?.[key]==='number'&&Number.isFinite(value[key])).map(key=>[key,value[key]]));
 let data={};if(row.kind==='chat')data=scalar(raw,['id','name','displayName','unreadCount','archived','pinned','muteEndTime','conversationTimestamp','lastMessageRecvTimestamp','readOnly','ephemeralExpiration','markedAsUnread']);
 if(row.kind==='group'){data=scalar(raw,['id','subject','owner','ownerPn','subjectOwner','subjectTime','creation','desc','descOwner','descTime','linkedParent','restrict','announce','memberAddMode','joinApprovalMode','isCommunity','isCommunityAnnounce','size','ephemeralDuration','addressingMode']);data.participants=(Array.isArray(raw.participants)?raw.participants:[]).slice(0,4096).map(p=>scalar(p,['id','lid','phoneNumber','name','notify','admin','isAdmin','isSuperAdmin']));}
 if(row.kind==='presence'){data.presences={};for(const [jid,value] of Object.entries(raw.presences??{}).slice(0,256))if(/^\d+(?::\d+)?@(s\.whatsapp\.net|lid)$/.test(jid)){const item={};if(['available','unavailable','composing','recording','paused'].includes(value?.lastKnownPresence))item.lastKnownPresence=value.lastKnownPresence;for(const key of ['lastSeen','groupOnlineCount'])if(Number.isSafeInteger(value?.[key])&&value[key]>=0)item[key]=value[key];data.presences[jid]=item;}}
 return {kind:row.kind,resource_id:row.resource_id,data,updated_at:row.updated_at};
}
function catalogData(raw,collection=false){
 const out={};for(const key of ['id','owner_jid','name','retailerId','description','price','currency','availability'])if(typeof raw?.[key]==='string')out[key]=raw[key].slice(0,key==='description'?8192:512);else if(key==='price'&&Number.isFinite(raw?.[key]))out[key]=raw[key];
 for(const key of ['isHidden','has_images','available'])if(typeof raw?.[key]==='boolean')out[key]=raw[key];
 if(collection){out.products_collected=typeof raw.products_collected==='boolean'?raw.products_collected:null;out.products_truncated=typeof raw.products_truncated==='boolean'?raw.products_truncated:null;out.products=(Array.isArray(raw.products)?raw.products:[]).slice(0,100).filter(p=>p&&typeof p.id==='string'&&p.id.length>0&&p.id.length<=512).map(p=>catalogData(p));}
 return out;
}
const parseSnapshot=row=>row?{data:JSON.parse(row.payload),updated_at:row.updated_at}:null;
let referenceFields;
const mediaTypes={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.ogg':'audio/ogg','.mp3':'audio/mpeg','.m4a':'audio/mp4','.mp4':'video/mp4','.pdf':'application/pdf'};
const validMediaName=name=>typeof name==='string'&&name.length<=150&&/^[A-Za-z0-9_-]+\.[A-Za-z0-9]{1,8}$/.test(name);
const safeDeliveryErrors=new Set(['destination_not_allowed','destination_not_public','dns_timeout','invalid_payload','dispatcher_stopped','redirect_rejected','receiver_rate_limited','receiver_http_error','receiver_timeout','interrupted_delivery','delivery_failed']);
const deliveryError=value=>safeDeliveryErrors.has(value)?value:value?'delivery_failed':null;
const avatarErrors=new Set(['unavailable','disconnected','readtimeout','read_timeout','download_failed','avatar_unavailable','avatar_destination_rejected','avatar_download_failed','avatar_timeout','avatar_too_large','invalid_avatar_media']);
const avatarMimes={'.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
const callStatuses=['offer','ringing','preaccept','transport','relaylatency','timeout','reject','accept','terminate'];
const groupJid=value=>typeof value==='string'&&/^\d+(?:-\d+)?@g\.us$/.test(value);
const participantJid=value=>typeof value==='string'&&/^\d+@(s\.whatsapp\.net|lid)$/.test(value);
function safeJoinEvent(row){const data=JSON.parse(row.payload),safe={id:row.resource_id,group_id:data.group_id,participant:participantJid(data.participant)?data.participant:null,source:'group.join-request',updated_at:row.updated_at};for(const key of ['author','participantPn','authorPn'])if(participantJid(data[key]))safe[key]=data[key];const observation=item=>({action:['created','revoked','rejected'].includes(item?.action)?item.action:'unknown',method:typeof item?.method==='string'&&/^[a-z_]{1,40}$/i.test(item.method)?item.method:null,observed_at:typeof item?.observed_at==='string'&&Number.isFinite(Date.parse(item.observed_at))?new Date(item.observed_at).toISOString():null});return {...safe,...observation(data),history:(Array.isArray(data.history)?data.history:[]).slice(-20).map(observation)};}
function subgroupData(value){if(!value||!groupJid(value.id))return null;const output={id:value.id};if(typeof value.subject==='string')output.subject=value.subject.slice(0,512);if(participantJid(value.owner))output.owner=value.owner;for(const key of ['creation','size'])if(Number.isFinite(value[key])&&value[key]>=0)output[key]=value[key];return output;}
function groupReadSnapshot(row,kind){if(!row)return {observed:false,available:false,stale:false,collection_status:'not_collected',updated_at:null,[kind==='group_requests'?'requests':'groups']:[]};const data=JSON.parse(row.payload),field=kind==='group_requests'?'requests':'groups',items=Array.isArray(data[field])?data[field]:[],output={observed:true,available:data.available===true,response_verified:data.response_verified===true,stale:data.stale===true,truncated:data.truncated===true,updated_at:row.updated_at,status_code:Number.isInteger(data.status_code)&&data.status_code>=100&&data.status_code<=599?data.status_code:null,error:['read_timeout','invalid_response','disconnected','forbidden','access_denied','not_found','method_missing','provider_error'].includes(data.error)?data.error:data.error?'read_unavailable':null};output.collection_status=data.available===false?'unavailable':data.stale?'observed_partial':data.truncated?'truncated':data.available===true&&data.response_verified===true?'complete':'observed_partial';output[field]=items.slice(0,2000).map(item=>{if(kind!=='group_requests')return subgroupData(item);if(!participantJid(item?.jid))return null;const safe={jid:item.jid};if(typeof item.request_method==='string'&&/^[a-z_]{1,40}$/i.test(item.request_method))safe.request_method=item.request_method;if((typeof item.request_time==='string'&&/^\d{1,16}$/.test(item.request_time))||(Number.isFinite(item.request_time)&&item.request_time>=0))safe.request_time=item.request_time;return safe;}).filter(Boolean);if(items.length>2000)output.truncated=true;return output;}
function safeCall(row){const raw=JSON.parse(row.payload),safe={id:row.resource_id,updated_at:row.updated_at,history_complete:false,source:'observed_events'};for(const key of ['from','chatId','callerPn','groupJid'])if(typeof raw[key]==='string'&&raw[key].length<=256&&!/[\x00-\x20]/.test(raw[key])&&/^(?:\+?\d+|\d+(?::\d+)?@(s\.whatsapp\.net|lid)|[0-9-]+@g\.us)$/.test(raw[key]))safe[key]=raw[key];for(const key of ['isGroup','isVideo','offline'])if(typeof raw[key]==='boolean')safe[key]=raw[key];if(Number.isFinite(raw.latencyMs)&&raw.latencyMs>=0)safe.latencyMs=raw.latencyMs;for(const key of ['date','observed_at','last_event_at'])if(typeof raw[key]==='string'&&Number.isFinite(Date.parse(raw[key])))safe[key]=new Date(raw[key]).toISOString();safe.status=callStatuses.includes(raw.status)?raw.status:null;safe.history=(Array.isArray(raw.history)?raw.history:[]).slice(-50).map(event=>{const entry={status:callStatuses.includes(event?.status)?event.status:null};for(const key of ['date','observed_at'])if(typeof event?.[key]==='string'&&Number.isFinite(Date.parse(event[key])))entry[key]=new Date(event[key]).toISOString();return entry;});return safe;}
const safeAvatarFile=data=>data&&typeof data.filename==='string'&&/^[0-9a-f-]{36}\.(jpg|png|webp)$/.test(data.filename)&&avatarMimes[extname(data.filename)]===data.mime;
function existingAvatar(data,directory){if(!safeAvatarFile(data))return false;try{const privateDir=realpathSync(directory),dir=realpathSync(resolve(directory,'avatars')),file=realpathSync(resolve(dir,data.filename));if(!(dir.startsWith(privateDir+'/')||dir.startsWith(privateDir+'\\'))||!(file.startsWith(dir+'/')||file.startsWith(dir+'\\')))return false;const info=statSync(file);return info.isFile()&&info.size>0&&info.size<=LOCAL_LIMITS.avatar_bytes;}catch{return false;}}
function safeWebhookPayload(value,depth=0){if(depth>12)return '[depth limited]';if(Array.isArray(value))return value.map(item=>safeWebhookPayload(item,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!/(secret|token|authorization|cookie|qr_payload|credentials|session|password)/i.test(key)).map(([key,item])=>[key,safeWebhookPayload(item,depth+1)]));return value;}
function mediaMatches(data,mime){const head=data.subarray(0,16);return mime==='image/jpeg'?head[0]===255&&head[1]===216&&head[2]===255:mime==='image/png'?head.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):mime==='image/webp'?head.toString('ascii',0,4)==='RIFF'&&head.toString('ascii',8,12)==='WEBP':mime==='audio/ogg'?head.toString('ascii',0,4)==='OggS':mime==='audio/mpeg'?head.toString('ascii',0,3)==='ID3'||head[0]===255&&(head[1]&224)===224:mime==='audio/mp4'?head.toString('ascii',4,8)==='ftyp':mime==='application/pdf'?head.toString('ascii',0,5)==='%PDF-':false;}
export async function bootstrap(database=db,directory=stateDir){
 if(database.prepare("SELECT value FROM settings WHERE key='admin_password'").get())return;
 let password=randomBytes(20).toString('base64url');const salt=randomBytes(16).toString('hex');
 await mkdir(directory,{recursive:true,mode:0o700});
 try{await writeFile(resolve(directory,'admin-access.txt'),'WIS local administrator\nPassword: '+password+'\n',{mode:0o600,flag:'wx'});}catch(error){if(error.code!=='EEXIST')throw error;const existing=await readFile(resolve(directory,'admin-access.txt'),'utf8');const match=/^Password: ([A-Za-z0-9_-]{20,})$/m.exec(existing);if(!match)throw Error('Existing administrator file needs manual recovery');password=match[1];}
 database.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));
}
async function jsonBody(req){let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>LOCAL_LIMITS.json_body_bytes)fail(413,'body_too_large');}try{const value=JSON.parse(raw||'{}');if(!value||typeof value!=='object'||Array.isArray(value))throw 0;return value;}catch{fail(400,'invalid_json');}}
function cleanConnection(row){const {qr_payload,lease_owner,...safe}=row;return {...safe,identity_verified:Boolean(row.phone&&row.expected_phone_e164&&row.phone.replace(/\D/g,'')===row.expected_phone_e164.replace(/\D/g,'')),outbound_enabled:process.env.WIS_OUTBOUND_ENABLED==='true'};}
export function makeServer(database=db,options={}){
 const directory=options.stateDir??stateDir;const failures=new Map(),readAuditTimes=new Map(),groupInviteLookups=new Map();
 const lookupGroupInviteInfo=options.lookupGroupInviteInfo??createGroupInviteInfoRpc();
 const audit=(action,actor,id)=>database.prepare('INSERT INTO audit(action,actor,resource_id,created_at) VALUES(?,?,?,?)').run(action,actor,id??null,now());
 const ownAvatarTarget=()=>{const connection=database.prepare("SELECT * FROM connections WHERE id='wis-5679'").get();return connection?.phone&&cleanConnection(connection).identity_verified?connection.phone.replace(/\D/g,'')+'@s.whatsapp.net':null;};
 const knownAvatarTarget=(target,admin)=>{if(typeof target!=='string'||target.length>150||! /^(?:\d+@(s\.whatsapp\.net|lid)|[0-9-]+@g\.us)$/.test(target))fail(400,'invalid_avatar_target');const connection=database.prepare("SELECT * FROM connections WHERE id='wis-5679'").get(),actual=connection?.phone?connection.phone.replace(/\D/g,'')+'@s.whatsapp.net':null;if(target===actual){if(!admin)fail(403,'administrator_required');if(target!==ownAvatarTarget())fail(409,'identity_not_verified');return target;}const contact=database.prepare("SELECT 1 FROM contacts WHERE wa_jid=? OR (phone_e164 IS NOT NULL AND replace(phone_e164,'+','')||'@s.whatsapp.net'=?)").get(target,target);const chat=database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind='group' AND resource_id=?").get(target,target);if(!contact&&!chat)fail(404,'unknown_avatar_target');return target;};
 const avatarMetadata=target=>{if(!target)return null;const row=database.prepare("SELECT * FROM snapshots WHERE kind='avatar' AND resource_id=?").get(target);const data=row?JSON.parse(row.payload):null,cached=existingAvatar(data,directory),available=Boolean(data?.available&&cached),stale=Boolean(data?.stale);return {target,observed:Boolean(row),available,cached,stale,status:!row?'not_collected':stale?'stale':available?'available':'unavailable',mime:cached?data.mime:null,size:cached&&Number.isSafeInteger(data.size)?data.size:null,updated_at:row?.updated_at??null,last_attempt_at:typeof data?.last_attempt_at==='string'&&Number.isFinite(Date.parse(data.last_attempt_at))?new Date(data.last_attempt_at).toISOString():null,error:data?.error?(avatarErrors.has(data.error)?data.error:'unavailable'):null,content_url:cached?'/api/v1/avatars?target='+encodeURIComponent(target)+'&content=1':null};};
 const historyFor=conversation=>{const request=database.prepare("SELECT * FROM snapshots WHERE kind='history_request' AND json_extract(payload,'$.target')=? ORDER BY updated_at DESC LIMIT 1").get(conversation.wa_chat_id);return {latest_command:database.prepare("SELECT * FROM read_commands WHERE kind='history' AND target=? ORDER BY created_at DESC,id DESC LIMIT 1").get(conversation.wa_chat_id)??null,latest_request:request?{command_id:request.resource_id,...parseSnapshot(request)}:null,latest_sync:parseSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind='history' AND resource_id='wis-5679'").get()),latest_sync_scope:'account',complete:false,request_limit:LOCAL_LIMITS.history_request_messages};};
 const server=createServer(async(req,res)=>{
  const send=(data,status=200,meta)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({data,...(meta?{meta}:{})}));};
  try{
   const host=req.headers.host??'';if(!new RegExp('^(127\\.0\\.0\\.1|localhost):'+req.socket.localPort+'$').test(host))fail(403,'invalid_host');
   const url=new URL(req.url,'http://'+host),path=url.pathname,method=req.method;
   res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'");
   let actor=null;const bearer=req.headers.authorization;
   if(bearer){const match=/^Bearer (wis_[A-Za-z0-9_-]{40,})$/.exec(bearer);if(!match)fail(401,'invalid_token');const token=database.prepare('SELECT * FROM tokens WHERE token_hash=? AND revoked_at IS NULL').get(hash(match[1]));if(!token)fail(401,'invalid_token');actor={id:token.id,admin:false,scopes:JSON.parse(token.scopes)};}
   else {const cookie=/(?:^|;\s*)wis_session=([^;]+)/.exec(req.headers.cookie??'');if(cookie){const session=database.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').get(hash(cookie[1]),now());if(session)actor={id:'admin',admin:true,scopes};}}
   if(method!=='GET'&&method!=='HEAD'&&!bearer&&req.headers.origin!=='http://'+host)fail(403,'origin_required');
   const auth=(scope='read',admin=false)=>{if(!actor)fail(401,'authentication_required');if(admin&&!actor.admin||scope&&!actor.scopes.includes(scope))fail(403,'insufficient_scope');};
   if(['/api/session','/api/me'].includes(path)&&method==='GET')return send({authenticated:Boolean(actor),admin:Boolean(actor?.admin)});
   if(path==='/api/login'&&method==='POST'){
    const key=req.socket.remoteAddress;const attempt=failures.get(key);if(attempt?.count>=5&&attempt.until>Date.now())fail(429,'login_rate_limited');
    const b=await jsonBody(req);const stored=database.prepare("SELECT value FROM settings WHERE key='admin_password'").get()?.value;if(!stored)fail(503,'bootstrap_required');
    const [salt,value]=stored.split(':');const valid=typeof b.password==='string'&&b.password.length<512&&timingSafeEqual(scryptSync(b.password,salt,64),Buffer.from(value,'hex'));
    if(!valid){failures.set(key,{count:attempt?.until>Date.now()?attempt.count+1:1,until:Date.now()+900000});fail(401,'invalid_credentials');}
    failures.delete(key);const token=randomBytes(32).toString('base64url');database.prepare('INSERT INTO sessions(token_hash,expires_at) VALUES(?,?)').run(hash(token),new Date(Date.now()+12*3600000).toISOString());res.setHeader('Set-Cookie','wis_session='+token+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200');audit('login','admin');return send({authenticated:true,admin:true});
   }
   if(path==='/api/logout'&&method==='POST'){auth();const cookie=/(?:^|;\s*)wis_session=([^;]+)/.exec(req.headers.cookie??'');if(cookie)database.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(cookie[1]));res.setHeader('Set-Cookie','wis_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send({authenticated:false});}
   if(path.startsWith('/api/whatsapp/')){
    auth('read',true);const connection=database.prepare("SELECT * FROM connections WHERE id='wis-5679'").get();
    if(path==='/api/whatsapp/connection'&&method==='GET')return send(cleanConnection(connection));
    if(path==='/api/whatsapp/qr'&&method==='GET'){if(!connection.qr_payload||!connection.qr_expires_at||connection.qr_expires_at<=now())fail(404,'qr_unavailable');const QR=await import('qrcode');const svg=await QR.toString(connection.qr_payload,{type:'svg',margin:2});res.writeHead(200,{'Content-Type':'image/svg+xml','Cache-Control':'no-store'});return res.end(svg);}
    if(method==='POST'&&['connect','disconnect','logout'].includes(path.split('/').pop())){const command=path.split('/').pop();database.prepare("UPDATE connections SET command=?,updated_at=? WHERE id='wis-5679'").run(command,now());audit('connection.'+command,actor.id);return send({command},202);}
    if(path==='/api/whatsapp/identity'&&method==='POST'){const b=await jsonBody(req);if(!phone(b.phone_e164)||!b.phone_e164.endsWith('5679'))fail(400,'expected_line_5679_required');if(connection.status==='connected'&&connection.phone?.replace(/\D/g,'')!==b.phone_e164.replace(/\D/g,''))fail(409,'connected_identity_mismatch');database.prepare("UPDATE connections SET expected_phone_e164=?,updated_at=? WHERE id='wis-5679'").run(b.phone_e164,now());audit('connection.identity',actor.id);return send({expected_phone_e164:b.phone_e164});}
    fail(404,'not_found');
   }
   if(path.startsWith('/api/v1/')){
    auth(null);const resource=path.slice('/api/v1/'.length);if(method==='GET'&&!['tokens','webhooks','webhook-deliveries','webhook-events'].includes(resource))auth('read');const b=method==='GET'||method==='DELETE'?{}:await jsonBody(req);
    if(resource==='group-invite-info'&&method==='POST'){
     auth('read',true);if(Object.keys(b).some(k=>k!=='invite_code')||!validGroupInviteCode(b.invite_code))fail(400,'invalid_invite_code');
     const last=groupInviteLookups.get(actor.id)??0;if(Date.now()-last<5000)fail(429,'read_rate_limited');groupInviteLookups.set(actor.id,Date.now());
     let result;try{result=await lookupGroupInviteInfo.lookup(b.invite_code);}catch(error){const code=error?.message,status=code==='read_timeout'?504:code==='previous_read_unresolved'?409:code==='invalid_invite_code'?400:code==='connection_unavailable'||code==='connection_changed'?503:code==='capability_unavailable'?501:502;fail(status,['read_timeout','previous_read_unresolved','invalid_invite_code','connection_unavailable','connection_changed','capability_unavailable','invalid_group_metadata_response'].includes(code)?code:'read_failed');}
     audit('group.metadata_by_invite_code',actor.id,randomUUID());return send(result.data,200,result.meta);
    }
    if(method==='GET')res.once('finish',()=>{if(res.statusCode>=400)return;const key=actor.id+':'+resource,date=Date.now();if(date-(readAuditTimes.get(key)??0)<60000)return;try{audit('api.read.'+resource,actor.id);readAuditTimes.set(key,date);if(readAuditTimes.size>1000)for(const [k,t]of readAuditTimes)if(date-t>60000)readAuditTimes.delete(k);}catch{/* Never fail an already completed read on audit write contention. */}});
    const page=()=>{const limit=Number(url.searchParams.get('limit')??LOCAL_LIMITS.page_default),offset=Number(url.searchParams.get('offset')??0),q=url.searchParams.get('q')??'';if(!Number.isInteger(limit)||limit<1||limit>LOCAL_LIMITS.page_max||!Number.isSafeInteger(offset)||offset<0||q.length>LOCAL_LIMITS.search_max_chars)fail(400,'invalid_pagination');return {limit,offset,q};};
    const paged=(from,where,args,order,columns='*',map=x=>x,extraMeta={})=>{const {limit,offset}=page();const total=database.prepare('SELECT count(*) AS n FROM '+from+(where?' WHERE '+where:'')).get(...args).n;const rows=database.prepare('SELECT '+columns+' FROM '+from+(where?' WHERE '+where:'')+' ORDER BY '+order+' LIMIT ? OFFSET ?').all(...args,limit,offset);return send(rows.map(map),200,{total,limit,offset,has_more:offset+rows.length<total,...extraMeta});};
    const search=()=>'%'+page().q.replace(/[\\%_]/g,'\\$&')+'%';
    if(['group-requests','community-subgroups'].includes(resource)&&method==='GET'){
     const target=url.searchParams.get('target');if(!groupJid(target))fail(400,'invalid_group_jid');const known=database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind IN('group','community') AND resource_id=?").get(target,target);if(!known)fail(404,'unknown_target');if(resource==='community-subgroups'&&!database.prepare("SELECT 1 FROM snapshots WHERE resource_id=? AND (kind='community' OR (kind='group' AND json_extract(payload,'$.isCommunity')=1))").get(target))fail(404,'unknown_community');const kind=resource==='group-requests'?'group_requests':'community_subgroups',row=database.prepare('SELECT * FROM snapshots WHERE kind=? AND resource_id=?').get(kind,target);const output={target,...groupReadSnapshot(row,kind)};if(kind==='group_requests'){const where="kind='group_join_event' AND json_extract(payload,'$.group_id')=?";const total=database.prepare('SELECT count(*) AS n FROM snapshots WHERE '+where).get(target).n;output.observed_events=database.prepare('SELECT * FROM snapshots WHERE '+where+' ORDER BY updated_at DESC,resource_id LIMIT 200').all(target).map(safeJoinEvent);output.observed_events_meta={total,limit:200,truncated:total>200,complete:false,source:'observed_events',current_pending_inferred:false};}return send(output);
    }
    if(resource==='stories'&&method==='GET'){
     // Filter in SQL before pagination/detail so a delayed cleanup never exposes expired content.
     const cutoff=now(),active="kind='story' AND json_valid(payload) AND julianday(json_extract(payload,'$.expires_at'))>julianday(?) AND julianday(json_extract(payload,'$.date'))<=julianday('now') AND julianday(json_extract(payload,'$.expires_at'))<=julianday(json_extract(payload,'$.date'))+1 AND coalesce(json_extract(payload,'$.revoked'),0)=0 AND coalesce(json_extract(payload,'$.expired'),0)=0",id=url.searchParams.get('id');
     const safe=row=>{const data=JSON.parse(row.payload),author=typeof data.author==='string'&&/^\d+(?::\d+)?@(s\.whatsapp\.net|lid)$/.test(data.author)?data.author:null;const contact=author?database.prepare('SELECT id,display_name FROM contacts WHERE wa_jid=? LIMIT 1').get(author):null;return {id:row.resource_id,author,fromMe:typeof data.fromMe==='boolean'?data.fromMe:null,type:['text','image','video','audio','document','sticker','unknown'].includes(data.type)?data.type:'unknown',body:typeof data.body==='string'?data.body.slice(0,8192):null,date:typeof data.date==='string'&&Number.isFinite(Date.parse(data.date))?new Date(data.date).toISOString():null,expires_at:new Date(data.expires_at).toISOString(),source:['live','import'].includes(data.source)?data.source:'unknown',updated_at:row.updated_at,contact:contact?{id:contact.id,display_name:contact.display_name}:null,media_available:false,history_complete:false};};
     if(id){if(id.length>512||/[\x00-\x20]/.test(id))fail(400,'invalid_story_id');const row=database.prepare('SELECT * FROM snapshots WHERE '+active+' AND resource_id=?').get(cutoff,id);if(!row)fail(404,'story_not_available');return send(safe(row));}
     const author=url.searchParams.get('author');if(author&&!/^\d+(?::\d+)?@(s\.whatsapp\.net|lid)$/.test(author))fail(400,'invalid_story_author');const clauses=[active],args=[cutoff];if(author){clauses.push("json_extract(payload,'$.author')=?");args.push(author);}if(page().q){clauses.push("(resource_id LIKE ? ESCAPE '\\' OR json_extract(payload,'$.author') LIKE ? ESCAPE '\\' OR json_extract(payload,'$.body') LIKE ? ESCAPE '\\')");args.push(search(),search(),search());}return paged('snapshots',clauses.join(' AND '),args,'updated_at DESC,resource_id','*',safe,{history_complete:false,source:'observed_events',active_only:true,media_downloads:false,read_receipts:false});
    }
    if(resource==='identities'&&method==='GET'){
     const contacts=database.prepare('SELECT id,wa_jid,phone_e164,created_at FROM contacts').all(),rows=[],covered=new Set();
     const lidPattern=/^\d+@lid$/,pnPattern=/^[1-9]\d{6,14}@s\.whatsapp\.net$/;
     for(const row of database.prepare("SELECT * FROM snapshots WHERE kind='identity' ORDER BY updated_at DESC,resource_id").all()){
      let data;try{data=JSON.parse(row.payload);}catch{continue;}if(!lidPattern.test(row.resource_id)||data.lid!==row.resource_id||!pnPattern.test(data.pn)||!['lid-mapping.update','messaging-history.set','contacts'].includes(data.source))continue;
      const phone='+'+data.pn.split('@')[0],conflict=data.conflict===true||data.status==='conflict';covered.add(data.lid);covered.add(data.pn);
      rows.push({id:data.lid,lid:data.lid,pn:data.pn,phone_e164:phone,status:conflict?'conflict':'observed',conflict,candidate_pns:[...new Set([data.pn,data.conflicting_pn,...(Array.isArray(data.candidate_pns)?data.candidate_pns:[])].filter(value=>typeof value==='string'&&pnPattern.test(value)))].slice(0,20),conflicting_pn:pnPattern.test(data.conflicting_pn??'')?data.conflicting_pn:null,source:data.source,observed_at:typeof data.observed_at==='string'&&Number.isFinite(Date.parse(data.observed_at))?new Date(data.observed_at).toISOString():null,updated_at:row.updated_at,contact_ids:contacts.filter(c=>c.wa_jid===data.lid||c.wa_jid===data.pn||c.phone_e164===phone).map(c=>c.id)});
     }
     const pnCounts=new Map();for(const row of rows)for(const candidate of row.candidate_pns)pnCounts.set(candidate,(pnCounts.get(candidate)??0)+1);for(const row of rows)if(row.candidate_pns.length>1||row.candidate_pns.some(candidate=>pnCounts.get(candidate)>1)){row.status='conflict';row.conflict=true;}
     for(const contact of contacts){const jid=contact.wa_jid;if(!jid||covered.has(jid)||!lidPattern.test(jid)&&!pnPattern.test(jid))continue;covered.add(jid);const lid=lidPattern.test(jid)?jid:null,pn=pnPattern.test(jid)?jid:null;rows.push({id:jid,lid,pn,phone_e164:pn?'+'+pn.split('@')[0]:null,status:'unknown',conflict:false,candidate_pns:pn?[pn]:[],conflicting_pn:null,source:'contact_identifier_only',observed_at:null,updated_at:contact.created_at,contact_ids:contacts.filter(c=>c.wa_jid===jid).map(c=>c.id)});}
     const id=url.searchParams.get('id');if(id){if(id.length>200)fail(400,'invalid_identity_id');const row=rows.find(x=>x.id===id);if(!row)fail(404,'identity_not_observed');return send(row);}
     const {limit,offset,q}=page(),lid=url.searchParams.get('lid'),pn=url.searchParams.get('pn');if(lid&&!lidPattern.test(lid)||pn&&!pnPattern.test(pn)&&!/^\+[1-9]\d{6,14}$/.test(pn))fail(400,'invalid_identity_filter');const matched=rows.filter(x=>(!lid||x.lid===lid)&&(!pn||x.candidate_pns.includes(pn.startsWith('+')?pn.slice(1)+'@s.whatsapp.net':pn))&&(!q||[x.id,x.lid,x.pn,x.phone_e164,...x.candidate_pns,...x.contact_ids].some(v=>v?.toLowerCase().includes(q.toLowerCase())))).sort((a,b)=>(b.updated_at??'').localeCompare(a.updated_at??'')||a.id.localeCompare(b.id));return send(matched.slice(offset,offset+limit),200,{total:matched.length,limit,offset,has_more:offset+limit<matched.length,history_complete:false,source:'persisted_identity_observations',unknown_means:'No explicit LID/PN pair has been observed; no phone is inferred from LID.'});
    }
    if(resource==='calls'&&method==='GET'){
     const id=url.searchParams.get('id');if(id){if(id.length>256||/[\x00-\x20]/.test(id))fail(400,'invalid_call_id');const row=database.prepare("SELECT * FROM snapshots WHERE kind='call' AND resource_id=?").get(id);if(!row)fail(404,'call_not_observed');return send(safeCall(row));}
     const status=url.searchParams.get('status');if(status&&!callStatuses.includes(status))fail(400,'invalid_call_status');const clauses=["kind='call'"],args=[];if(status){clauses.push("json_extract(payload,'$.status')=?");args.push(status);}if(page().q){clauses.push("(resource_id LIKE ? ESCAPE '\\' OR json_extract(payload,'$.from') LIKE ? ESCAPE '\\' OR json_extract(payload,'$.chatId') LIKE ? ESCAPE '\\')");args.push(search(),search(),search());}return paged('snapshots',clauses.join(' AND '),args,'updated_at DESC,resource_id','*',safeCall,{history_complete:false,source:'observed_events',collection_scope:'persisted_call_snapshots',legacy_events_included:false});
    }
    const avatarForTarget=target=>{try{return avatarMetadata(knownAvatarTarget(target,actor.admin));}catch{return null;}};
    if(resource==='avatars'&&method==='GET'){
     const target=knownAvatarTarget(url.searchParams.get('target'),actor.admin),metadata=avatarMetadata(target);if(!url.searchParams.has('content'))return send(metadata);if(url.searchParams.get('content')!=='1')fail(400,'invalid_avatar_content');const row=database.prepare("SELECT payload FROM snapshots WHERE kind='avatar' AND resource_id=?").get(target),data=row?JSON.parse(row.payload):null;if(!safeAvatarFile(data))fail(404,'avatar_unavailable');const privateDir=await realpath(directory),avatarsDir=await realpath(resolve(directory,'avatars'));if(!avatarsDir.startsWith(privateDir+'/')&&!avatarsDir.startsWith(privateDir+'\\'))fail(403,'avatar_outside_storage');const file=await realpath(resolve(avatarsDir,data.filename));if(!file.startsWith(avatarsDir+'/')&&!file.startsWith(avatarsDir+'\\'))fail(403,'avatar_outside_storage');const info=await stat(file);if(!info.isFile()||info.size<1||info.size>LOCAL_LIMITS.avatar_bytes)fail(413,'avatar_size_invalid');const bytes=await readFile(file);if(!mediaMatches(bytes,data.mime))fail(415,'avatar_type_mismatch');res.writeHead(200,{'Content-Type':data.mime,'Content-Length':bytes.length,'Content-Disposition':'inline; filename="avatar'+extname(data.filename)+'"','Cache-Control':'private, no-store'});return res.end(bytes);
    }
    if(resource==='overview'&&method==='GET'){
     const count=table=>database.prepare('SELECT count(*) AS n FROM '+table).get().n;
     const counts={contacts:count('contacts'),conversations:count('conversations'),messages:count('messages'),groups:database.prepare("SELECT count(*) AS n FROM snapshots WHERE kind='group'").get().n,operations:count('operations'),pending:database.prepare("SELECT count(*) AS n FROM operations WHERE status IN('pending','sending')").get().n,failed:database.prepare("SELECT count(*) AS n FROM operations WHERE status IN('failed','outcome_unknown')").get().n,events:count('events')};
     return send({counts,connection:cleanConnection(database.prepare("SELECT * FROM connections WHERE id='wis-5679'").get()),account_updated_at:database.prepare("SELECT max(updated_at) AS value FROM snapshots WHERE resource_id='wis-5679'").get().value,last_event_at:database.prepare('SELECT max(created_at) AS value FROM events').get().value,history_complete:false});
    }
    if(resource==='coverage'&&method==='GET'){auth('read');return send(buildDataCoverage(database));}
    if(resource==='contact-checks'&&method==='GET'){auth('read');const id=url.searchParams.get('id');if(id&&id.length>100)fail(400,'invalid_contact_id');if(id&&!database.prepare('SELECT 1 FROM contacts WHERE id=?').get(id))fail(404,'contact_not_found');const rows=id?database.prepare("SELECT resource_id,payload,updated_at FROM snapshots WHERE kind='contact_check' AND resource_id=?").all(id):database.prepare("SELECT s.resource_id,s.payload,s.updated_at FROM snapshots s JOIN contacts c ON c.id=s.resource_id WHERE s.kind='contact_check' ORDER BY s.updated_at DESC LIMIT 1000").all();if(id){const command=database.prepare("SELECT id,kind,target,status,error,created_at,updated_at FROM read_commands WHERE kind='contact_check' AND target=? ORDER BY created_at DESC,id DESC LIMIT 1").get(id);return send({contact_id:id,result:rows[0]?parseSnapshot(rows[0]):null,command:command??null});}return send(rows.map(row=>({contact_id:row.resource_id,...parseSnapshot(row),updated_at:row.updated_at})));}
    if(resource==='limits'&&method==='GET'){auth('read',true);return send({source:'local_config',limits:LOCAL_LIMITS,flags:{outbound_enabled:process.env.WIS_OUTBOUND_ENABLED==='true',webhooks_enabled:process.env.WIS_WEBHOOKS_ENABLED==='true'},safe_daily_volume:null,provider_plan:false,editable:false});}
    if(resource==='account-limits'&&method==='GET'){auth('read',true);return send(accountLimits(database.prepare("SELECT * FROM snapshots WHERE kind='account_limits' AND resource_id='wis-5679'").get()));}
    if(resource==='account'&&method==='GET'){auth('read',true);const account={};for(const kind of ['profile','status','privacy','business','history','connection'])account[kind]=parseSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind=? AND resource_id='wis-5679'").get(kind));account.avatar=avatarMetadata(ownAvatarTarget());account.updated_at=database.prepare("SELECT max(updated_at) AS value FROM snapshots WHERE resource_id='wis-5679'").get().value;return send(account);}
    if(resource==='snapshots'&&method==='GET'){const requested=url.searchParams.get('kind'),kind=requested==='contact_profile'?'contact':requested;if(!['contact','chat','group','presence','message'].includes(kind))fail(400,'invalid_snapshot_kind');const id=url.searchParams.get('resource_id');if(id&&id.length>200)fail(400,'invalid_resource_id');return paged('snapshots','kind=?'+(id?' AND resource_id=?':''),id?[kind,id]:[kind],'updated_at DESC,resource_id','*',row=>({kind:row.kind,resource_id:row.resource_id,data:JSON.parse(row.payload),updated_at:row.updated_at}));}
    if(resource==='groups'&&method==='GET'){const id=url.searchParams.get('id');if(id){if(id.length>200)fail(400,'invalid_resource_id');const row=database.prepare("SELECT * FROM snapshots WHERE kind='group' AND resource_id=?").get(id);if(!row)fail(404,'group_not_observed');return send({...JSON.parse(row.payload),id:row.resource_id,updated_at:row.updated_at,avatar:avatarForTarget(row.resource_id)});}const where="kind='group'"+(page().q?" AND (resource_id LIKE ? ESCAPE '\\' OR json_extract(payload,'$.subject') LIKE ? ESCAPE '\\')":'');return paged('snapshots',where,page().q?[search(),search()]:[],'updated_at DESC,resource_id','*',row=>({...JSON.parse(row.payload),id:row.resource_id,updated_at:row.updated_at}));}
    const explorers={labels:{kind:'label',summary:'labels'},'label-associations':{kind:'label_association',summary:'label_associations'},communities:{kind:'community',summary:'communities'},channels:{kind:'newsletter',summary:'newsletters'},products:{kind:'product',summary:'catalog'},collections:{kind:'collection',summary:'collections'}};
    if(resource==='communities'&&method==='GET'&&url.searchParams.has('id')){const id=url.searchParams.get('id');if(!groupJid(id))fail(400,'invalid_group_jid');const row=database.prepare("SELECT * FROM snapshots WHERE kind='community' AND resource_id=?").get(id);if(!row)fail(404,'community_not_observed');const raw=JSON.parse(row.payload),data=subgroupData({...raw,id})??{id};for(const key of ['desc','description'])if(typeof raw[key]==='string')data[key]=raw[key].slice(0,4096);for(const key of ['isCommunity','isCommunityAnnounce','announce','restrict'])if(typeof raw[key]==='boolean')data[key]=raw[key];return send({...data,updated_at:row.updated_at,linked_groups:(Array.isArray(raw.linked_groups)?raw.linked_groups:[]).slice(0,2000).map(subgroupData).filter(Boolean),subgroups:groupReadSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind='community_subgroups' AND resource_id=?").get(id),'community_subgroups')});}
    if(method==='GET'&&((['products','collections'].includes(resource)&&url.searchParams.has('id'))||resource==='collection-products')){
     const collection=resource!=='products',id=url.searchParams.get(resource==='collection-products'?'collection_id':'id');if(typeof id!=='string'||!id.trim()||id.length>512||/[\x00-\x1f]/.test(id))fail(400,'invalid_catalog_id');const row=database.prepare('SELECT * FROM snapshots WHERE kind=? AND resource_id=?').get(collection?'collection':'product',id);if(!row)fail(404,'catalog_item_not_found');const raw=JSON.parse(row.payload),safe=catalogData(raw,collection);
     const summary=typeof raw.owner_jid==='string'?database.prepare('SELECT * FROM snapshots WHERE kind=? AND resource_id=?').get(collection?'collections':'catalog',raw.owner_jid):null;const summaryRaw=summary?JSON.parse(summary.payload):{};const summaryData={};for(const key of ['available','response_verified','stale','truncated','known_only','has_more'])if(typeof summaryRaw[key]==='boolean')summaryData[key]=summaryRaw[key];for(const key of ['product_count','collection_count','pages'])if(Number.isSafeInteger(summaryRaw[key])&&summaryRaw[key]>=0)summaryData[key]=summaryRaw[key];summaryData.scope=['public_catalog','contact_catalog'].includes(summaryRaw.scope)?summaryRaw.scope:'observed_catalog';summaryData.source=['public_whatsapp_graphql','checked_baileys_iq','getCatalog','getCollections'].includes(summaryRaw.source)?summaryRaw.source:null;summaryData.error=['read_timeout','read_pending','disconnected','method_missing','identity_unavailable','invalid_response','access_denied','rate_limited','provider_error','read_failed','transport_failed','public_catalog_unavailable','graphql_error','public_catalog_config_unavailable'].includes(summaryRaw.error)?summaryRaw.error:summaryRaw.error?'read_failed':null;for(const key of ['last_attempt_at','last_success_at'])summaryData[key]=typeof summaryRaw[key]==='string'&&Number.isFinite(Date.parse(summaryRaw[key]))?new Date(summaryRaw[key]).toISOString():null;
     const meta={observed:true,history_complete:false,scope:summaryData.scope,stale:summaryData.stale===true,collection_status:summaryRaw.available===false||raw.available===false?'unavailable':'observed_partial',summaries:summary?[{resource_id:summary.resource_id,data:summaryData,updated_at:summary.updated_at}]:[]};
     if(resource==='collection-products'){const {limit,offset,q}=page();const products=safe.products.filter(p=>!q||[p.id,p.name??'',p.description??''].some(value=>value.toLowerCase().includes(q.toLowerCase())));const data=products.slice(offset,offset+limit);return send(data,200,{...meta,observed:safe.products_collected===false?false:safe.products_collected===true||safe.products.length>0,collection_id:id,total:products.length,limit,offset,has_more:offset+data.length<products.length,products_collected:safe.products_collected,products_truncated:safe.products_truncated,collection_status:meta.collection_status==='unavailable'?'unavailable':safe.products_collected===false||safe.products_collected!==true&&!safe.products.length?'not_collected':safe.products_truncated?'truncated':'observed_partial'});}
     return send({...safe,[collection?'collection_id':'product_id']:safe.id??null,id:row.resource_id,updated_at:row.updated_at},200,meta);
    }
    if(explorers[resource]&&method==='GET'){
     const config=explorers[resource],where='kind=?'+(page().q?" AND (resource_id LIKE ? ESCAPE '\\' OR payload LIKE ? ESCAPE '\\')":'');
     const observed=database.prepare('SELECT count(*) AS n,max(updated_at) AS last FROM snapshots WHERE kind IN(?,?)').get(config.kind,config.summary);
     const summaries=database.prepare('SELECT * FROM snapshots WHERE kind=? ORDER BY updated_at DESC').all(config.summary).map(row=>({resource_id:row.resource_id,...parseSnapshot(row)}));
     const collection_status=!observed.n?'not_collected':summaries.some(s=>s.data.available===false)?'unavailable':summaries.some(s=>s.data.truncated||s.data.has_more)?'truncated':summaries.some(s=>s.data.known_only)?'observed_partial':summaries.length&&summaries.every(s=>s.data.available===true&&s.data.response_verified===true)?'complete':'observed_partial';
     return paged('snapshots',where,page().q?[config.kind,search(),search()]:[config.kind],'updated_at DESC,resource_id','*',row=>({...JSON.parse(row.payload),id:row.resource_id,updated_at:row.updated_at}),{observed:observed.n>0,collection_status,last_updated_at:observed.last,summaries});
    }
    if(resource==='group-invite'&&method==='GET'){
     auth('read',true);const target=url.searchParams.get('target');if(!groupJid(target))fail(400,'invalid_group_jid');if(!database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind IN('group','community') AND resource_id=?").get(target,target))fail(404,'unknown_target');
     const row=database.prepare("SELECT * FROM snapshots WHERE kind='group_invite' AND resource_id=?").get(target),raw=row?JSON.parse(row.payload):{},date=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;const expires=date(raw.expires_at),success=date(raw.last_success_at),valid=Boolean(raw.available===true&&raw.response_verified===true&&typeof raw.code==='string'&&/^[A-Za-z0-9]{10,128}$/.test(raw.code)&&expires&&success&&Date.parse(success)<=Date.now()&&Date.parse(expires)>Date.now()&&Date.parse(expires)>Date.parse(success)&&Date.parse(expires)-Date.parse(success)<=300000);
     return send({target,observed:Boolean(row),code:valid?raw.code:null,available:valid,response_verified:raw.response_verified===true,expires_at:valid?expires:null,expired:raw.expired===true||Boolean(row&&raw.code&&!valid),last_attempt_at:date(raw.last_attempt_at),last_success_at:success,error:['read_timeout','read_pending','disconnected','method_missing','invalid_response','access_denied','rate_limited','provider_error','read_failed','not_found'].includes(raw.error)?raw.error:raw.error?'read_failed':null});
    }
    if(resource==='contact-products'&&method==='GET'){
     const target=url.searchParams.get('target');if(typeof target!=='string'||!/^[1-9]\d{6,14}@s\.whatsapp\.net$/.test(target))fail(400,'invalid_contact_catalog_target');if(!database.prepare('SELECT 1 FROM contacts WHERE wa_jid=? OR phone_e164=?').get(target,'+'+target.split('@')[0]))fail(404,'unknown_target');
     const row=database.prepare("SELECT * FROM snapshots WHERE kind='catalog' AND resource_id=?").get(target),raw=row?JSON.parse(row.payload):{},date=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
     const {limit,offset,q}=page();const where="kind='product' AND json_extract(payload,'$.owner_jid')=?"+(q?" AND (json_extract(payload,'$.name') LIKE ? ESCAPE '\\' OR json_extract(payload,'$.description') LIKE ? ESCAPE '\\')":'');const args=q?[target,search(),search()]:[target];return paged('snapshots',where,args,'updated_at DESC,resource_id','*',r=>{const value=catalogData(JSON.parse(r.payload));return {...value,product_id:value.id??null,id:r.resource_id,updated_at:r.updated_at};},{target,scope:'contact_catalog',observed:Boolean(row),available:raw.available===true,response_verified:raw.response_verified===true,stale:raw.stale===true,truncated:raw.truncated===true||raw.has_more===true,collection_status:!row?'not_collected':raw.available!==true?'unavailable':raw.truncated||raw.has_more?'truncated':'observed_partial',error:['read_timeout','read_pending','disconnected','method_missing','invalid_response','access_denied','rate_limited','provider_error','read_failed','not_found'].includes(raw.error)?raw.error:raw.error?'read_failed':null,last_attempt_at:date(raw.last_attempt_at),last_success_at:date(raw.last_success_at),history_complete:false});
    }
    if(resource==='bots'&&method==='GET'){
     const row=database.prepare("SELECT * FROM snapshots WHERE kind='bot_list' AND resource_id='wis-5679'").get();const raw=row?JSON.parse(row.payload):{},date=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
     const bots=(Array.isArray(raw.bots)?raw.bots:[]).slice(0,1000).filter(b=>typeof b?.jid==='string'&&/^\d{1,40}@(s\.whatsapp\.net|lid|bot)$/.test(b.jid)).map(b=>({jid:b.jid,persona_id:typeof b.persona_id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(b.persona_id)?b.persona_id:null}));const {limit,offset,q}=page();const filtered=bots.filter(b=>!q||[b.jid,b.persona_id??''].some(value=>value.toLowerCase().includes(q.toLowerCase())));const data=filtered.slice(offset,offset+limit);return send(data,200,{total:filtered.length,limit,offset,has_more:offset+data.length<filtered.length,observed:Boolean(row),available:raw.available===true,response_verified:raw.response_verified===true,stale:raw.stale===true,truncated:raw.truncated===true||(raw.bots?.length??0)>1000,collection_status:!row?'not_collected':raw.available!==true?'unavailable':raw.stale?'observed_partial':raw.truncated?'truncated':'observed_partial',error:['read_timeout','read_pending','disconnected','method_missing','invalid_response','access_denied','rate_limited','provider_error','read_failed'].includes(raw.error)?raw.error:raw.error?'read_failed':null,last_attempt_at:date(raw.last_attempt_at),last_success_at:date(raw.last_success_at),last_updated_at:row?.updated_at??null,scope:'provider_bot_catalog',wis_automations:false,partial:true,history_complete:false});
    }
    if(resource==='channel-messages'&&method==='GET'){
     const target=url.searchParams.get('target');if(!/^\d{1,40}@newsletter$/.test(target??'')||target.length>150)fail(400,'invalid_newsletter_jid');if(!database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind='newsletter' AND resource_id=?").get(target,target))fail(404,'unknown_target');
     const row=database.prepare("SELECT * FROM snapshots WHERE kind='newsletter_messages' AND resource_id=?").get(target);const raw=row?JSON.parse(row.payload):{},date=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
     const messages=(Array.isArray(raw.messages)?raw.messages:[]).slice(0,50).filter(m=>typeof m?.id==='string'&&/^[\x21-\x7e]{1,256}$/.test(m.id)).map(m=>({id:m.id,server_id:typeof m.server_id==='string'&&/^\d{1,40}$/.test(m.server_id)?m.server_id:Number.isSafeInteger(m.server_id)&&m.server_id>=0?String(m.server_id):null,date:date(m.date),type:['text','image','video','audio','document','sticker','reaction','poll','unknown'].includes(m.type)?m.type:'unknown',body:typeof m.body==='string'?m.body.slice(0,8192):null,media_available:false}));
     const {limit,offset,q}=page();const filtered=messages.filter(m=>!q||[m.id,m.body??''].some(value=>value.toLowerCase().includes(q.toLowerCase())));const data=filtered.slice(offset,offset+limit);return send(data,200,{target,total:filtered.length,limit,offset,has_more:offset+data.length<filtered.length,observed:Boolean(row),available:raw.available===true,response_verified:raw.response_verified===true,stale:raw.stale===true,truncated:raw.truncated===true||(raw.messages?.length??0)>50,history_complete:false,partial:true,collection_status:!row?'not_collected':raw.available!==true?'unavailable':raw.stale?'observed_partial':raw.truncated?'truncated':'observed_partial',error:['read_timeout','read_pending','disconnected','method_missing','invalid_response','access_denied','rate_limited','provider_error','read_failed','not_found'].includes(raw.error)?raw.error:raw.error?'read_failed':null,last_attempt_at:date(raw.last_attempt_at),last_success_at:date(raw.last_success_at),last_updated_at:row?.updated_at??null,source:'checked_newsletter_iq'});
    }
    if(resource==='blocklist'&&method==='GET'){
     auth('read',true);const row=database.prepare("SELECT * FROM snapshots WHERE kind='blocklist' AND resource_id='wis-5679'").get();const snapshot=row?JSON.parse(row.payload):null,{limit,offset,q}=page();const ids=Array.isArray(snapshot?.ids)?snapshot.ids:[];const filtered=ids.filter(id=>typeof id==='string'&&id.toLowerCase().includes(q.toLowerCase()));const data=filtered.slice(offset,offset+limit).map(id=>({id}));return send(data,200,{total:filtered.length,limit,offset,has_more:offset+data.length<filtered.length,observed:Boolean(row),available:snapshot?.available??false,collection_status:!row?'not_collected':snapshot?.available===false?'unavailable':snapshot?.truncated?'truncated':snapshot?.response_verified===true?'complete':'observed_partial',truncated:snapshot?.truncated===true,stale:snapshot?.stale===true,response_verified:snapshot?.response_verified===true,error:['read_timeout','read_pending','disconnected','method_missing','identity_unavailable','invalid_target','unknown_target','not_found','invalid_response','access_denied','rate_limited','provider_error','read_failed','transport_failed'].includes(snapshot?.error)?snapshot.error:snapshot?.error?'read_failed':null,last_attempt_at:typeof snapshot?.last_attempt_at==='string'&&Number.isFinite(Date.parse(snapshot.last_attempt_at))?new Date(snapshot.last_attempt_at).toISOString():null,last_success_at:typeof snapshot?.last_success_at==='string'&&Number.isFinite(Date.parse(snapshot.last_success_at))?new Date(snapshot.last_success_at).toISOString():null,last_updated_at:row?.updated_at??null});
    }
    if(resource==='events'&&method==='GET'){const kind=url.searchParams.get('kind');if(kind&&kind.length>100)fail(400,'invalid_event_kind');return paged('events',kind?'kind=?':'',kind?[kind]:[],'created_at DESC,id DESC','*',row=>({id:row.id,kind:row.kind,resource_id:row.resource_id,data:JSON.parse(row.payload),created_at:row.created_at}));}
    if(resource==='history'&&method==='GET'){const id=url.searchParams.get('conversation_id');if(!id||id.length>200)fail(400,'conversation_required');const conversation=database.prepare('SELECT * FROM conversations WHERE id=?').get(id);if(!conversation)fail(404,'conversation_not_found');return send(historyFor(conversation));}
     if(resource==='order-details'&&method==='GET'){const id=url.searchParams.get('message_id');if(!id||id.length>200)fail(400,'invalid_message_id');const message=database.prepare("SELECT id,wa_message_id,type FROM messages WHERE id=? AND type='order'").get(id);if(!message)fail(404,'order_message_not_found');const messageSnapshot=message.wa_message_id?parseSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind='message' AND resource_id=?").get(message.wa_message_id)):null;if(messageSnapshot?.data?.revoked||messageSnapshot?.data?.edited||messageSnapshot?.data?.deleted)return send({message_id:message.id,available:false,revoked:Boolean(messageSnapshot.data.revoked),edited:Boolean(messageSnapshot.data.edited),deleted:Boolean(messageSnapshot.data.deleted),details:null,command:null});const row=message.wa_message_id?database.prepare("SELECT * FROM snapshots WHERE kind='order_details' AND resource_id=?").get(message.wa_message_id):null,command=message.wa_message_id?database.prepare("SELECT id,kind,target,status,error,created_at,updated_at FROM read_commands WHERE kind='order_details' AND target=? ORDER BY created_at DESC,id DESC LIMIT 1").get(message.wa_message_id):null;return send({message_id:message.id,available:Boolean(row),revoked:false,details:row?parseSnapshot(row):null,command:command??null});}
    if(resource==='sync'){
     auth('read',true);if(method==='GET'&&url.searchParams.has('id')){const id=url.searchParams.get('id');if(!id||id.length>100)fail(400,'invalid_command_id');const command=database.prepare('SELECT * FROM read_commands WHERE id=?').get(id);if(!command)fail(404,'read_command_not_found');return send(command);}if(method==='GET')return paged('read_commands','',[],'created_at DESC,id DESC');
     if(method==='POST'&&['group_requests','community_subgroups'].includes(b.kind)){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||!groupJid(b.target))fail(400,'invalid_group_read');if(!database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind IN('group','community') AND resource_id=?").get(b.target,b.target))fail(404,'unknown_target');if(b.kind==='community_subgroups'&&!database.prepare("SELECT 1 FROM snapshots WHERE resource_id=? AND (kind='community' OR (kind='group' AND json_extract(payload,'$.isCommunity')=1))").get(b.target))fail(404,'unknown_community');const pending=database.prepare("SELECT * FROM read_commands WHERE kind=? AND target=? AND status IN('pending','running')").get(b.kind,b.target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare('INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,?,?,?,?)').run(id,b.kind,b.target,date,date);audit('sync.'+b.kind,actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='group_invite'){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||!groupJid(b.target))fail(400,'invalid_group_invite_target');if(!database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind IN('group','community') AND resource_id=?").get(b.target,b.target))fail(404,'unknown_target');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='group_invite' AND target=? AND status IN('pending','running')").get(b.target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'group_invite',?,?,?)").run(id,b.target,date,date);audit('sync.group_invite',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
      if(method==='POST'&&b.kind==='order_details'){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||typeof b.target!=='string'||!/^[-\w.]{1,200}$/.test(b.target))fail(400,'invalid_order_message');const message=database.prepare("SELECT wa_message_id FROM messages WHERE id=? AND type='order'").get(b.target);if(!message?.wa_message_id)fail(404,'order_message_not_found');const stored=database.prepare("SELECT payload FROM snapshots WHERE kind='message' AND resource_id=?").get(message.wa_message_id),data=stored?JSON.parse(stored.payload):{};if(data.revoked||data.edited||data.deleted)fail(409,'order_message_changed');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='order_details' AND target=? AND status IN('pending','running')").get(message.wa_message_id);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'order_details',?,?,?)").run(id,message.wa_message_id,date,date);audit('sync.order_details',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
      if(method==='POST'&&b.kind==='contact_check'){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||typeof b.target!=='string'||b.target.length>100)fail(400,'invalid_contact_id');const contact=database.prepare('SELECT id,phone_e164 FROM contacts WHERE id=?').get(b.target);if(!contact||!contact.phone_e164)fail(404,'known_contact_phone_required');if(!/^\+[1-9]\d{6,14}$/.test(contact.phone_e164))fail(409,'invalid_stored_phone');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='contact_check' AND target=? AND status IN('pending','running')").get(contact.id);if(pending)return send(pending,202);const prior=database.prepare("SELECT payload FROM snapshots WHERE kind='contact_check' AND resource_id=?").get(contact.id);let checkedAt;try{checkedAt=JSON.parse(prior?.payload||'{}').checked_at;}catch{}if(checkedAt&&Date.now()-Date.parse(checkedAt)<900000)fail(429,'contact_check_cooldown');const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'contact_check',?,?,?)").run(id,contact.id,date,date);audit('sync.contact_check',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='contact_catalog'){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||typeof b.target!=='string'||!/^[1-9]\d{6,14}@s\.whatsapp\.net$/.test(b.target))fail(400,'invalid_contact_catalog_target');if(!database.prepare('SELECT 1 FROM contacts WHERE wa_jid=? OR phone_e164=?').get(b.target,'+'+b.target.split('@')[0]))fail(404,'unknown_target');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='contact_catalog' AND target=? AND status IN('pending','running')").get(b.target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'contact_catalog',?,?,?)").run(id,b.target,date,date);audit('sync.contact_catalog',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='bot_list'){if(Object.keys(b).some(k=>k!=='kind'))fail(400,'unexpected_bot_list_parameter');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='bot_list' AND target IS NULL AND status IN('pending','running')").get();if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'bot_list',NULL,?,?)").run(id,date,date);audit('sync.bot_list',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='newsletter_messages'){if(Object.keys(b).some(k=>!['kind','target'].includes(k))||typeof b.target!=='string'||b.target.length>150||!/^\d{1,40}@newsletter$/.test(b.target))fail(400,'invalid_newsletter_read');if(!database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind='newsletter' AND resource_id=?").get(b.target,b.target))fail(404,'unknown_target');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='newsletter_messages' AND target=? AND status IN('pending','running')").get(b.target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'newsletter_messages',?,?,?)").run(id,b.target,date,date);audit('sync.newsletter_messages',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='account_limits'){if(Object.keys(b).some(k=>k!=='kind'))fail(400,'unexpected_account_limits_parameter');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='account_limits' AND target IS NULL AND status IN('pending','running')").get();if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'account_limits',NULL,?,?)").run(id,date,date);audit('sync.account_limits',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='avatar'){if(Object.keys(b).some(k=>!['kind','target'].includes(k)))fail(400,'invalid_avatar_request');const target=knownAvatarTarget(b.target,actor.admin);const pending=database.prepare("SELECT * FROM read_commands WHERE kind='avatar' AND target=? AND status IN('pending','running')").get(target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'avatar',?,?,?)").run(id,target,date,date);audit('sync.avatar',actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
     if(method==='POST'&&b.kind==='history'){
      if(Object.keys(b).some(k=>!['kind','target'].includes(k)))fail(400,'history_fixed_limit');if(typeof b.target!=='string'||b.target.length>150||! /^[0-9-]+@(s\.whatsapp\.net|lid|g\.us)$/.test(b.target))fail(400,'invalid_history_target');const conversation=database.prepare('SELECT * FROM conversations WHERE wa_chat_id=?').get(b.target);if(!conversation)fail(404,'unknown_target');const anchor=database.prepare("SELECT * FROM messages WHERE conversation_id=? AND wa_message_id IS NOT NULL AND length(wa_message_id)>0 AND direction IN('in','out') ORDER BY created_at ASC,id ASC LIMIT 1").get(conversation.id);if(!anchor||!Number.isFinite(Date.parse(anchor.created_at)))fail(409,'history_anchor_unavailable');const pending=database.prepare("SELECT * FROM read_commands WHERE kind='history' AND target=? AND status IN('pending','running')").get(b.target);if(pending)return send({...pending,requested_count:LOCAL_LIMITS.history_request_messages,history_complete:false},202);const id=randomUUID(),date=now();database.prepare("INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,'history',?,?,?)").run(id,b.target,date,date);audit('sync.history',actor.id,id);return send({...database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),requested_count:LOCAL_LIMITS.history_request_messages,history_complete:false},202);
     }
     if(method==='POST'){if(!['account','groups','group','contact_profile','all','catalog','collections','blocklist','communities','community','newsletter','newsletters'].includes(b.kind))fail(400,'invalid_read_command');const target=b.target??null;if(['group','community','newsletter','contact_profile'].includes(b.kind)){if(typeof target!=='string'||target.length>150)fail(400,'target_required');let exists;if(['group','community'].includes(b.kind)){if(!/^[0-9-]+@g\.us$/.test(target))fail(400,'invalid_group_jid');exists=database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind IN('group','community') AND resource_id=?").get(target,target);}else if(b.kind==='newsletter'){if(!/^\d+@newsletter$/.test(target))fail(400,'invalid_newsletter_jid');exists=database.prepare("SELECT 1 FROM conversations WHERE wa_chat_id=? UNION SELECT 1 FROM snapshots WHERE kind='newsletter' AND resource_id=?").get(target,target);}else{if(!/^\d+@(s\.whatsapp\.net|lid)$/.test(target))fail(400,'invalid_contact_jid');exists=database.prepare('SELECT 1 FROM contacts WHERE wa_jid=?').get(target);}if(!exists)fail(404,'unknown_target');}else if(target!==null)fail(400,'unexpected_target');const pending=database.prepare("SELECT * FROM read_commands WHERE kind=? AND target IS ? AND status IN('pending','running')").get(b.kind,target);if(pending)return send(pending,202);const id=randomUUID(),date=now();database.prepare('INSERT INTO read_commands(id,kind,target,created_at,updated_at) VALUES(?,?,?,?,?)').run(id,b.kind,target,date,date);audit('sync.'+b.kind,actor.id,id);return send(database.prepare('SELECT * FROM read_commands WHERE id=?').get(id),202);}
    }
    if(resource==='settings'){
     auth('read',true);const read=()=>{const row=database.prepare("SELECT value FROM settings WHERE key='dashboard_preferences'").get();return {poll_seconds:10,default_page_size:50,theme:'system',...(row?JSON.parse(row.value):{}),scheduled_reads:getScheduledReadStatus(database),outbound_enabled:process.env.WIS_OUTBOUND_ENABLED==='true',webhooks_enabled:process.env.WIS_WEBHOOKS_ENABLED==='true',storage:'SQLite local',history_complete:false};};
     if(method==='GET')return send(read());if(method==='PATCH'){const allowed=['poll_seconds','default_page_size','theme','scheduled_reads_enabled','scheduled_reads_interval_minutes'];if(Object.keys(b).some(k=>!allowed.includes(k)))fail(400,'local_preferences_only');if(b.poll_seconds!==undefined&&(!Number.isInteger(b.poll_seconds)||b.poll_seconds<5||b.poll_seconds>60))fail(400,'invalid_poll_seconds');if(b.default_page_size!==undefined&&![25,50,100,200].includes(b.default_page_size))fail(400,'invalid_page_size');if(b.theme!==undefined&&!['light','dark','system'].includes(b.theme))fail(400,'invalid_theme');if(b.scheduled_reads_enabled!==undefined&&typeof b.scheduled_reads_enabled!=='boolean')fail(400,'invalid_scheduled_reads_enabled');if(b.scheduled_reads_interval_minutes!==undefined&&![15,30,60,120].includes(b.scheduled_reads_interval_minutes))fail(400,'invalid_scheduled_reads_interval');const old=read();if(['poll_seconds','default_page_size','theme'].some(k=>b[k]!==undefined))database.prepare("INSERT INTO settings(key,value) VALUES('dashboard_preferences',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify({poll_seconds:b.poll_seconds??old.poll_seconds,default_page_size:b.default_page_size??old.default_page_size,theme:b.theme??old.theme}));if(b.scheduled_reads_enabled!==undefined||b.scheduled_reads_interval_minutes!==undefined){const scheduled=getScheduledReadSettings(database);updateScheduledReadSettings(database,{enabled:b.scheduled_reads_enabled??scheduled.enabled,interval_minutes:b.scheduled_reads_interval_minutes??scheduled.interval_minutes});}audit('settings.preferences',actor.id);return send(read());}
    }
    if(resource==='media'&&method==='GET'){
     const name=url.searchParams.get('path');
     if(!url.searchParams.has('path')){
      const {limit,offset,q}=page();const from="(SELECT media_path AS path,created_at,1 AS message_count,type FROM messages WHERE media_path IS NOT NULL UNION ALL SELECT resource_id AS path,created_at,0 AS message_count,NULL AS type FROM audit WHERE action='media.uploaded' AND resource_id IS NOT NULL)";const where=q?" WHERE path LIKE ? ESCAPE '\\'":'';const args=q?[search()]:[];const total=database.prepare('SELECT count(DISTINCT path) AS n FROM '+from+where).get(...args).n;const rows=database.prepare('SELECT path,min(created_at) AS created_at,sum(message_count) AS message_count,max(type) AS type FROM '+from+where+' GROUP BY path ORDER BY created_at DESC,path LIMIT ? OFFSET ?').all(...args,limit,offset);
      let mediaDir=null;try{mediaDir=await realpath(resolve(directory,'media'));}catch{}const data=await Promise.all(rows.map(async row=>{let size=null,available=false;if(mediaDir&&validMediaName(row.path))try{const file=await realpath(resolve(mediaDir,row.path));if(file.startsWith(mediaDir+'/')||file.startsWith(mediaDir+'\\')){const info=await stat(file);available=info.isFile()&&info.size<=LOCAL_LIMITS.media_read_bytes;if(available)size=info.size;}}catch{}return {...row,size,available,mime_type:mediaTypes[extname(row.path).toLowerCase()]??'application/octet-stream',media_url:available?'/api/v1/media?path='+encodeURIComponent(row.path):null};}));return send(data,200,{total,limit,offset,has_more:offset+data.length<total});
     }
     if(!validMediaName(name))fail(400,'invalid_media_path');if(!database.prepare("SELECT 1 FROM messages WHERE media_path=? UNION SELECT 1 FROM audit WHERE action='media.uploaded' AND resource_id=?").get(name,name))fail(404,'media_not_registered');const dir=await realpath(resolve(directory,'media'));const file=await realpath(resolve(dir,name));if(!file.startsWith(dir+'/')&&!file.startsWith(dir+'\\'))fail(403,'media_outside_storage');const info=await stat(file);if(!info.isFile()||info.size>LOCAL_LIMITS.media_read_bytes)fail(413,'invalid_media_size');res.writeHead(200,{'Content-Type':mediaTypes[extname(file).toLowerCase()]??'application/octet-stream','Content-Disposition':'inline; filename="'+name+'"','Cache-Control':'private, no-store'});return res.end(await readFile(file));
    }
    if(resource==='connections'&&method==='GET')return send(database.prepare('SELECT * FROM connections').all().map(cleanConnection));
    if(resource==='capability-fields'&&method==='GET'){auth('read');const query=url.searchParams.get('q');if(query!==null&&(query.trim().length<2||query.trim().length>100))fail(400,'invalid_query');const limit=Math.min(500,Math.max(1,Math.floor(Number(url.searchParams.get('limit'))||100)));const rawOffset=Number(url.searchParams.get('offset')||0);if(!Number.isSafeInteger(rawOffset)||rawOffset<0||rawOffset>100000)fail(400,'invalid_offset');return send(query===null?await listCapabilityFields(root,limit,rawOffset):await searchCapabilityFields(root,query,limit,rawOffset));} if(resource==='capabilities'&&method==='GET')return send(JSON.parse(await readFile(resolve(root,'public/whapi-capabilities.json'),'utf8')));
    if(resource==='reference-fields'&&method==='GET'){referenceFields??=readFile(resolve(root,'public/whapi-fields.json'),'utf8').then(JSON.parse).catch(error=>{referenceFields=null;throw error;});const reference=await referenceFields;const id=url.searchParams.get('id');if(id){const method=reference.methods.find(x=>x.id===id);if(!method)fail(404,'reference_method_not_found');return send(method);}return send({captured_at:reference.captured_at,methods:reference.methods.map(x=>({id:x.id,version:x.version,operations:x.operations.map(o=>({method:o.method,path:o.path,tags:o.tags,field_count:(o.request_fields?.length??0)+Object.values(o.response_fields??{}).reduce((n,fields)=>n+fields.length,0)}))}))});}
    if(resource==='openapi'&&method==='GET'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(await readFile(resolve(root,'docs/api.openapi.json')));}
    if(resource==='contacts'){
     if(method==='GET'&&url.searchParams.has('id')){const id=url.searchParams.get('id');if(id.length>200)fail(400,'invalid_contact_id');const contact=database.prepare('SELECT * FROM contacts WHERE id=?').get(id);if(!contact)fail(404,'contact_not_found');const jids=[...new Set([contact.wa_jid,contact.phone_e164?contact.phone_e164.slice(1)+'@s.whatsapp.net':null].filter(Boolean))];const snapshotRows=jids.length?database.prepare("SELECT * FROM snapshots WHERE kind IN('contact','presence','chat') AND resource_id IN("+jids.map(()=>'?').join(',')+") ORDER BY updated_at DESC").all(...jids):[];const snapshots=snapshotRows.map(row=>({kind:row.kind,resource_id:row.resource_id,...parseSnapshot(row)}));const conversations=database.prepare('SELECT * FROM conversations WHERE contact_id=?'+(jids.length?' OR wa_chat_id IN('+jids.map(()=>'?').join(',')+')':'')+' ORDER BY last_message_at DESC,id DESC').all(contact.id,...jids).map(c=>({...c,relation_origins:[...(c.contact_id===contact.id?['stored_contact_id']:[]),...(c.wa_chat_id===contact.wa_jid?['exact_wa_jid']:[]),...(contact.phone_e164&&c.wa_chat_id===contact.phone_e164.slice(1)+'@s.whatsapp.net'?['exact_phone_jid']:[])]}));return send({contact,avatar:avatarForTarget(contact.wa_jid??(contact.phone_e164?contact.phone_e164.slice(1)+'@s.whatsapp.net':null)),profile:snapshots.find(row=>row.kind==='contact')??null,presence:snapshots.find(row=>row.kind==='presence')??null,conversations,snapshots});}
     if(method==='GET'){const q=page().q;return paged('contacts',q?"(display_name LIKE ? ESCAPE '\\' OR phone_e164 LIKE ? ESCAPE '\\' OR wa_jid LIKE ? ESCAPE '\\')":'',q?[search(),search(),search()]:[],'created_at DESC,id DESC');}
     auth('contacts:write');if(!['POST','PATCH'].includes(method))fail(405,'method_not_allowed');
     const old=method==='PATCH'?database.prepare('SELECT * FROM contacts WHERE id=?').get(String(b.id)):null;if(method==='PATCH'&&!old)fail(404,'not_found');
     const values={...old,...b};if(!phone(values.phone_e164))fail(400,'invalid_e164');
     for(const k of ['consent_at','opted_out_at'])if(values[k]&&(typeof values[k]!=='string'||!Number.isFinite(Date.parse(values[k]))||Date.parse(values[k])>Date.now()+60000))fail(400,'invalid_date');
     if(old?.opted_out_at&&'opted_out_at'in b&&b.opted_out_at!==old.opted_out_at)fail(409,'optout_removal_requires_review');
     if(values.consent_at&&(typeof values.consent_source!=='string'||!values.consent_source.trim()||typeof values.consent_scope!=='string'||!values.consent_scope.trim()))fail(400,'consent_evidence_required');
     for(const k of ['display_name','consent_source','consent_scope'])if(values[k]!=null&&(typeof values[k]!=='string'||values[k].length>1000))fail(400,'invalid_contact');
     const id=old?.id??randomUUID();database.prepare('INSERT INTO contacts(id,phone_e164,display_name,consent_at,consent_source,consent_scope,opted_out_at,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET phone_e164=excluded.phone_e164,display_name=excluded.display_name,consent_at=excluded.consent_at,consent_source=excluded.consent_source,consent_scope=excluded.consent_scope,opted_out_at=excluded.opted_out_at').run(id,values.phone_e164,values.display_name??'',values.consent_at??null,values.consent_source??null,values.consent_scope??null,values.opted_out_at??null,old?.created_at??now());audit('contact.'+method,actor.id,id);return send(database.prepare('SELECT * FROM contacts WHERE id=?').get(id),method==='POST'?201:200);
    }
    if(resource==='conversations'&&method==='GET'){if(url.searchParams.has('id')){const id=url.searchParams.get('id');if(!id||id.length>200)fail(400,'invalid_conversation_id');const conversation=database.prepare('SELECT * FROM conversations WHERE id=?').get(id);if(!conversation)fail(404,'conversation_not_found');const contact=conversation.contact_id?database.prepare('SELECT * FROM contacts WHERE id=?').get(conversation.contact_id)??null:null;const snapshots=database.prepare("SELECT * FROM snapshots WHERE kind IN('chat','group','presence') AND resource_id=? ORDER BY kind").all(conversation.wa_chat_id).map(conversationSnapshot);const counts=database.prepare("SELECT count(*) AS total,coalesce(sum(direction='in'),0) AS inbound,coalesce(sum(direction='out'),0) AS outbound FROM messages WHERE conversation_id=?").get(id);const by_status=Object.fromEntries(database.prepare('SELECT delivery_status,count(*) AS count FROM messages WHERE conversation_id=? GROUP BY delivery_status').all(id).map(row=>[row.delivery_status,row.count]));return send({conversation,contact,contact_relation:contact?'stored_contact_id':null,snapshots,history:historyFor(conversation),message_counts:{total:counts.total,in:counts.inbound,out:counts.outbound,by_status},history_complete:false});}const kind=url.searchParams.get('kind')??'all';if(!['all','direct','group'].includes(kind))fail(400,'invalid_chat_kind');const clauses=[],args=[];if(kind!=='all')clauses.push(kind==='group'?"c.wa_chat_id LIKE '%@g.us'":"c.wa_chat_id NOT LIKE '%@g.us'");if(page().q){clauses.push("(c.display_name LIKE ? ESCAPE '\\' OR c.title LIKE ? ESCAPE '\\' OR c.wa_chat_id LIKE ? ESCAPE '\\' OR p.display_name LIKE ? ESCAPE '\\' OR p.phone_e164 LIKE ? ESCAPE '\\')");args.push(...Array(5).fill(search()));}return paged('conversations c LEFT JOIN contacts p ON p.id=c.contact_id',clauses.join(' AND '),args,'c.last_message_at DESC,c.id DESC','c.*,p.display_name AS contact_name,p.phone_e164 AS phone_e164');}
    if(resource==='messages'&&method==='GET'){
      const id=url.searchParams.get('id');if(id){if(id.length>200)fail(400,'invalid_message_id');const message=database.prepare('SELECT * FROM messages WHERE id=?').get(id);if(!message)fail(404,'message_not_found');const conversation=database.prepare('SELECT * FROM conversations WHERE id=?').get(message.conversation_id),contact=conversation?.contact_id?database.prepare('SELECT * FROM contacts WHERE id=?').get(conversation.contact_id):null;const snapshot=message.wa_message_id?parseSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind='message' AND resource_id=?").get(message.wa_message_id)):null,revoked=Boolean(snapshot?.data?.revoked||snapshot?.data?.edited||snapshot?.data?.deleted),orderDetails=!revoked&&message.type==='order'&&message.wa_message_id?parseSnapshot(database.prepare("SELECT * FROM snapshots WHERE kind='order_details' AND resource_id=?").get(message.wa_message_id)):null;const events=message.wa_message_id?database.prepare("SELECT * FROM events WHERE kind='messages.reaction' AND resource_id=? ORDER BY created_at DESC LIMIT 100").all(message.wa_message_id).map(row=>({id:row.id,data:JSON.parse(row.payload),created_at:row.created_at})):[];const reactionMessages=message.wa_message_id?database.prepare("SELECT * FROM snapshots WHERE kind='message' AND json_extract(payload,'$.type')='reaction' AND json_extract(payload,'$.details.key.id')=? ORDER BY updated_at DESC LIMIT 100").all(message.wa_message_id).map(row=>({resource_id:row.resource_id,...parseSnapshot(row)})):[];const related=kind=>message.wa_message_id?database.prepare("SELECT * FROM snapshots WHERE kind=? AND json_extract(payload,'$.message_id')=? ORDER BY updated_at DESC LIMIT 100").all(kind,message.wa_message_id).map(row=>({resource_id:row.resource_id,...parseSnapshot(row)})):[];return send({message:{...message,media_url:message.media_path?'/api/v1/media?path='+encodeURIComponent(message.media_path):null},conversation:conversation??null,contact:contact??null,snapshot,details:snapshot?.data?.details??null,order_details:orderDetails,quote:snapshot?.data?.quote??null,mentions:snapshot?.data?.mentions??[],reactions:{events,messages:reactionMessages,snapshots:related('reaction'),complete:false},receipts:related('receipt'),history:conversation?historyFor(conversation):{complete:false}});}
     const clauses=[],args=[];if(url.searchParams.has('type')){const type=url.searchParams.get('type');if(!['text','image','video','audio','document','sticker','location','contact','poll','reaction','button_reply','list_reply','poll_update','unsupported','unknown','product','order','event','event_response'].includes(type))fail(400,'invalid_message_type');clauses.push('type=?');args.push(type);}if(url.searchParams.has('conversation_id')){clauses.push('conversation_id=?');args.push(url.searchParams.get('conversation_id'));}if(page().q){clauses.push("body LIKE ? ESCAPE '\\'");args.push(search());}return paged('messages',clauses.join(' AND '),args,'created_at DESC,id DESC','*',row=>({...row,media_url:row.media_path?'/api/v1/media?path='+encodeURIComponent(row.media_path):null}));}
    if(resource==='operations'&&method==='GET'){const id=url.searchParams.get('id');return paged('operations o LEFT JOIN messages m ON m.id=o.message_id',id?'o.id=?':'',id?[id]:[],'o.created_at DESC,o.id DESC','o.*,m.delivery_status',x=>({...x,message:{delivery_status:x.delivery_status}}));}
    if(resource==='messages'&&method==='POST'){
     auth('send');const key=req.headers['idempotency-key'];if(typeof key!=='string'||! /^[\x21-\x7e]{1,128}$/.test(key))fail(400,'idempotency_key_required');if(!phone(b.to))fail(400,'invalid_e164');if(!['text','image','audio','document'].includes(b.type??'text'))fail(422,'unsupported_type');if((b.type??'text')==='text'&&(typeof b.body!=='string'||!b.body.trim()||b.body.length>LOCAL_LIMITS.text_max_chars))fail(400,'invalid_body');
     const payload={to:b.to,type:b.type??'text',body:b.body??null,media_path:b.media_path??null};if(payload.body!==null&&(typeof payload.body!=='string'||payload.body.length>LOCAL_LIMITS.text_max_chars))fail(400,'invalid_body');const fingerprint=hash(JSON.stringify(payload));
     const previous=database.prepare('SELECT * FROM operations WHERE idempotency_key=?').get(key);if(previous){if(previous.request_hash!==fingerprint)fail(409,'idempotency_conflict');return send(previous);}
     if(process.env.WIS_OUTBOUND_ENABLED!=='true')fail(409,'outbound_disabled');
     const c=database.prepare('SELECT * FROM contacts WHERE phone_e164=?').get(b.to);if(!eligible(c))fail(403,c?.opted_out_at?'contact_opted_out':'contact_consent_required');if(b.purpose&&b.purpose!=='transactional')fail(409,'campaigns_disabled');
     if(payload.type!=='text'){if(typeof payload.media_path!=='string'||! /^[0-9a-f-]{36}\.(jpg|png|webp|ogg|mp3|m4a|pdf)$/.test(payload.media_path))fail(400,'invalid_media_path');const ext=extname(payload.media_path);if(payload.type==='image'&&!['.jpg','.png','.webp'].includes(ext)||payload.type==='audio'&&!['.ogg','.mp3','.m4a'].includes(ext)||payload.type==='document'&&ext!=='.pdf')fail(400,'media_type_mismatch');await readFile(resolve(directory,'media',payload.media_path));}
     // File validation yields to other requests; recheck before the synchronous transaction.
     const replay=database.prepare('SELECT * FROM operations WHERE idempotency_key=?').get(key);if(replay){if(replay.request_hash!==fingerprint)fail(409,'idempotency_conflict');return send(replay);}
     if(!eligible(database.prepare('SELECT * FROM contacts WHERE id=?').get(c.id)))fail(403,'contact_consent_required');
     const operation=transaction(database,()=>{const jid=c.wa_jid??b.to.slice(1)+'@s.whatsapp.net';let conversation=database.prepare('SELECT id FROM conversations WHERE wa_chat_id=?').get(jid);if(!conversation){conversation={id:randomUUID()};database.prepare('INSERT INTO conversations(id,contact_id,wa_chat_id,display_name) VALUES(?,?,?,?)').run(conversation.id,c.id,jid,c.display_name);}const message=randomUUID(),id=randomUUID(),date=now();database.prepare('INSERT INTO messages(id,conversation_id,direction,type,body,media_path,created_at) VALUES(?,?,?,?,?,?,?)').run(message,conversation.id,'out',payload.type,payload.body,payload.media_path,date);database.prepare('INSERT INTO operations(id,to_e164,type,body,media_path,message_id,idempotency_key,request_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,b.to,payload.type,payload.body,payload.media_path,message,key,fingerprint,date,date);return database.prepare('SELECT * FROM operations WHERE id=?').get(id);});audit('message.queued',actor.id,operation.id);return send({...operation,outbound_enabled:false},202);
    }
    if(resource==='media'&&method==='POST'){auth('send');const extensions={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','audio/ogg':'ogg','audio/mpeg':'mp3','audio/mp4':'m4a','application/pdf':'pdf'};const ext=extensions[b.mime_type];if(!ext||typeof b.base64!=='string'||b.base64.length>LOCAL_LIMITS.media_base64_max_chars||! /^[A-Za-z0-9+/]*={0,2}$/.test(b.base64))fail(400,'invalid_media');const data=Buffer.from(b.base64,'base64');if(!data.length||data.length>LOCAL_LIMITS.media_upload_bytes)fail(413,'invalid_media_size');if(!mediaMatches(data,b.mime_type))fail(415,'media_signature_mismatch');const filename=randomUUID()+'.'+ext;await mkdir(resolve(directory,'media'),{recursive:true,mode:0o700});await writeFile(resolve(directory,'media',filename),data,{flag:'wx',mode:0o600});audit('media.uploaded',actor.id,filename);return send({media_path:filename,mime_type:b.mime_type,size:data.length},201);}
    if(resource==='tokens'){
     auth('read',true);if(method==='GET')return send(database.prepare('SELECT id,name,scopes,created_at,revoked_at FROM tokens').all().map(t=>({...t,scopes:JSON.parse(t.scopes)})));
     if(method==='DELETE'){database.prepare('UPDATE tokens SET revoked_at=? WHERE id=?').run(now(),url.searchParams.get('id'));return send({revoked:true});}
     if(method==='POST'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>80||!Array.isArray(b.scopes)||!b.scopes.length||b.scopes.some(x=>!scopes.includes(x)))fail(400,'invalid_token');const id=randomUUID(),token='wis_'+randomBytes(32).toString('base64url');database.prepare('INSERT INTO tokens(id,name,token_hash,scopes,created_at) VALUES(?,?,?,?,?)').run(id,b.name,hash(token),JSON.stringify(b.scopes),now());audit('token.created',actor.id,id);return send({id,token},201);}
    }
    if(resource==='webhooks'){
     auth('webhooks:write');if(method==='GET')return send(database.prepare("SELECT w.id,w.url,w.enabled,w.created_at,count(d.id) AS total,sum(CASE WHEN d.status='pending' THEN 1 ELSE 0 END) AS pending,sum(CASE WHEN d.status='sending' THEN 1 ELSE 0 END) AS sending,sum(CASE WHEN d.status='delivered' THEN 1 ELSE 0 END) AS delivered,sum(CASE WHEN d.status='failed' THEN 1 ELSE 0 END) AS failed,max(d.created_at) AS last_delivery_at FROM webhooks w LEFT JOIN webhook_deliveries d ON d.webhook_id=w.id GROUP BY w.id ORDER BY w.created_at DESC,w.id").all().map(row=>({id:row.id,url:row.url,enabled:Boolean(row.enabled),created_at:row.created_at,last_delivery_at:row.last_delivery_at,delivery_counts:{total:row.total,pending:row.pending,sending:row.sending,delivered:row.delivered,failed:row.failed},dispatcher_enabled:process.env.WIS_WEBHOOKS_ENABLED==='true',activation_requires_approval:true})));
     if(method==='DELETE'){const id=url.searchParams.get('id');if(!id||id.length>200)fail(400,'webhook_id_required');const changed=database.prepare('UPDATE webhooks SET enabled=0 WHERE id=?').run(id);if(!changed.changes)fail(404,'webhook_not_found');audit('webhook.disabled',actor.id,id);return send({disabled:true,history_preserved:true});}
     if(method==='PATCH'||method==='PUT'||method==='POST'&&b.enabled)fail(409,'webhook_activation_requires_approval');
     if(method==='POST'){let target;try{target=new URL(b.url);}catch{fail(400,'invalid_url');}if(target.protocol!=='https:'||target.username||target.password||target.port&&target.port!=='443')fail(400,'https_required');const id=randomUUID(),secret=randomBytes(32).toString('hex');database.prepare('INSERT INTO webhooks(id,url,secret,created_at) VALUES(?,?,?,?)').run(id,target.href,secret,now());return send({id,url:target.href,enabled:false,secret},201);}
    }
    if(resource==='webhook-deliveries'&&method==='GET'){
     auth('webhooks:write');const fields='id,webhook_id,event_id,event_type,status,attempts,available_at,last_error,created_at',id=url.searchParams.get('id');
     if(id){auth(null,true);if(id.length>200)fail(400,'invalid_delivery_id');const row=database.prepare('SELECT '+fields+',payload FROM webhook_deliveries WHERE id=?').get(id);if(!row)fail(404,'delivery_not_found');let payload;try{payload=safeWebhookPayload(JSON.parse(row.payload));}catch{payload=null;}return send({...row,last_error:deliveryError(row.last_error),payload});}
     const status=url.searchParams.get('status'),webhook=url.searchParams.get('webhook_id'),clauses=[],args=[];if(status){if(!['pending','sending','delivered','failed'].includes(status))fail(400,'invalid_delivery_status');clauses.push('status=?');args.push(status);}if(webhook){if(webhook.length>200)fail(400,'invalid_webhook_id');clauses.push('webhook_id=?');args.push(webhook);}return paged('webhook_deliveries',clauses.join(' AND '),args,'created_at DESC,id DESC',fields,row=>({...row,last_error:deliveryError(row.last_error)}));
    }
    if(resource==='webhook-events'&&method==='GET'){
     auth('webhooks:write');return send({supported:[{name:'message.created',source:'SQLite trigger message_created',when:'Local message row inserted',payload_fields:['id','conversation_id','direction','type','body','delivery_status']},{name:'message.updated',source:'SQLite trigger message_updated',when:'Local delivery_status changed',payload_fields:['id','delivery_status']},{name:'operation.updated',source:'SQLite trigger operation_updated',when:'Local outbound queue status changed',payload_fields:['id','status','wa_message_id']}],delivery:{dispatcher_enabled:process.env.WIS_WEBHOOKS_ENABLED==='true',activation_requires_approval:true,new_webhooks_enabled:false,delivery_semantics:'at_least_once',deduplicate_by:'X-WIS-Event-ID',signature:{algorithm:'HMAC-SHA256',input:'X-WIS-Timestamp + dot + raw request body',header:'X-WIS-Signature',format:'sha256=hex',timestamp_header:'X-WIS-Timestamp',event_id_header:'X-WIS-Event-ID'},automatic_live_tests:false,retry:{max_attempts:5,includes_initial_attempt:true,max_retries:4,backoff_seconds:[2,4,8,16],lease_seconds:60,dns_timeout_seconds:5,request_timeout_seconds:15},destination:{https_only:true,port:443,allowlist_required:true,public_ipv4_only:true,redirects:false}},reference:{source:'https://whapi.readme.io/reference/getallowedevents',version:'1.8.7',types:['messages','statuses','chats','contacts','groups','presences','calls','channel','users','labels','service'],methods:['post','put','delete','patch'],wire_compatible:false,note:'Reference categories are not implemented local event names. Only supported[] is emitted.'}});
    }
    if(resource==='campaigns'){
     auth('read',true);const parse=c=>({...c,contact_ids:JSON.parse(c.contact_ids),execution_enabled:false});if(method==='GET')return send(database.prepare('SELECT * FROM campaigns ORDER BY created_at DESC').all().map(parse));
     if(method==='POST'){if(typeof b.name!=='string'||!b.name.trim()||typeof b.body!=='string'||!b.body.trim()||!Array.isArray(b.contact_ids)||!b.contact_ids.length||b.contact_ids.length>1000||!Number.isInteger(b.daily_limit)||b.daily_limit<1||b.daily_limit>10000||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.window_start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.window_end)||b.window_start>=b.window_end)fail(400,'invalid_campaign');const ids=[...new Set(b.contact_ids)];if(ids.some(id=>!database.prepare('SELECT id FROM contacts WHERE id=?').get(id)))fail(400,'unknown_recipients');const id=randomUUID();database.prepare('INSERT INTO campaigns(id,name,body,contact_ids,daily_limit,window_start,window_end,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,b.name,b.body,JSON.stringify(ids),b.daily_limit,b.window_start,b.window_end,now());return send(parse(database.prepare('SELECT * FROM campaigns WHERE id=?').get(id)),201);}
     if(method==='PATCH'){const campaign=database.prepare('SELECT * FROM campaigns WHERE id=?').get(String(b.id));if(!campaign)fail(404,'not_found');const contacts=JSON.parse(campaign.contact_ids).map(id=>database.prepare('SELECT * FROM contacts WHERE id=?').get(id));const allowed=contacts.filter(eligible);if(b.action==='preview')return send({campaign:parse(campaign),eligible:allowed,excluded:contacts.filter(c=>!eligible(c)),execution_enabled:false});if(!['approve','pause'].includes(b.action))fail(400,'invalid_action');if(b.action==='approve'&&allowed.length!==contacts.length)fail(409,'recipient_consent_required');database.prepare('UPDATE campaigns SET status=?,approved_at=? WHERE id=?').run(b.action==='approve'?'approved':'paused',b.action==='approve'?now():campaign.approved_at,campaign.id);audit('campaign.'+b.action,actor.id,campaign.id);return send({campaign:parse(database.prepare('SELECT * FROM campaigns WHERE id=?').get(campaign.id)),execution_enabled:false});}
    }
    fail(404,'not_found');
   }
   if(path.startsWith('/api/'))fail(404,'not_found');
   if(method!=='GET')fail(405,'method_not_allowed');const relative=path==='/'?'index.html':decodeURIComponent(path.slice(1));if(relative.includes('..')||relative.includes('\\')||relative.startsWith('.'))fail(404,'not_found');const file=resolve(root,'local/public',relative);if(!file.startsWith(resolve(root,'local/public')+'/')&&!file.startsWith(resolve(root,'local/public')+'\\'))fail(404,'not_found');const data=await readFile(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(file)]??'application/octet-stream','Cache-Control':'no-store'});res.end(data);
  }catch(error){if(res.headersSent)return res.end();const status=error.status??(error.code==='ENOENT'?404:error.code?.startsWith('SQLITE_CONSTRAINT')?409:500);res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({error:error.status?error.message:status===404?'not_found':status===409?'conflict':'internal_error'}));}
 });
 server.once('close',()=>lookupGroupInviteInfo.close?.());
 const scheduledReadTimer=setInterval(()=>{try{const connection=database.prepare("SELECT * FROM connections WHERE id='wis-5679'").get();queueScheduledReadIfDue(database,{connected:connection?.status==='connected'&&cleanConnection(connection).identity_verified});}catch{console.error('scheduled_read_scheduler_failed');}},options.scheduledReadIntervalMs??30_000);
 scheduledReadTimer.unref?.();
 server.once('close',()=>clearInterval(scheduledReadTimer));
 return server;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){if(!db.prepare("SELECT value FROM settings WHERE key='admin_password'").get())throw Error('Run npm run setup before starting the server.');const port=Number(process.env.WIS_LOCAL_PORT??3010);const server=makeServer();server.listen(port,'127.0.0.1',()=>{console.log('WIS local ready at http://127.0.0.1:'+port);if(process.send)process.send({type:'wis.ready',generation:process.env.WIS_RUNTIME_GENERATION});});process.on('message',message=>{if(message?.type==='wis.shutdown')server.close(()=>process.exit(0));});}
