import test from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync,randomBytes} from 'node:crypto';
process.env.WIS_DB_PATH=':memory:';
const {openDatabase}=await import('../../local/db.mjs');
const {makeServer}=await import('../../local/server.mjs');
test('provider bot catalog is sanitized and read-only with manual administrative refresh',async()=>{
 const db=openDatabase(':memory:'),password=randomBytes(20).toString('hex'),salt='bots-test';db.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));const server=makeServer(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';const req=async(path,method='GET',body,token)=>{const r=await fetch(base+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie,...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json(),headers:r.headers};};
 try{assert.equal((await req('/api/v1/bots')).status,401);const login=await req('/api/login','POST',{password});cookie=login.headers.get('set-cookie').split(';')[0];const reader=(await req('/api/v1/tokens','POST',{name:'reader',scopes:['read']})).json.data.token;assert.equal((await req('/api/v1/bots','GET',null,reader)).json.meta.observed,false);
 const command=await req('/api/v1/sync','POST',{kind:'bot_list'});assert.equal(command.status,202);assert.equal((await req('/api/v1/sync','POST',{kind:'bot_list'})).json.data.id,command.json.data.id);assert.equal((await req('/api/v1/sync','POST',{kind:'bot_list',target:null})).status,400);assert.equal((await req('/api/v1/sync','POST',{kind:'bot_list'},reader)).status,403);
 const payload={available:true,response_verified:true,bots:[{jid:'123@bot',persona_id:'persona-1',token:'secret-value'},{jid:'https://secret.invalid',persona_id:'bad'}],last_success_at:'2026-01-01T00:00:00Z'};db.prepare("INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES('bot_list','wis-5679',?,?)").run(JSON.stringify(payload),new Date().toISOString());const list=(await req('/api/v1/bots?q=persona','GET',null,reader)).json;assert.equal(list.data.length,1);assert.equal(list.data[0].jid,'123@bot');assert.equal(list.meta.wis_automations,false);assert.equal(list.meta.history_complete,false);assert.equal(JSON.stringify(list).includes('secret-value'),false);
 db.prepare("UPDATE snapshots SET payload=json_set(payload,'$.available',json('false'),'$.stale',json('true'),'$.error','secret-value') WHERE kind='bot_list'").run();const failure=(await req('/api/v1/bots')).json;assert.equal(failure.data.length,1);assert.equal(failure.meta.stale,true);assert.equal(failure.meta.error,'read_failed');assert.equal((await req('/api/v1/snapshots?kind=bot_list','GET',null,reader)).status,400);assert.equal((await req('/api/v1/bots','POST',{})).status,404);
 }finally{await new Promise(r=>server.close(r));db.close();}
});
