import test from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync,randomBytes} from 'node:crypto';
process.env.WIS_DB_PATH=':memory:';
const {openDatabase}=await import('../../local/db.mjs');
const {makeServer}=await import('../../local/server.mjs');
test('catalog details use exact IDs and only stored collection members',async()=>{
 const db=openDatabase(':memory:'),password=randomBytes(20).toString('hex'),salt='catalog-test';db.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));const server=makeServer(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';const req=async(path,method='GET',body)=>{const r=await fetch(base+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json(),headers:r.headers};};
 try{assert.equal((await req('/api/v1/products?id=own:p')).status,401);const login=await req('/api/login','POST',{password});cookie=login.headers.get('set-cookie').split(';')[0];const insert=(kind,id,payload)=>db.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run(kind,id,JSON.stringify(payload),new Date().toISOString());
 insert('product','own:p',{id:'p',owner_jid:'own',name:'Product',secret:'hidden-secret',url:'hidden-secret'});insert('collection','own:c',{id:'c',owner_jid:'own',name:'Collection',products_collected:true,products_truncated:true,products:[{id:'nested',name:'Nested',url:'hidden-secret'}]});insert('catalog','other',{available:false});insert('collections','own',{available:false,stale:true,scope:'public_catalog',source:'public_whatsapp_graphql',error:'provider_error',last_attempt_at:'2026-01-02T00:00:00Z',last_attempt_scope:'own_account',last_attempt_source:'checked_baileys_iq_fallback',last_success_at:'2026-01-01T00:00:00Z'});
 const product=(await req('/api/v1/products?id=own:p')).json;assert.equal(product.data.id,'own:p');assert.equal(product.data.product_id,'p');assert.equal(product.meta.collection_status,'observed_partial');assert.equal(product.meta.summaries.length,0);assert.equal(JSON.stringify(product).includes('hidden-secret'),false);assert.equal((await req('/api/v1/products?id=')).status,400);assert.equal((await req('/api/v1/collections?id=missing')).status,404);
 const members=(await req('/api/v1/collection-products?collection_id=own:c')).json;assert.equal(members.data.length,1);assert.equal(members.data[0].id,'nested');assert.equal(members.meta.products_truncated,true);assert.equal(members.meta.collection_status,'unavailable');assert.equal(members.meta.scope,'public_catalog');assert.equal(members.meta.stale,true);assert.equal(members.meta.summaries[0].data.source,'public_whatsapp_graphql');assert.equal(members.meta.summaries[0].data.error,'provider_error');assert.equal(members.meta.summaries[0].data.last_success_at,'2026-01-01T00:00:00.000Z');assert.equal(members.meta.summaries[0].data.last_attempt_at,'2026-01-02T00:00:00.000Z');assert.equal(members.meta.summaries[0].data.last_attempt_scope,'own_account');assert.equal(members.meta.summaries[0].data.last_attempt_source,'checked_baileys_iq_fallback');assert.equal(JSON.stringify(members).includes('hidden-secret'),false);
 insert('collection','own:unknown',{id:'unknown',owner_jid:'none',products_collected:false,products:[]});const unknown=(await req('/api/v1/collection-products?collection_id=own:unknown')).json;assert.equal(unknown.meta.observed,false);assert.equal(unknown.meta.collection_status,'not_collected');assert.equal((await req('/api/v1/collection-products')).status,400);
 }finally{await new Promise(r=>server.close(r));db.close();}
});
