import test from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync,randomBytes} from 'node:crypto';
process.env.WIS_DB_PATH=':memory:';
const {openDatabase}=await import('../../local/db.mjs');
const {makeServer}=await import('../../local/server.mjs');
test('contact catalog requires exact known PN and isolates owners without enabling writes',async()=>{
 const db=openDatabase(':memory:'),password=randomBytes(20).toString('hex'),salt='contact-catalog';db.prepare("INSERT INTO settings(key,value) VALUES('admin_password',?)").run(salt+':'+scryptSync(password,salt,64).toString('hex'));const server=makeServer(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';const req=async(path,method='GET',body,token)=>{const r=await fetch(base+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie,...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json(),headers:r.headers};};
 try{const login=await req('/api/login','POST',{password});cookie=login.headers.get('set-cookie').split(';')[0];const reader=(await req('/api/v1/tokens','POST',{name:'reader',scopes:['read']})).json.data.token;const target='12025550111@s.whatsapp.net';assert.equal((await req('/api/v1/contact-products?target='+target)).status,404);assert.equal((await req('/api/v1/contact-products?target=123@lid')).status,400);assert.equal((await req('/api/v1/contact-products?target=012345678@s.whatsapp.net')).status,400);assert.equal((await req('/api/v1/contact-products?target=1234567@s.whatsapp.net')).status,404);
 db.prepare('INSERT INTO contacts(id,phone_e164,created_at) VALUES(?,?,?)').run('known','+12025550111',new Date().toISOString());assert.equal((await req('/api/v1/contact-products?target='+target,'GET',null,reader)).json.meta.observed,false);const command=await req('/api/v1/sync','POST',{kind:'contact_catalog',target});assert.equal(command.status,202);assert.equal((await req('/api/v1/sync','POST',{kind:'contact_catalog',target})).json.data.id,command.json.data.id);assert.equal((await req('/api/v1/sync','POST',{kind:'contact_catalog',target},reader)).status,403);assert.equal((await req('/api/v1/sync','POST',{kind:'contact_catalog',target,count:5})).status,400);
 const insert=(kind,id,payload)=>db.prepare('INSERT INTO snapshots(kind,resource_id,payload,updated_at) VALUES(?,?,?,?)').run(kind,id,JSON.stringify(payload),new Date().toISOString());insert('product',target+':p',{id:'p',owner_jid:target,name:'Visible',url:'secret-value'});insert('product','other:p',{id:'other',owner_jid:'other',name:'Visible'});insert('catalog',target,{available:false,stale:true,error:'secret-value',scope:'contact_catalog',last_success_at:'2026-01-01T00:00:00Z'});const products=(await req('/api/v1/contact-products?target='+target+'&q=Visible','GET',null,reader)).json;assert.equal(products.meta.total,1);assert.equal(products.data[0].product_id,'p');assert.equal(products.meta.stale,true);assert.equal(products.meta.error,'read_failed');assert.equal(products.meta.scope,'contact_catalog');assert.equal(JSON.stringify(products).includes('secret-value'),false);assert.equal(db.prepare('SELECT count(*) AS n FROM operations').get().n,0);
 }finally{await new Promise(r=>server.close(r));db.close();}
});
