"use client";
import {useEffect,useState} from "react";
type Campaign={id:string;name:string;status:string;daily_limit:number};
export function Campaigns(){
 const [rows,setRows]=useState<Campaign[]>([]),[error,setError]=useState(""),[preview,setPreview]=useState<{eligible:unknown[];excluded:unknown[];missing:unknown[]}|null>(null),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/v1/campaigns",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.data);}
 useEffect(()=>{queueMicrotask(()=>{void load().catch(e=>setError(e.message));});},[]);
 async function run(method:string,body:unknown){setBusy(true);setError("");try{const r=await fetch("/api/v1/campaigns",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);if(j.data?.eligible)setPreview(j.data);await load();}catch(e){setError(e instanceof Error?e.message:"Error de conexión");}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Planificación de campañas</h2><p className="text-sm text-slate-500">Prepará destinatarios y revisá consentimiento. Aprobar el borrador no encola mensajes: la ejecución continúa desactivada.</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run("POST",{name:f.get("name"),body:f.get("body"),contact_ids:String(f.get("ids")).split(/[\s,]+/).filter(Boolean),daily_limit:Number(f.get("limit")),window_start:f.get("start"),window_end:f.get("end")});}}><input required name="name" aria-label="Nombre de campaña" placeholder="Nombre del borrador" className="rounded-lg border p-2"/><input required name="limit" type="number" min="1" max="10000" aria-label="Límite diario" placeholder="Límite diario acordado" className="rounded-lg border p-2"/><textarea required name="body" aria-label="Texto de campaña" placeholder="Texto para revisar" className="rounded-lg border p-2"/><textarea required name="ids" aria-label="IDs de contactos" placeholder="IDs de contactos separados por coma (API /contacts)" className="rounded-lg border p-2"/><label className="text-sm">Desde (Argentina)<input required type="time" name="start" defaultValue="09:00" className="ml-2 rounded-lg border p-2"/></label><label className="text-sm">Hasta (Argentina)<input required type="time" name="end" defaultValue="18:00" className="ml-2 rounded-lg border p-2"/></label><button disabled={busy} className="btn px-4 py-2">Guardar borrador</button></form>{rows.map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-3 text-sm"><span>{row.name} · {row.status} · límite {row.daily_limit}/día</span><div className="flex gap-3">{[["preview","Previsualizar"],["approve","Aprobar borrador"],["pause","Pausar"]].map(([action,label])=><button key={action} disabled={busy} className="text-emerald-700" onClick={()=>void run("PATCH",{id:row.id,action})}>{label}</button>)}</div></article>)}{preview&&<p role="status" className="rounded-lg bg-slate-50 p-3 text-sm">Elegibles: {preview.eligible.length} · Excluidos: {preview.excluded.length} · No encontrados: {preview.missing.length} · Ejecución desactivada</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</section>;
}
