"use client";
import { useCallback, useEffect, useState } from "react";

type Row = Record<string, unknown>;
const cell = (value: unknown) => value == null ? "—" : Array.isArray(value) ? value.join(", ") : typeof value === "object" ? JSON.stringify(value) : String(value);
async function api(path: string, method = "GET", body?: unknown) {
  const response = await fetch(`/api/v1/${path}`, { method, cache: "no-store", headers: { "Content-Type": "application/json" }, ...(body ? {body:JSON.stringify(body)} : {}) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error ?? "No se pudo completar la solicitud");
  return result.data;
}
function Table({rows, columns}: {rows:Row[];columns:[string,string][]}) {return <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{columns.map(([key,label])=><th key={key} className="border-b p-3 text-slate-500">{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id ?? i)}>{columns.map(([key])=><td key={key} className="max-w-sm border-b border-slate-100 p-3 break-words">{cell(row[key])}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-5 text-sm text-slate-500">Sin registros disponibles.</p>}</div>}
export function DashboardTools({admin}:{admin:boolean}) {
  const [operations,setOperations]=useState<Row[]>([]), [contacts,setContacts]=useState<Row[]>([]), [tokens,setTokens]=useState<Row[]>([]), [webhooks,setWebhooks]=useState<Row[]>([]), [capabilities,setCapabilities]=useState<Row[]>([]);
  const [errors,setErrors]=useState<Record<string,string>>({}), [secret,setSecret]=useState<string|null>(null), [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{await Promise.all([...["operations","contacts","capabilities"],...(admin?["tokens","webhooks"]:[])].map(async name=>{try {const data=await api(name);const rows=Array.isArray(data)?data:(data?.capabilities ?? data?.methods ?? []);({operations:setOperations,contacts:setContacts,tokens:setTokens,webhooks:setWebhooks,capabilities:setCapabilities}[name]!)(rows);setErrors(prev=>({...prev,[name]:""}));}catch(e){setErrors(prev=>({...prev,[name]:e instanceof Error?e.message:"Error de conexión"}));}}));},[admin]);
  useEffect(()=>{void refresh();},[refresh]);
  async function mutate(path:string,method:string,body?:unknown) {setBusy(true);setErrors(prev=>({...prev,action:""}));try {const result=await api(path,method,body);if(result?.token||result?.secret)setSecret(result.token??result.secret);await refresh();}catch(e){setErrors(prev=>({...prev,action:e instanceof Error?e.message:"Error de conexión"}));}finally{setBusy(false);}}
  const panel="space-y-4 rounded-2xl border border-slate-200 bg-white p-6";
  const input="rounded-lg border border-slate-300 p-2 text-sm";
  return <div className="space-y-8">
    {Object.entries(errors).filter(([,v])=>v).map(([k,v])=><p key={k} role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{k}: {v}</p>)}
    <section id="operaciones" className={panel}><div className="flex justify-between"><h2 className="text-xl font-semibold">Operaciones recientes</h2><button onClick={()=>void refresh()} className="text-sm text-emerald-700">Actualizar</button></div><p className="text-sm text-slate-500">Últimas 50 operaciones. Aceptado en cola no significa entregado. No reintentes un resultado desconocido sin reconciliarlo.</p><Table rows={operations} columns={[["created_at","Fecha"],["to_e164","Destino"],["type","Tipo"],["status","Estado"],["last_error","Incidencia"]]} /></section>
    <section id="contactos" className={panel}><h2 className="text-xl font-semibold">Contactos y consentimiento</h2><Table rows={contacts} columns={[["display_name","Nombre"],["phone_e164","Teléfono"],["consent_at","Consentimiento"],["consent_source","Origen"],["opted_out_at","Baja"]]} />{admin && <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("contacts","POST",{phone_e164:f.get("phone"),display_name:f.get("name")});}}><input className={input} name="name" placeholder="Nombre" required aria-label="Nombre del contacto"/><input className={input} name="phone" placeholder="+549…" pattern="\+[1-9][0-9]{7,14}" required aria-label="Número completo E.164"/><button disabled={busy} className="btn px-4">Crear sin consentimiento</button></form>}<p className="text-xs text-slate-500">La creación de un contacto no autoriza envíos. El consentimiento y las bajas se registran mediante la API documentada.</p></section>
    <section id="integraciones" className={panel}><h2 className="text-xl font-semibold">Python y n8n</h2><p className="text-sm text-slate-500">Usá /api/v1 con Authorization: Bearer y un Idempotency-Key único por envío. La sesión permanece en el worker.</p><a href="/api/v1/openapi" className="inline-block text-sm text-emerald-700 underline">Especificación OpenAPI</a>{admin && <><h3 className="font-semibold">Tokens por conexión</h3><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate("tokens","POST",{name:f.get("name"),scopes:f.getAll("scope")});}}><input className={input} name="name" required maxLength={80} placeholder="Nombre de integración" aria-label="Nombre del token"/>{["read","send","contacts:write","webhooks:write"].map(scope=><label key={scope} className="flex items-center gap-1 text-sm"><input type="checkbox" name="scope" value={scope} defaultChecked={scope==="read"}/>{scope}</label>)}<button disabled={busy} className="btn px-4">Crear token</button></form>{tokens.map(token=><div className="flex flex-wrap justify-between gap-2 border-b py-3 text-sm" key={String(token.id)}><span>{cell(token.name)} · {cell(token.scopes)} · {token.revoked_at?"Revocado":"Activo"}</span>{!token.revoked_at && <button disabled={busy} className="text-red-700" onClick={()=>void mutate(`tokens?id=${encodeURIComponent(String(token.id))}`,"DELETE")}>Revocar</button>}</div>)}<h3 className="pt-3 font-semibold">Webhooks</h3><p className="text-sm text-slate-500">Se crean desactivados. Activarlos requiere una configuración revisada; cada evento lleva firma e identificador.</p><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void mutate("webhooks","POST",{url:new FormData(e.currentTarget).get("url")});}}><input className={`${input} grow`} type="url" name="url" placeholder="https://…" required aria-label="URL de webhook"/><button disabled={busy} className="btn px-4">Guardar desactivado</button></form><Table rows={webhooks} columns={[["url","URL"],["enabled","Habilitado"],["created_at","Creación"]]}/></>}{secret && <div className="rounded-xl bg-amber-50 p-4"><p className="text-sm font-semibold">Secreto visible una única vez. Guardalo en tu gestor de secretos.</p><code className="mt-2 block break-all text-xs">{secret}</code><button className="mt-3 text-sm underline" onClick={()=>setSecret(null)}>Ya lo guardé · Ocultar</button></div>}</section>
    <section id="capacidades" className={panel}><h2 className="text-xl font-semibold">Cobertura del catálogo WHAPI</h2><p className="text-sm text-slate-500">La matriz distingue implementación local, soporte parcial y funciones pendientes. La verificación en vivo requiere pruebas autorizadas.</p><Table rows={capabilities} columns={[["name","Función"],["endpoint","API local"],["status","Estado"],["reason","Alcance / limitación"]]}/></section>
  </div>;
}
