"use client";
/* eslint-disable @next/next/no-img-element -- QR is a temporary in-memory data URL. */
import { useCallback,useEffect,useState } from "react";
type Connection={status:string;phone:string|null;qr_payload:string|null;qr_expires_at:string|null;expected_phone_e164?:string|null;updated_at?:string;last_error:string|null};
export function WhatsappSettingsClient({sectorDisplayName}:{sectorDisplayName:string}) {
  const [identityNotice,setIdentityNotice]=useState<string|null>(null);
  const [connection,setConnection]=useState<Connection|null>(null),[error,setError]=useState<string|null>(null),[hint,setHint]=useState<string|null>(null),[qr,setQr]=useState<{payload:string;url:string}|null>(null),[now,setNow]=useState(0),[busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{try{const r=await fetch("/api/whatsapp/connection",{cache:"no-store"});if(!r.ok)throw new Error("No se pudo consultar la conexión.");const j=await r.json();setConnection(j.connection);setHint(j.workerHint);setError(null);}catch(e){setError(e instanceof Error?e.message:"Error de conexión");}},[]);
  useEffect(()=>{queueMicrotask(()=>{void refresh();});const t=setInterval(()=>{setNow(Date.now());void refresh();},2500);return()=>clearInterval(t);},[refresh]);
  const payload=connection?.qr_payload;
  useEffect(()=>{let cancelled=false;if(payload)void import("qrcode").then(async m=>{const url=await m.default.toDataURL(payload,{width:280,margin:2});if(!cancelled)setQr({payload,url});}).catch(()=>setError("No se pudo dibujar el QR."));return()=>{cancelled=true;};},[payload]);
  async function action(path:string){setBusy(true);try{const r=await fetch(`/api/whatsapp/${path}`,{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.hint??"No se pudo completar la operación.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Error de conexión");}finally{setBusy(false);}}
  async function saveIdentity(form:FormData){setBusy(true);setIdentityNotice(null);try{const r=await fetch("/api/whatsapp/identity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_phone_e164:form.get("expected_phone_e164")})});const j=await r.json();if(!r.ok)throw new Error(j.hint??"No se pudo guardar la identidad.");setIdentityNotice("Número completo guardado. Los envíos continúan sujetos a habilitación y consentimiento.");await refresh();}catch(e){setIdentityNotice(e instanceof Error?e.message:"Error al guardar la identidad");}finally{setBusy(false);}}
  const identityVerified=connection?.status==="connected" && Boolean(connection.expected_phone_e164 && connection.phone && connection.phone.replace(/\D/g,"")===connection.expected_phone_e164.slice(1));
  const expires=connection?.qr_expires_at?Date.parse(connection.qr_expires_at):0;
  const valid=expires>now && now>0 && connection?.status==="qr_pending" && qr?.payload===payload;
  const statuses:Record<string,string>={connected:"Conectada",disconnected:"Desconectada",qr_pending:"Esperando vinculación"};
  return <div className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6"><div><h2 className="text-xl font-semibold">{sectorDisplayName}</h2><p className="mt-2 text-sm">Estado: <strong>{statuses[connection?.status??""]??"Consultando…"}</strong></p><p className="mt-2 text-sm">Identidad de WhatsApp: {connection?.phone??"Todavía no disponible"}</p><p className="mt-2 text-sm">Número esperado: {connection?.expected_phone_e164??"Falta configurar el número completo antes de habilitar envíos"}</p>{connection?.updated_at&&<p className="mt-2 text-xs text-slate-500">Última actualización: {connection.updated_at}</p>}</div>
    <section className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">Confirmar la línea completa</h3><p className={`text-sm ${identityVerified?"text-emerald-700":"text-amber-800"}`}>{identityVerified?"Identidad verificada: el número configurado coincide con la línea conectada.":"Identidad sin verificar. Conectar la sesión no confirma por sí solo la línea esperada."}</p><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void saveIdentity(new FormData(e.currentTarget));}}><input name="expected_phone_e164" type="tel" aria-label="Número completo esperado en formato E.164" placeholder="Número completo: +549…5679" pattern="\+[1-9][0-9]{7,14}" maxLength={16} required className="min-w-0 grow rounded-lg border border-slate-300 p-3 text-sm"/><button disabled={busy} className="rounded-lg border border-emerald-700 px-4 py-3 text-sm text-emerald-800 disabled:opacity-40">Guardar identidad</button></form><p className="text-xs text-slate-500">Incluí el código de país. Podés configurarlo antes del QR o confirmar la identidad informada por WhatsApp. Esto no habilita envíos.</p>{identityNotice&&<p role="status" className="text-sm">{identityNotice}</p>}</section>
    {connection?.last_error && <p role="status" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Incidencia: {connection.last_error}</p>}{hint&&<p className="text-sm text-slate-500">{hint}</p>}
    <div className="flex flex-wrap gap-3"><button disabled={busy||connection?.status==="connected"} onClick={()=>void action("connect")} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Solicitar conexión / QR</button><button disabled={busy||connection?.status==="disconnected"} onClick={()=>{if(window.confirm("Cerrar la sesión vinculada requiere escanear un nuevo QR. ¿Desconectar?"))void action("disconnect");}} className="rounded-xl border border-slate-300 px-4 py-3 text-sm disabled:opacity-40">Cerrar sesión vinculada</button></div>
    {valid&&qr ? <section className="rounded-xl bg-slate-50 p-5"><h3 className="font-semibold">Escaneá desde tu teléfono</h3><p className="mt-2 text-sm text-slate-600">WhatsApp → Dispositivos vinculados → Vincular un dispositivo.</p>{ }<img src={qr.url} alt="QR privado para vincular tu línea de WhatsApp" width={280} height={280} className="my-4 bg-white"/><p className="text-xs text-slate-500">Vence en {Math.max(0,Math.ceil((expires-now)/1000))} segundos. No compartas este código.</p></section>:connection?.status==="qr_pending"?<p role="status" className="text-sm text-slate-500">Esperando un QR vigente del worker. Los códigos vencidos se ocultan automáticamente.</p>:null}
    <p className="border-t pt-4 text-xs text-slate-500">Reiniciar el servidor conserva la sesión. Cerrar sesión la revoca. No se enviarán mensajes de prueba desde esta pantalla.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
  </div>;
}
